### PR TITLE
Update GeoServerDataDirectory.java

### PR DESCRIPTION
**Pull request by NewbieOfUESTC**
change for maven build error.

### CODE REVIEW

**Comment by NewbieOfUESTC** [comment]
It's the first time to use github.

**Comment by aaime** [comment]
Hi, we need  a description of what your change is doing, a reference to a ticket in jira, and a test that covers this change.

**Comment by aaime** [comment]
By the way, is this change the same, or similar, to the one at #910 ?

**Comment by koordo** [comment]
Exactly the same problem but a bit different solutions.

**Comment by aaime** [comment]
Can we get just one solution, and have it tested at least interactively? :)

**Comment by aaime** [comment]
I've merged #910, closing this one, please re-open or make a new pull request in case we are still not covering some case.

**Pull request closed without merging**
