### PR TITLE
[GEOS-9735] Wfs-templating, add @context validation for json-ld output [GEOS-9737] Rename wfs-templating module

### PR DESCRIPTION
**Pull request by taba90**
Jira ticket 
https://osgeo-org.atlassian.net/browse/GEOS-9735
https://osgeo-org.atlassian.net/browse/GEOS-9737

This pullrequest:
- add a validation against the @context for the json-ld output in wfs-templating module. To provide it, it takes advantage  of the algorithms provided by the json-ld api.
- rename the wfs-tempalting module to features-templating module
## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [x] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [x] New unit tests have been added covering the changes
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [x] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by taba90** [comment]
builds error caused by download failiure looks unrelated
[ERROR] Failed to execute goal on project geoserver: Could not resolve dependencies for project org.geoserver:geoserver:pom:2.19-SNAPSHOT: Failed to collect dependencies at org.geotools:gt-main:jar:25-SNAPSHOT: Failed to read artifact descriptor for org.geotools:gt-main:jar:25-SNAPSHOT: Could not find artifact org.geotools:library:pom:25-SNAPSHOT in osgeo-snapshots (https://repo.osgeo.org/repository/snapshot/) -> [Help 1]

**Comment by tbarsballe** [comment]
This PR is causing build failures on master, and should not have been merged with active CI failures:

```
     [exec] /home/travis/build/geoserver/geoserver/doc/en/user/source/community/features-templating/index.rst:4: WARNING: Title underline too short.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

Please fix this before merging any backports

**Comment by ianturton** [comment]
Do we need to revert this until the docs are fixed?

**Comment by mprins** [comment]
there's a fix on master in 56661236d2cde3b7d6c3d721849fda8f6e24f150

**Pull request merged**
