### PR TITLE
[GEOS-8240] Fix "Forwarded" header name, add user docs

### PR DESCRIPTION
**Pull request by lmoran**
- Fixed the name of the "Forwarded" header
- Added user documentation (English only)

Dee discussion: https://github.com/geoserver/geoserver/commit/3c05cfb84151fbcdf5bde6d4d42faa4d743673e9#commitcomment-29588575

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
@lmoran the Travis CI failure is a formatting check failure in `src/main/src/test/java/org/vfny/geoserver/util/URLProxifyingTest.java`. Building the gs-main module is a convenient way to run the formatter and fix this problem.

**Comment by lmoran** [comment]
The formatting...  well, I wasn't able to build the `main` module once I pulled the latest changes from master, because of:
```
/geoserver/src/main/src/main/java/org/geoserver/catalog/util/LegacyCatalogImporter.java:[455,16]` error: no suitable constructor found for ReferencedEnvelope(org.locationtech.jts.geom.Envelope,DefaultGeographicCRS)
[ERROR]     constructor ReferencedEnvelope.ReferencedEnvelope(Rectangle2D,CoordinateReferenceSystem) is not applicable
[ERROR]       (argument mismatch; org.locationtech.jts.geom.Envelope cannot be converted to Rectangle2D)
```
There are similar-sounding errors in other classes as well.

**Comment by aaime** [comment]
@lmoran it's likely due to the recent switch to JTS 1.15.1, which changed package from "com.vividsolutions" to "org.locationtech". Long story short, you need a fresh build of geotools and an up to date checkout of GeoServer.

**Comment by dromagnoli** [comment]
The fix looks correct to me. I have applied that "PR" on my code since I was having issues with the layerPreview so now I can see the layerPreviews. Travis tests are failing but I think they are unrelated to the changes made by @lmoran.
I did a full build without -Prelease,communityRelease and it was successfully.
Adding those profiles to my maven build, I'm getting some different test failures (on worldwind and some others) but they look unrelated to this fix again.

Anyone else has other feedbacks?

**Comment by aaime** [comment]
@dromagnoli If you have tests running in the build, -Prelease is all you can do, community modules are run in a secondary build with tests disabled and have indeed many failure (getting test coverage and making that a blocker for people changing core is a privilege for extension modules, it's the reason to push people to go and make the module supported).
So when you run -PcommunityRelease, you should always also add -DskipTests.

**Comment by aaime** [comment]
By the way, I've restarted the build again... already did once this morning, think I saw the same WCS failures, though I agree I don't understand where they are coming from.

**Comment by dromagnoli** [comment]
travis is back to green!  :)

**Comment by aaime** [comment]
image

**Comment by aaime** [comment]
Changes look fair to me, merging

**Comment by bencaradocdavies** [comment]
I kicked the Jenkins CITE tests as they should now be fixed.

**Comment by lmoran** [comment]
Fixed as a consequence of this PR @bencaradocdavies ?

**Comment by bencaradocdavies** [comment]
Yes @lmoran, the CITE tests have recovered.

**Pull request merged**
