### PR TITLE
GEOS-11607 Bugfix - KML WMS GetMap is performing a heavy database load query

### PR DESCRIPTION
**Pull request by tiago-s-vieira-alb**
[GEOS-11607](https://osgeo-org.atlassian.net/browse/GEOS-11607) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

JIRA ISSUE:
https://osgeo-org.atlassian.net/browse/GEOS-11607
  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [X] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [X] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [X] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [X] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by tiago-s-vieira-alb** [comment]
Tests are failing. We'll take a look.

**Comment by tiago-s-vieira-alb** [comment]
@aaime , the KMLTest "testRasterLayer" is failing after our change, on this assertion:

assertXpathEvaluatesTo("1", "count(//kml:GroundOverlay)", dom);

`[ERROR] testRasterLayer(org.geoserver.kml.KMLTest)  Time elapsed: 0.021 s  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<[1]> but was:<[0]>
        at org.geoserver.kml.KMLTest.testRasterLayer(KMLTest.java:772)
`

I'm not familiar with the GroundOverlay attribute, and if it makes sense the changed result value.

Can you take a look please?

Thanks

**Comment by tiago-s-vieira-alb** [comment]
The unit test that I've done **testLayerLookAt** executes successfully.
The problem is with an existing unit test **testRasterLayer** that started to crash, when changing the decorator for the Layer.

**Comment by aaime** [comment]
@tiago-s-vieira-alb when running against a raster layer context.getCurrentFeatureCollection returns null, a NPE occurs, and the test fails.

Something like this should address the issue (untested):

```java
            Layer currentLayer = context.getCurrentLayer();
            Envelope bounds;
            if (currentLayer instanceof FeatureLayer) {
                bounds = context.getCurrentFeatureCollection().getBounds();
            } else {
                bounds = currentLayer.getBounds();
            }
```

**Comment by tiago-s-vieira-alb** [comment]
It works!
Thank you

**Comment by tiago-s-vieira-alb** [comment]
Hi,

The pipeline "Linux JDK GitHub CI / build (21, temurin, ubuntu-22.04)" is failing because:
`Error: 6,291 [ERROR] Could not acquire lock(s)
Error: 6,291 [ERROR] java.lang.IllegalStateException: Could not acquire lock(s)
Error: 6,291 [ERROR] Could not acquire lock(s)
Error: 6,291 [ERROR] Could not acquire lock(s)
Error: 6,291 [ERROR] `

How can I launch it again?
It doesn't seem to be related with the changes of this PR.

**Comment by mprins** [comment]
>  java.lang.IllegalStateException: Could not acquire lock(s)

that problem seems to be fixed in the main branch (as of https://github.com/geoserver/geoserver/pull/8063), if you rebase your branch it should pass.

for now I've restarted the failing build

**Comment by tiago-s-vieira-alb** [comment]
Same error, but now in the "Assembly GitHub CI / build (ubuntu-22.04, 11, temurin)"

**Comment by tiago-s-vieira-alb** [comment]
All green! :)
May you proceed with the merge to main?
Thanks

**Comment by tiago-s-vieira-alb** [comment]
> Merged. The bot failed to backport despite my squash-merge, if you want to have it on 2.26.x and 2.25.x you'll have to cherry-pick [26ed595](https://github.com/geoserver/geoserver/commit/26ed5955b7e78fb993b0949fb1a6791af5356eee) manually and issue PRs targeting the respective branches.

We can wait for the main release (27.x).
Thank you

**Pull request merged**
