### PR TITLE
GEOS-6904: Removing wps-sextante community module

### PR DESCRIPTION
**Pull request by dromagnoli**

### CODE REVIEW

**Comment by ahuarte47** [comment]
Hi, we use the wps-sextante module with GeoServer 2.4 in our organization. We had to rewrite this wrapper to run sextante processes successfully.

https://github.com/ahuarte47/geoserver/compare/geoserver:2.4.x...2.4.x-tcsa_changes

Unfortunately we have not yet uploaded all necessary changes in the official repository of geoserver for 2.4 and master branches.

The wps-sextante module will be definitely removed ?

Alvaro

**Comment by dromagnoli** [comment]
Hi Alvaro,
I'm moving this discussion to the GeoServer mailing list where we have
initially asked if anyone need it, so we can discuss that further before
really removing it.

The "official" module doesn't build on GeoServer since 4 years so I think
it isn't helpful for you too.
If you could merge your branch on GeoServer we won't remove that.

Please, let us know.
Best Regards,
Daniele



==
GeoServer Professional Services from the experts! Visit
http://goo.gl/NWWaa2 for more information.
==

Ing. Daniele Romagnoli
Senior Software Engineer

GeoSolutions S.A.S.
Via Poggio alle Viti 1187
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:      +39 0584 1660272

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by aaime** [comment]
It is removed because nobody is maintaining it and has not been working for several years. If you want to donate a working version and maintain it, you're more than welcomed to do so :-)
The 2.4.x series has been dead for more than 6 months, so no changes will be performed there, but you should definitely make a pull request for 2.8.x

**Comment by ahuarte47** [comment]
Hi, I released an initial pull request with the changes needed to compile the wps-module.

https://github.com/geoserver/geoserver/pull/940

But I would like debug it to test some sextante processes, but although I can compile successfully with mvn in console, when I import the geoserver projects in eclipse I get many errors about invalid references (gs-main, when the project is named main, and so on) any idea ?

Thank you very much!
Alvaro

**Comment by aaime** [comment]
GeoServer has changed a lot since 2.4, one of the changes is that the module names are now all prefixed with gs- (just like the geotools ones are prefixed with -gt) even if the directory name does not have the prefix.

**Comment by ahuarte47** [comment]
I updated and rebased my fork and activate the master branch in my local repository (previously I did a full clean). To recreate the eclipse projects of geoserver I use "mvn eclipse:eclipse -Pwps,sextante", then where is my mistake ? I must rename manually the projects in eclipse adding the "gs-" prefix.

Thanks in avance
Alvaro

**Comment by aaime** [comment]
You have to drop all projects from eclipse, do a eclipse:clean eclipse:eclipse, and then re-import them

**Comment by ahuarte47** [comment]
Hi Andrea, thanks for your reply, I did "mvn eclipse:clean" and I get same errors.

eclipse-juno 4 2-geoserver-master_errors

**Comment by aaime** [comment]
It seems you did not remove your projects from eclipse before starting, as I recommended?

**Comment by ahuarte47** [comment]
Yes, I remove the projects, clean, create and restarted eclipse and I re-import them, I must change manually the build path of the projects in order to it works ok.

**Comment by ahuarte47** [comment]
Hi Andrea, as you known I am released two new PR's related with this.

https://github.com/geoserver/geoserver/pull/942
https://github.com/geoserver/geoserver/pull/943

I met with these individual problems using the processe of the wps-sextante module. I have reproduced them in the master branch. It is possible that these errors appear in other processes but I could not check.

I know that I must provide junit tests but I am newer about it. I promise try it! I only want help in as far as possible. Thank you very much for your patience.

Best Regards
Alvaro

**Comment by ahuarte47** [comment]
Hi, I think that this PR can be closed, the clonficts were resolved in other commit merged ( https://github.com/geoserver/geoserver/commit/9a51904a5647d778d28ef64b4ca3a5f71dd6f7fd )

Best regards
Alvaro

**Comment by dromagnoli** [comment]
Thank for your effort, Alvaro.

**Comment by ahuarte47** [comment]
Thanks Daniele!

**Pull request closed without merging**
