### PR TITLE
Added the Error Prone Compiler steps to IntelliJ Quickstart

### PR DESCRIPTION
**Pull request by vava23**
GeoServer uses Error Prone tool which is not compatible with Java 8 and causes a compile error. However, Java 8 is the preferrable version according to documentation.

The issue can be easily fixed by installing the Error Prone Compiler plugin. I propose updating the developer documentation to reflect this step.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by aaime** [comment]
ErrorProne should not be active by default, it's part of the maven build only if "qa" system variable is set (e.g., "-Dqa" in the build).
Not sure why IntelliJ ends up using it on some machines, looks like an IntelliJ bug to me.

I don't have it enabled in my IntelliJ and would not recommend doing so, the GeoServer code base is massive, the last thing one needs is to slow down the compiler IMHO. Best to finish the work, and do the QA checks in a build (which include errorprone, but also PMD and Spotbugs) as the last step before committing code.

**Comment by vava23** [comment]
>ErrorProne should not be active by default, it's part of the maven build only if "qa" system variable is set (e.g., "-Dqa" in the build).

I see. That's what I got right after importing the project:
изображение

>I don't have it enabled in my IntelliJ and would not recommend doing so, the GeoServer code base is massive, the last thing one needs is to slow down the compiler IMHO.

Fair enough. Sorry for the straightforward suggestion. That did the trick for me, but I've got not so much experience in Java so far. Maybe there are some more reasonable ways to fix the issue. Seems that switching to _errorprone8_ profile doesn't help, but I should try it once again.

**Comment by aaime** [comment]
Maybe the text can be amended to state that one either:

- Disables the errorprone profile (anyone has a clue why some people get it on by default?)
- Adds the necessary plugins to IDEA, with a warning that the builds will be slower.

With those changes I'd be happy to merge the docs changes.

**Comment by vava23** [comment]
Done that. Also moved the text under **Run GeoServer from Intellij** paragraph, as it seems to be just one of possible issues.

**Comment by aaime** [comment]
Looks good thanks, merging.

**Pull request merged**
