### PR TITLE
[GEOS-9937] Name of styles with colons are incorrect in REST API

### PR DESCRIPTION
**Pull request by shadab-geo**
[GEOS-9937](https://osgeo-org.atlassian.net/browse/GEOS-9937)

  

[GEOS-9937](https://osgeo-org.atlassian.net/browse/GEOS-9937)

In the current implementation, it looks that anything present before the colon in style name is considered as a workspace name. It proceeds even if the workspace with the given name is not present. This fix assigns workspace name only if one with the given name exists

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by dromagnoli** [comment]
Hi @shadab-geo, please, make sure to add a new test for that fix

**Comment by nmco** [comment]
@dromagnoli I'm wondering if having a style name with colons makes sense:
- How can we actually create a style with colons? By editing manually the data directory?
- How will this play out with the workspace prefix business when querying the data?
- How will this play out with GWC?

More I think about this, more I think that we should discuss with the community if layers names, style names, etc ... shall be allowed to have a colon don't he name.

**Comment by dromagnoli** [comment]
> @dromagnoli I'm wondering if having a style name with colons makes sense:
> 
I suspect older versions of GeoServer allow for that so the user reporting the bug was using these as a sort of prefix or label for categorization.

> * How can we actually create a style with colons? By editing manually the data directory?
Yep, with the current code, that's the only way to do that and replicate the issue.

> * How will this play out with the workspace prefix business when querying the data?
> * How will this play out with GWC?
> 
> More I think about this, more I think that we should discuss with the community if layers names, style names, etc ... shall be allowed to have a colon don't he name.

Yep. And/Or, if we want to drop this kind of "legacy-support" we should put a note in the upgrading pages from older versions.

**Comment by nmco** [comment]
Makes sense @dromagnoli I think about older users, thanks for the explanation.

**Pull request closed without merging**
