### PR TITLE
GWC Rest Integration

### PR DESCRIPTION
**Pull request by tbarsballe**
Configuration changes to support the new MVC-based GeoWebCache rest API, when embedded in GeoServer.

Depends upon https://github.com/GeoWebCache/geowebcache/pull/539

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
Those muppets at Travis CI have started setting `_JAVA_OPTIONS`:
https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/

**Comment by bencaradocdavies** [comment]
I am looking for docs but I think `_JAVA_OPTIONS` trumps JVM command line options, resulting in builds being killed for exceeding memory limits.

**Comment by bencaradocdavies** [comment]
Closed/reopened to pickup new Travis options to remove `_JAVA_OPTIONS`.

**Comment by bencaradocdavies** [comment]
Good grief it is still using the old `.travis.yml`.

**Comment by bencaradocdavies** [comment]
Now that Travis has passed on master, trying another close/reopen to see if the new settings are honoured.

**Comment by bencaradocdavies** [comment]
Latest Travis build is running with no `_JAVA_OPTIONS`!

**Comment by bencaradocdavies** [comment]
Build still fails, this time the failure is in gs-gwc, which makes a great deal more sense. Are ares or apollo deploying the new artifacts?

**Comment by bencaradocdavies** [comment]
My mass `.travis.yml` fixes should retrigger the GeoWebCache build.

**Comment by bencaradocdavies** [comment]
I can confirm the gs-gwc failure locally.

**Comment by bencaradocdavies** [comment]
Not expected to pass but one more close/reopen to ensure the Travis build for this PR has the latest settings.

**Comment by tbarsballe** [comment]
Test failures fixed.

**Pull request merged**
