### PR TITLE
Openlayers3 Freemarker template parameters fix

### PR DESCRIPTION
**Pull request by fernandor777**
Template Fix + Test to check parameters encode

### CODE REVIEW

**Comment by aaime** [comment]
I'm guessing this pull request fails because it got crossed in the middle of the JTS upgrade, since it's not finding some new JAI-EXT/JTS related coordinate sequence.
@fernandor777 maybe try to upgrade this branch to the latest GeoServer master and see if that helps.

**Comment by fernandor777** [comment]
Thanks, Andrea, updated and now passes all checks.

**Comment by aaime** [comment]
Looks good, thanks

**Comment by aaime** [comment]
I've merged and backported to 2.13.x
Picking on 2.12.x results in conflicts in the tests. We don't have a 2.12.x scheduled for release, but sometimes a sponsor or a volunteer shows up that wants to do such release anyways, so could you have a look at backporting there too?

**Comment by fernandor777** [comment]
It's fine, I'll try the 2.12.x backport

**Pull request merged**
