### PR TITLE
GEOS-7020: fixed VectorRenderingLayerIdentifier bounds / size calcula…

### PR DESCRIPTION
**Pull request by mbarto**
…tion to have a more precise scale factor calculation.

### CODE REVIEW

**Comment by aaime** [comment]
+1

**Comment by bencaradocdavies** [comment]
@aaime why +1 when this breaks Travis CI on OpenJDK?
https://osgeo-org.atlassian.net/browse/GEOS-7023

**Comment by aaime** [comment]
@bencaradocdavies why do we only hear complaints from you?
I've reviewed the change and gave a plus one, but I'm not a compiler, is that so hard to understand for you?

**Comment by mbarto** [comment]
fyi: I am working on it, seems to be an issue with antialiasing not turned off and handled differently by the different JVM

**Comment by bencaradocdavies** [comment]
Thanks @mbarto, I saw https://github.com/geoserver/geoserver/pull/1067 and will test it on openjdk7.

No problem @aaime, I do not think everyone has learned to expect working Travis CI as it was broken for so long. I think it is merger's responsibility to check, but this is not yet agreed or clear.

**Comment by bencaradocdavies** [comment]
@mbarto, I think your analysis is correct. OpenJDK uses a different antialiasing implementation and we have previously seen failures caused by this in, if I recall correctly, gt-render.

**Pull request merged**
