### PR TITLE
Fix incorrect log message

### PR DESCRIPTION
**Pull request by dbaston**
Hopefully such a small PR isn't annoying, but I noticed this in my logs and thought it was worth fixing.

### CODE REVIEW

**Comment by aaime** [comment]
Yep good one. I can apply it directly to master, with no backport, and close an eye, or if you could create a ticket for it and make the commit message be "[GEOS-XYWZ] Title of the message" do also a backport?

**Comment by dbaston** [comment]
@aaime If going through the trouble to ticket and backport, should I go a bit futher standardize the format of all of these log messages?

**Comment by aaime** [comment]
As you prefer :-)

**Comment by aaime** [comment]
Opened [ticket](https://osgeo-org.atlassian.net/browse/GEOS-8685), rewrote commit message and manually merged on 2.13.x, 2.12.x

**Pull request closed without merging**
