### PR TITLE
[WIP] Request tracing

### PR DESCRIPTION
**Pull request by rcoup**
Initial implementation of per-request identifiers for tracing, as discussed [on the list](https://www.mail-archive.com/geoserver-devel@lists.sourceforge.net/msg32694.html) a while ago. Work-in-progress PR for review/discussion.

High-level overview:
- Generate a UUID (or pull it from a request Header enabled via `-D GEOSERVER_REQUEST_TRACE_HEADER=X-MyRequest-ID` for reverse-proxies)
- Attach to the HttpServletRequest and the OWS Request object
- Set it in the logging [MDC](http://logback.qos.ch/manual/mdc.html), so it can be logged via `%X{requestTraceID}`. 
- Return it via a response header (either custom request header name, or `GeoServer-Request-ID`)
- Pass it into the monitoring extension, write into the XML audit log, and persist into Hibernate
- Transfer across threads into async tasks
- Make available to the stores via the EnvironmentInject mechanism
### Hibernate Monitoring

For [Monitoring minor upgrade docs](http://docs.geoserver.org/latest/en/user/extensions/monitoring/upgrade.html#minor-upgrades):

> **Column remote_user_agent added to request table**
> 
> No action should be required here as Hibernate will simply append the new column to the table. If for some reason this does not happen the column can be added manually:
> 
> `ALTER TABLE request ADD COLUMN trace_id VARCHAR(64);`
### Passing to Datastores

Pass to PostgreSQL backends via:
1. Store session startup SQL: `SET application_name='${TRACEID}';`
2. Store session close-up SQL: `SET application_name='';`
3. In Postgresql configuration, set `log_line_prefix='(%a) '` to log the trace IDs in slow-statement/locks/error/etc logs

For Oracle, I think you can do something similar via [`DBMS_APPLICATION_INFO.SET_CLIENT_INFO`](http://www.toadworld.com/platforms/oracle/w/wiki/2367.dbms-application-info-set-client-info).
### Todo
- [x] pass through to PostGIS datastores
- [ ] pass through to cascaded WXS datastores
- [ ] async/threadlocaltransfer is untested atm
- [ ] tests for all the parts
- [ ] tidy up copyright/etc messages
### Questions
1. Should any default logging formats be updated to include the trace IDs?
   - Andrea is +1

### CODE REVIEW

**Comment by aaime** [comment]
Hi @rcoup wondering if this is still a work in progress or meant to be reviewed? The build failure is strange, but I restarted the build yesterday and it occurred again in the same position... it could well be the code just needs a rebase.

**Comment by rcoup** [comment]
Still a WIP, I've been on leave for a few weeks. Review welcome on anything you notice, otherwise i'll start working on tests next. Will rebase & repush and see if the build clears up.

**Comment by aaime** [comment]
Hi @rcoup this has been stuck for many months? Will you resume work?
Otherwise we can open a ticket to track the work in progress, link to this pull request, and close it until someone can complete the work.

**Comment by rcoup** [comment]
Yeah, close it :) Thinking it probably needs reworking to match http://opentracing.io/ rather than doing our own thing.

**Pull request closed without merging**
