### PR TITLE
Fixing GEOMETRY_COLUMNS create table code snippit

### PR DESCRIPTION
**Pull request by Illutax**
The types "LINE", "COLLECTION", "MULTILINE", "GEOMETRY" are not supported.

Supported Simple types are:

-Point
-LineString
-CircularString
-CompoundCurve
-Polygon
-CurvePolygon

Collection types are:
-MultiPoint
-MultiLineString
-MultiPolygon
-GeometryCollection

Source: https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-types-overview?view=sql-server-ver15

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [X] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Review by mprins — CHANGES_REQUESTED** [review]
I don't think this is correct; the values in this TYPE column are AFAIK the names of JTS geometry classes, not native database types.

See:  https://github.com/geotools/geotools/blob/5d5f62f4f3f409f506bd941ac877744b6dfe83cc/modules/library/main/src/main/java/org/geotools/geometry/jts/Geometries.java#L84-L110


/cc @aaime

**Comment by Illutax** [comment]
> I don't think this is correct; the values in this TYPE column are AFAIK the names of JTS geometry classes, not native database types.
> 
> See: https://github.com/geotools/geotools/blob/5d5f62f4f3f409f506bd941ac877744b6dfe83cc/modules/library/main/src/main/java/org/geotools/geometry/jts/Geometries.java#L84-L110
> 
> /cc @aaime

I've encountered an problem when trying to add a layer containing a jts.MultiLineString. The GeoServer logged an ContractViolation in doing so.

**Comment by aaime** [comment]
@mprins the geometry type lookup is a SQLServer specific issue, the code doing the lookup is here:
https://github.com/geotools/geotools/blob/029dc5c8ccc503de3cfd7f4d1c939d8056c260c4/modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDialect.java#L327

Once it has found the geometry type name as a string, it checks it against the TYPE_TO_CLASS_MAP defined here:
https://github.com/geotools/geotools/blob/029dc5c8ccc503de3cfd7f4d1c939d8056c260c4/modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDialect.java#L98

So, it seems it's incorrect to include curved geometry types in the list, they would not be recognized anyways. ``CIRCULARSTRING`` and ``CURVEPOLYGON`` should be removed, while ``MULTILINESTRING`` and ``GEOMETRYCOLLECTION`` are indeed missing. I see ``TYPE_TO_CLASS_MAP``  also "measured" variants, but I see no actual use for them (nothing special is done in the code for the "M"), adding them to the table definition list would just cause confusion I believe.

**Comment by Illutax** [comment]
CLA was send.

**Comment by aaime** [comment]
Thanks for the CLA. The PR is blocked on my feedback about entries, see https://github.com/geoserver/geoserver/pull/4552#issuecomment-720408433

**Review by mprins — APPROVED** [review]

**Pull request merged**
