### PR TITLE
Use of sphinx external links to reference geotools user manual.

### PR DESCRIPTION
**Pull request by jodygarnett**
Make use of sphinx external links to reference geotools user manual. Also removed the mbstyle specification (as it is now maintained in the geotools user manual).

## Checklist
For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [x] There is a ticket https://osgeo-org.atlassian.net/browse/GEOT-6641
- [ ] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by aaime** [comment]
The "Documentation" Travis build check failed with:

```
developer:

sphinx:
     [echo] Running sphinx-build -D release=2.18-SNAPSHOT -W -b html -d "/home/travis/build/geoserver/geoserver/doc/en/target/developer/doctrees" . "/home/travis/build/geoserver/geoserver/doc/en/target/developer/html"
     [exec] /usr/local/lib/python2.7/dist-packages/sphinx/util/nodes.py:94: FutureWarning: 
     [exec]    The iterable returned by Node.traverse()
     [exec]    will become an iterator instead of a list in Docutils > 0.16.
     [exec]   for classifier in reversed(node.parent.traverse(nodes.classifier)):
     [exec] /usr/local/lib/python2.7/dist-packages/sphinx/util/nodes.py:94: FutureWarning: 
     [exec]    The iterable returned by Node.traverse()
     [exec]    will become an iterator instead of a list in Docutils > 0.16.
     [exec]   for classifier in reversed(node.parent.traverse(nodes.classifier)):
     [exec] /usr/local/lib/python2.7/dist-packages/sphinx/util/nodes.py:94: FutureWarning: 
     [exec]    The iterable returned by Node.traverse()
     [exec]    will become an iterator instead of a list in Docutils > 0.16.
     [exec]   for classifier in reversed(node.parent.traverse(nodes.classifier)):
     [exec] /home/travis/build/geoserver/geoserver/doc/en/developer/source/programming-guide/wps-services/implementing.rst:14: WARNING: Unknown interpreted text role "geotools".
     [exec] /usr/local/lib/python2.7/dist-packages/sphinx/writers/html.py:462: FutureWarning: 
     [exec]    The iterable returned by Node.traverse()
     [exec]    will become an iterator instead of a list in Docutils > 0.16.
     [exec]   target_node = image_nodes and image_nodes[0] or node.parent
     [exec] /usr/local/lib/python2.7/dist-packages/sphinx/writers/html.py:462: FutureWarning: 
     [exec]    The iterable returned by Node.traverse()
     [exec]    will become an iterator instead of a list in Docutils > 0.16.
     [exec]   target_node = image_nodes and image_nodes[0] or node.parent
```

**Comment by aaime** [comment]
@jodygarnett been a while, are you still interested in getting this PR in?

**Comment by jodygarnett** [comment]
Yeah let me rebase it

**Review by bradh — COMMENTED** [review]
Doesn't this mean that the older GeoServer releases will point to newer GeoTools instructions?

(I guess it already does, but maybe it should point to a specific version?)

**Comment by jodygarnett** [comment]
> Doesn't this mean that the older GeoServer releases will point to newer GeoTools instructions?

Yeah it does, but the geotools project does not publish "historic" versions like docs.geoserver.org does.Indeed docs.geoserver.org may need to stop this practice soon as we need a new home for this content.

**Comment by jodygarnett** [comment]
Un related failure in windows environment.

**Comment by jodygarnett** [comment]
Backported to 2.18.x, linking to stable geotools user guide.

**Pull request merged**
