### PR TITLE
Fix MapML community module NPE when querying images returning no geometry

### PR DESCRIPTION
**Pull request by prushforth**
## Description

I noticed that when I used the MapML client to query example layers like "A sample ArcGrid file" or "North America sample imagery" in the default Preview Layers, that a null pointer exception occurred.  There are no tests for this module (yet).  The checkstyle build profile reports a bunch of failures because _generated_ files (mostly) don't have a license header.  Not sure what to do there (I didn't commit them).  No Jira for this,  I will do that after submitting.  Hopefully have not missed anything. LMK. Attn: @cmhodgson 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] If this is your first contribution, confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) and sent a CLA as necessary (not required for small changes, e.g., fixing typos in documentation)
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by cmhodgson** [comment]
Thanks Peter. Given the small size of the fix and that it is only in our community module I think we can forgo the formality of the JIRA ticket and tests, etc.

**Comment by aaime** [comment]
@cmhodgson it is true that community modules are not subject to tests and QA.
However I don't see a CLA on file from @prushforth . Peter did you send one to OSGeo? If not, the code is tainted and the PR should be reverted ASAP.

**Comment by prushforth** [comment]
I sent an individual CLA on May 5th, to info@osgeo.org.

**Comment by aaime** [comment]
Ok, the last update in the CLA git repo is from April 27th, so yeah, it has not been recorded yet. Will keep it monitored.

**Pull request merged**
