### PR TITLE
[GEOS-6944] Fixed UNKNOWN crs for layer group

### PR DESCRIPTION
**Pull request by tbarsballe**
Fix (and test case) for https://jira.codehaus.org/browse/GEOS-6944

### CODE REVIEW

**Comment by aaime** [comment]
+1 Merging

**Comment by aaime** [comment]
Hey Torben, one question, do you have commit access to GeoServer, in order to perform the backports?

**Comment by tbarsballe** [comment]
No, I only have commit access to GeoTools at the moment, not GeoServer.

**Comment by tbarsballe** [comment]
Now that I do have commit access on GeoServer, did you want me to do the backports for this?
Also, what is the procedure for doing backports against GeoServer (What versions are relevant; just back to stable and maintenance?). Note that I haven't really backported anything before, even on GeoTools.

**Comment by aaime** [comment]
Hi, yep, you should do the backports.
The procedure is like a normal commit, minus the following:
* A non invasive bug fix where you are confident there are no potential side effects, can be backported right away
* In case of doubt or large fix, ask
* A new feature/improvement should not be backported right away, wait a month since commit on trunk, ask for feedback on the devel list about the backport, on positive feedback, do the backport

Stable can receive backports of bug fixes, but also improvements and small new features under positive feedback, maintenance should be limited to bug fixes, but if you really must, ask for feedback anyways and the PSC will decide on a case by case basis (e.g., if the new feature is a mere addition that does not affect any existing functionality it has a good chance, a API breaking one or one that touches many pre-existing code paths very little).

**Pull request merged**
