### PR TITLE
[GEOS-11647] Restore "quiet on not found" configuration for REST in global settings

### PR DESCRIPTION
**Pull request by groldan**
[GEOS-11647](https://osgeo-org.atlassian.net/browse/GEOS-11647) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

In [this commit](e57616971c4c11f6efdd7d12b855b509fbbe9ae1) from 2014, each resource lookup in the REST API would check for the configuration setting, and avoid throwing `RestletException` (which we use `ResourceNotFoundException` for those cases).

For example:

```
boolean quietOnNotFound=quietOnNotFoundEnabled(request)
if(quietOnNotFound){
    return null;
}
throw new RestletException( "No such layer: " + layer, Status.CLIENT_ERROR_NOT_FOUND );
```

Now the checkbox to enable it persists in `org.geoserver.web.RESTSettingsPanel` but it has no effect, and the only way to silence the log flooding is by adding a `?quietOnNotFound=true` parameter to every REST API request.

Make `org.geserver.rest.RestControllerAdvice` account for either the request parameter or the global settings configuration when deciding if it'll log the stack trace or not.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by groldan** [comment]
Hi @aaime, I'm trying but couldn't realize why the log handler wouldn't be called, then I tried running `SecuredFeatureSourceTest` and noticed it's not being called in there either, it's just that the test only checks no events have been captured:

image

I'll dig into it a little bit more

**Comment by groldan** [comment]
yeah it's because the logger is a `Log4j2Logger`

**Comment by aaime** [comment]
If I recall properly, @jodygarnett did develop support for logging tests when switching to log4j2... @jodygarnett do you remember where that support is?

**Comment by groldan** [comment]
@aaime managed to create a strategy object to handle logs capturing, check out 604f77a91e76f610fda52d28131068e1ab4df16c

**Comment by jodygarnett** [comment]
Here you go: https://github.com/geoserver/geoserver/blob/main/src/main/src/test/java/org/geoserver/logging/TestAppender.java

**Pull request merged**
