### PR TITLE
Update automation.rst

### PR DESCRIPTION
**Pull request by daRasmussen**
Typo

### CODE REVIEW

**Comment by bradh** [comment]
I think "sports" could be valid here (http://www.dictionary.com/browse/sport defn. 26), but supports definitely reads better.

**Comment by aaime** [comment]
Yes, was not a typo, written as intended. But if we go with the notion that using it is unclear, there is a couple other places where the term is used:

````
>  git grep sports
en/developer/source/programming-guide/wps-services/design-guide.rst:The GoeServer code base sports by default two implementation of a ``ProcessFilter``:
fr/user/source/styling/sld-extensions/index.rst:GeoServer sports a number of vendor specific extensions to SLD 1.0.
````

(cleaned up the output to report only the actual "sports" matches)

**Comment by bradh** [comment]
I will address those (plus that GoeServer thing too, and the other four places it occurs).

**Comment by bradh** [comment]
The follow-up PR is at https://github.com/geoserver/geoserver/pull/2869

**Pull request merged**
