### PR TITLE
Donating YSLD reference from Boundless Suite

### PR DESCRIPTION
**Pull request by bmmpxf**

### CODE REVIEW

**Comment by bmmpxf** [comment]
@jodygarnett This is the first draft. We may wish to adjust this further.

**Comment by jodygarnett** [comment]
Would like a review from @jdeolive :)

**Comment by jodygarnett** [comment]
Thanks @bmmpxf - I noticed a couple pictures we will need to update (wrong geoserver logo used). Other than that these are excellent docs thanks you.

**Comment by jdeolive** [comment]
These docs are awesome, great work Mike. Big +1 from me.

**Pull request closed without merging**
