### PR TITLE
GeoFence GUI adding and editing Layergroup bug fix

### PR DESCRIPTION
**Pull request by esmailzadeh**
https://github.com/geoserver/geofence/issues/53

### CODE REVIEW

**Comment by jodygarnett** [comment]
This is against a community module by the looks of things. Not sure if we need to use Jira for this or not. 

Not sure what to do on this one @NielsCharlier - normally we would not accept this (no test case so it is hard to know if it fixes anything). Since this is a community module it will be up to module maintainer?

**Comment by aaime** [comment]
I had a discussion with Emanuele already, so far it has not been merged cause it lacks a test

**Comment by NielsCharlier** [comment]
Agreed

**Comment by aaime** [comment]
Closing, the geofence ticket in question was fixed some days ago in a different way.

**Pull request closed without merging**
