### PR TITLE
[GEOS-11103] Upgrade Hazelcast dependency to 5.3.1

### PR DESCRIPTION
**Pull request by fernandor777**
[GEOS-11103](https://osgeo-org.atlassian.net/browse/GEOS-11103) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

[
[GEOS-11103](https://osgeo-org.atlassian.net/browse/GEOS-11103)
](https://osgeo-org.atlassian.net/browse/GEOS-11103)

Hazelcast current version is old (two major versions back) and have some known vulnerabilities.  The plan for this issue is to upgrade it to 5.3.1 including the source code upgrade for the WPS hazelcast extension.
# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [x] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by sikeoka** [comment]
@NielsCharlier may be interested in this PR since this upgrade would require quite a few changes to get the hz-cluster community module to even compile.

There is a geowebcache distributed community module but I don't know how this upgrade would affect that module or if anyone is using it.

**Comment by fernandor777** [comment]
Indeed @sikeoka I saw the build errors and added migration fixes for hz-cluster community module.  I'll give a look for the GeoWebCache module and create a PR.  Thanks!

**Comment by fernandor777** [comment]
Added an upgrade fix for GeoWebCache distributed module since it's causing a build error on this PR:
https://github.com/GeoWebCache/geowebcache/pull/1155

**Comment by fernandor777** [comment]
I added the GeoWebCache counterpart PR:
https://github.com/GeoWebCache/geowebcache/pull/1155

**Comment by aaime** [comment]
@fernandor777 legit QA failures here:

```
2023-08-22T16:46:49.8210551Z 16:46:49,820 [WARNING] /home/runner/work/geoserver/geoserver/src/extension/wps/wps-cluster-hazelcast/src/main/java/org/geoserver/wps/hz/HazelcastStatusStore.java:[131,42] unchecked method invocation: method executeOnEntries in interface com.hazelcast.map.IMap is applied to given types
2023-08-22T16:46:49.8211515Z   required: com.hazelcast.map.EntryProcessor<K,V,R>,com.hazelcast.query.Predicate<K,V>
2023-08-22T16:46:49.8212316Z   found: org.geoserver.wps.hz.HazelcastStatusStore.RemovingEntryProcessor,com.hazelcast.query.Predicate
2023-08-22T16:46:49.8213797Z 16:46:49,820 [WARNING] /home/runner/work/geoserver/geoserver/src/extension/wps/wps-cluster-hazelcast/src/main/java/org/geoserver/wps/hz/HazelcastStatusStore.java:[131,83] unchecked conversion
2023-08-22T16:46:49.8214713Z   required: com.hazelcast.query.Predicate<K,V>
2023-08-22T16:46:49.8215114Z   found:    com.hazelcast.query.Predicate
2023-08-22T16:46:49.8215970Z 16:46:49,820 [WARNING] /home/runner/work/geoserver/geoserver/src/extension/wps/wps-cluster-hazelcast/src/main/java/org/geoserver/wps/hz/HazelcastStatusStore.java:[131,42] unchecked conversion
2023-08-22T16:46:49.8216594Z   required: java.util.Map<java.lang.String,java.lang.Object>
2023-08-22T16:46:49.8217005Z   found:    java.util.Map
```

**Comment by fernandor777** [comment]
Thanks @aaime fixed.

**Review by aaime — APPROVED** [review]

**Comment by aaime** [comment]
Thanks, merged!

**Pull request merged**
