### PR TITLE
Update win-installer.rst

### PR DESCRIPTION
**Pull request by ragnvald**
The src folder is not in the bin distribution. Changed to src distribution. Also mentions that the user will have to download the src distribution.

<Include a few sentences describing the overall goals for this Pull Request. Please do not remove the checklist below, pull requests missing it will be ignored.>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Review by bradh — APPROVED** [review]
Seems reasonable.

**Comment by ragnvald** [comment]
> Seems reasonable.

It is, but it needs some further changes. The text should reflect that the user will need to download both src and bin to do this process.

**Review by bradh — COMMENTED** [review]
Perhaps it should reflect that either git or a checkout can be used. 

This is the Developer docs, so "users"  of these instructions might vary quite a lot.

**Comment by ragnvald** [comment]
Just did an update on Windows. One of the challenges I met were to upgrade the https support. Not sure if this kind of detail will fit in this document. Perhaps a separate page on supporting https could be called for? Also - would it be an idea to add the missing jetty-viles in the right version with the distribution?

New versions of geoserver might come with new versions of Jetty. It is therefore necessary to download the correct jetty distribution from https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/

Then copy:

- add ssl.mod from /modules to %GEOSERVER_HOME%\modules
- copy (replace because inconsistent with context) jetty-ssl.xml from /etc to %GEOSERVER_HOME%\etc
- copy (add) jetty-ssl-context.xml from /etc to %GEOSERVER_HOME%\etc

In addition _keystore_  must be copied from the earlier installation.

**Comment by aaime** [comment]
Hmm... is it a good idea to use the same keystore in all installations? Believe a new key should be generated for each install.

**Comment by ragnvald** [comment]
My colleague @kjetpett did [a blog posting on https and geoserver 2.12.1](http://kjetilpettersson.blogspot.com/2018/06/geoserver-2121jetty-installing-ssl.html). Some of the ideas above are from this posting. Perhaps we could use this as a starting point for docs on https?

**Comment by aaime** [comment]
@ragnvald yep sure, it would help those that want to run GeoServer within Jetty.

**Comment by aaime** [comment]
Sooo... is this one good to merge? I'm not clear if further work will land here, or in another PR.

**Comment by aaime** [comment]
Cough cough! :-D

**Comment by ragnvald** [comment]
> Cough cough! :-D

Terribly sorry @aaime - I am a bit of a noob here and can not find the "magic button" in the web user interface to do the merge. Suggestions?

**Comment by aaime** [comment]
I was not expectnig you to, you don't have developer status, so the magic button is not available for you.
I was referring to my previous comment: "Sooo... is this one good to merge? I'm not clear if further work will land here, or in another PR."

I guess it is good for merge, yes?

**Comment by aaime** [comment]
Assuming it is and merging...

**Pull request merged**
