### PR TITLE
[GEOS-11263] hideEmptyRules not working in JSON LegendGraphic

### PR DESCRIPTION
**Pull request by iaunzu**
[GEOS-11263](https://osgeo-org.atlassian.net/browse/GEOS-11263) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

Hi

This a a PR for [GEOS-11263](https://osgeo-org.atlassian.net/browse/GEOS-11263)

It applies the same strategy in ``BufferedImageLegendGraphicBuilder`` but in JSONLegendGraphicBuilder to filter out all rules with no features in the BBOX.
  
# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [X] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [X] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [X] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [X] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [X] Bug fixes and small new features are presented as a single commit.
- [X] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
Tests are failing:

```
2024-01-22T14:45:10.4781526Z 14:45:10,477 [INFO] Results:
2024-01-22T14:45:10.4782381Z 14:45:10,477 [INFO] 
2024-01-22T14:45:10.4783130Z 14:45:10,477 [ERROR] Errors: 
2024-01-22T14:45:10.4789750Z 14:45:10,477 [ERROR]   JSONLegendGraphicOutputFormatTest.testLanguageRaster:1757->checkLanguageRule:1795 » JSON
2024-01-22T14:45:10.4791786Z 14:45:10,478 [ERROR]   JSONLegendGraphicOutputFormatTest.testLanguageVector:1747->checkLanguageRule:1795 » JSON
```

**Comment by iaunzu** [comment]
Ok, I pushed a commit attempting to pass those tests. It turns out that hideEmptyRules serves two purposes. One is to filter out those rules with a <ogc:Filter>. The other is to exclude rules not painted on the map and it is heavily dependent on the BBOX. This change targets the latter, performing the process only when a BBOX is specified, assuming that all rules will be painted if no BBOX is present in the request. This should probably be changed for image legends as well.

Also, rules with RasterSymbolizers would always be filtered out and now they are skipped from the process.

**Review by aaime — CHANGES_REQUESTED** [review]
Overall looks good, see comment about making the test more readable.

**Comment by aaime** [comment]
Looks good thanks, merging and scheduling for backport.

**Pull request merged**
