### PR TITLE
[GEOS-9209] Enhance StyleInfo with MetadataMap on Catalog object and Rest entpoint.

### PR DESCRIPTION
**Pull request by fernandor777**
This PR enhances StyleInfo and StyleInfoImpl Catalog objects adding a MetadataMap attribute for being serialized by Xstream.
Also adds Rest integration tests on Restconfig module.

https://osgeo-org.atlassian.net/browse/GEOS-9209

### CODE REVIEW

**Comment by simboss** [comment]
Travis build failing. Please, double check.

**Comment by fernandor777** [comment]
Looks like a GWC module test fails on Java 8 (java 11 tests says ok).
```
testAutomaticTruncationDefaultStyleContentsChange(org.geoserver.gwc.GWCIntegrationTest)  Time elapsed: 1010 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: equalToIgnoringCase("MISS")
     but: was HIT
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:956)
    at org.junit.Assert.assertThat(Assert.java:923)
    at org.geoserver.gwc.GWCIntegrationTest.testAutomaticTruncationDefaultStyleContentsChange(GWCIntegrationTest.java:717)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
```

Double checking on linux 64 bits / OpenJDK 8 build + tests (local environment):
```
mvn clean install -T1C -Prelease -nsu
```
Result: all tests are ok.  including GWC:
```
[INFO] gs-rest ............................................ SUCCESS [ 15.386 s]
[INFO] GeoWebCache (GWC) Module ........................... SUCCESS [02:52 min]
[INFO] gs-restconfig ...................................... SUCCESS [03:15 min]
[INFO] gs-restconfig-wcs .................................. SUCCESS [ 27.969 s]
[INFO] gs-restconfig-wfs .................................. SUCCESS [ 31.359 s]
[INFO] gs-restconfig-wms .................................. SUCCESS [ 23.432 s]
```

Proceeding to check failing test method code and investigate the cause.

**Comment by simboss** [comment]
I double checked and the failure seems unrelated.

**Comment by aaime** [comment]
Yes, the test is known to randomly fail, especially on appveyor. 
https://github.com/geoserver/geoserver/pull/3491 attempts to fix it.

The PR looks good to me, merging.

**Comment by fernandor777** [comment]
Yes, now adding gs-main tests.

**Comment by fernandor777** [comment]
Added tests for StyleInfo catalog loading/saving/updating on gs-main module.

**Comment by mbarto** [comment]
Looks good to me

**Comment by simboss** [comment]
@aaime did you approve this or not? From comments it seems so but not from the report up above.

Aside, please, discuss backport to 2.15.x for GeoNode compatibility.

**Comment by aaime** [comment]
@mbarto looked at it before I did, so I did not add another review.... adding it now...

**Comment by simboss** [comment]
Thanks @aaime. Can you or @mbarto merge at your convenience?

@fernandor777 please, backport to 2.15.x branch

**Comment by fernandor777** [comment]
2.15.x Backport:
https://github.com/geoserver/geoserver/pull/3493

**Pull request merged**
