### PR TITLE
[GEOS-7396]: ClassCastException fix

### PR DESCRIPTION
**Pull request by dromagnoli**
You need to merge https://github.com/geotools/geotools/pull/1119 before merging this PR.

### CODE REVIEW

**Comment by jodygarnett** [comment]
@dromagnoli got some test failures - possibly as a result of this change?

````
Failed tests:   testTimeKVPNow(org.geoserver.wcs.GetCoverageTest): expected:<18.2849999185419> but was:<18.26599991763942>
  testTimeSecond(org.geoserver.wcs.GetCoverageTest): expected:<18.2849999185419> but was:<18.26599991763942>
  testElevationFirst(org.geoserver.wcs.GetCoverageTest): expected:<18.2849999185419> but was:<18.26599991763942>

Tests in error: 
  testElevationSecond(org.geoserver.wcs.GetCoverageTest): Could not load sample.tif from scope class org.geoserver.wcs.GetCoverageTest.
  testCategoriesToArray(org.geoserver.wcs.GetCoverageTest)
````

**Comment by jodygarnett** [comment]
Confirmed this commit was responsible for the above failures, reverted commit from master and reopening this pull request.

**Comment by dromagnoli** [comment]
I'm checking it.

**Comment by dromagnoli** [comment]
Updated pull request available here:
https://github.com/geoserver/geoserver/pull/1504

**Pull request merged**
