### PR TITLE
[GEOS-8556] Add option to copy global attributes from NetCDF/GRIB source files (2.12.x)

### PR DESCRIPTION
**Pull request by bencaradocdavies**
https://osgeo-org.atlassian.net/browse/GEOS-8556

Backport to 2.12.x of: https://github.com/geoserver/geoserver/pull/2742

### CODE REVIEW

**Comment by aaime** [comment]
A month passed, so the backport is fine, but ... isn't it a bit strange to have it in 2.12.x and not in 2.13.x?
However 2.13.x is frozen so... will you remember to port there once 2.13.0 is out?

**Comment by aaime** [comment]
Actually, scratch that, it's probably already in 2.13.x :)

**Comment by bencaradocdavies** [comment]
@aaime yum, already in 2.13.x as it was merged on master before the new branch was made. In fact, before the decision to branch on beta.  :-)

An interesting question is whether 2.12.x counts as stable or maintenance in the window between 2.13-beta and 2.13.0. What rules apply?

**Comment by aaime** [comment]
Unsure, we're in a gray area :)
Personally I'm not too concerned, this patch worked fine when I tried it out and we are talking about a smaller change on an extension module, not a large change in core. But it's just me :-)

**Pull request merged**
