### PR TITLE
[GEOS-9927] Add StyleComponentInfo in AbstractStylePage

### PR DESCRIPTION
**Pull request by weskamm**
This adds a new entry point for extensions to be instantiated in the AbstractStylePage and thus get access to the style edit pages. For more information, see https://osgeo-org.atlassian.net/browse/GEOS-9927

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [x] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by aaime** [comment]
@weskamm if you want to run the QA locally, the [QA guide](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) shows you how to do that. Running them on the whole source code takes a lot of time, but if you cd into the one module modified, then it's pretty quick (just one module being checked) and gives you a better turnaround between changes and checks.

**Comment by weskamm** [comment]
Thanks for the hint, i think i finally figured out the issues

**Comment by aaime** [comment]
The change looks legit, but there is no test. We don't normally merge PRs without one.

Thinking out loud, at test could be done that uses a test component and verifies it plugged in correctly. During tests it's possible to inject a testing bit of Spring app context, overriding a method like in this example (taken from a WCS test):

```
    protected void setUpSpring(List<String> springContextLocations) {
        super.setUpSpring(springContextLocations);
        springContextLocations.add("classpath:/org/geoserver/wcs/ResourceAccessManagerContext.xml");
    }
```

You can find a full example of an extensible page being tested here:
https://github.com/geoserver/geoserver/blob/7afff47045ed55f4d17a838245bc091ddcffeff0/src/web/core/src/test/java/org/geoserver/web/GeoServerHomePageTest.java

**Comment by weskamm** [comment]
I tried hard adding a test, but i did not find an easy way to mockup a bean for testing without changing lots of code. I will have a look at your recommendation

**Comment by weskamm** [comment]
Thanks for pointing out the direction, i have added a test now :tada:

**Comment by aaime** [comment]
Looking good, thanks! Merging.

**Pull request merged**
