### PR TITLE
Add Tomcat CORS configuration

### PR DESCRIPTION
**Pull request by RussellGrew**
Proposed Tomcat CORS example for documentation. 

Update existing page where appropriate.

I could not find an equivalent to `<param-name>chainPreflight</param-name>` for Tomcat.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by mprins** [comment]
@RussellGrew The Tomcat filter is documented here: https://tomcat.apache.org/tomcat-9.0-doc/config/filter.html#CORS_Filter

**Comment by aaime** [comment]
Agree with @mprins a reference to the full Tomcat documentation for CORS filters would be a useful addition.

**Comment by RussellGrew** [comment]
Thanks.

I will remove the new Tomcat example and instead link to the website? Or do
both?

Cheers.

**Comment by mprins** [comment]
perhaps add tomcat config to the web.xml in a comment block as well, like the jetty config: 

https://github.com/geoserver/geoserver/blob/5bc01673dabef6e764534130562d33ca97e46a39/src/web/app/src/main/webapp/WEB-INF/web.xml#L170-L191

That would make it easier for an end user I think. I would keep the things in the doc as well, it's not prone to changes (eg. tomcat config for v7.x and v9.x is identical)

**Comment by RussellGrew** [comment]
Additional feedback is invited.

Sphinx runs fine.

**Comment by aaime** [comment]
Merged, thanks!

**Pull request merged**
