### PR TITLE
GEOS-10163 Incorrect INSPIRE namespace URI

### PR DESCRIPTION
**Pull request by nielsmeijer**
[GEOS-10163](https://osgeo-org.atlassian.net/browse/GEOS-10163)

Ticket [GEOS-10002](https://osgeo-org.atlassian.net/browse/GEOS-10002) incorrectly changed the inspire namespace URIs to https://. Due this change, inspire validators fail. 

This pull request reverts the namespace url  to the currect URI.

See also https://osgeo-org.atlassian.net/browse/GEOS-10163

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Review by mprins — APPROVED** [review]
LGTM

**Comment by taba90** [comment]
Looks good to me

**Comment by aaime** [comment]
Merged on main. If you want the fix to be in 2.19.x and 2.18.x releases please backport (note, 2.18.5, the final 2.18.x release, is due out in a few days).

**Comment by nielsmeijer** [comment]
Thanks for the merge. I've created #5220 and #5221 for 2.18.x and 2.19.x

**Pull request merged**
