### PR TITLE
[GEOS-11624] Split geopackage extension into three (sub)modules

### PR DESCRIPTION
**Pull request by woutergd**
As I am working on implementing the Geopackage Output extension into the Geoserver Cloud project, I found out that this was not easily possible as it was a single module that imported the GWC, WMS and WFS modules. To make it a better fit, hereby I propose the changes to split this extension into three separate modules: a wms and wfs module, and a core module that support both of them.

# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).
- [X] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
Sure, I don't see a problem here. By looking at ext-geopkg-output.xml it seems the assembly will still catch the right jar files. @jodygarnett what do you think?=

**Comment by jratike80** [comment]
Will the WFS submodule take care of the OGC API Features GeoPackage output if that will be supported in the future?

**Comment by aaime** [comment]
It should... in theory even today, when installing both the OGC API features package and the Geopackage output format, the GeoPackage format should become available in OGC API features. But I haven't tried.

**Comment by jodygarnett** [comment]
It should be fine, a bit of a pain to have more jars; but it is maven ...

**Comment by woutergd** [comment]
Sorry, had not enough time last weeks to continue on this PR. Good to hear that these changes are not expected to be an issue.

I noticed that I have for some strange reason failures on the JDK 17 and 21 builds, is there someone who can point me in the right direction to resolve these build errors? I will try also to fix this week the merge conflicts, so this PR can move forward.

**Comment by aaime** [comment]
You can safely ignore those failures, they are happening sometimes on the Github actions but we cannot reproduce them on developer machines. But please make sure you rebase this PR on top of the latest main branch, as we try to mitigate those failures over time by giving tests more leniency (some are time based, others will retry on lock failures, and so on).

**Comment by woutergd** [comment]
@aaime thanks for the info. I rebased this PR, and also created a JIRA-issue as was suggested to me in Discourse as something that was required to provide a PR.

I noticed however that after the rebase I have different / new tests that are failing. Are these also known? Otherwise I will make some time this week to investigate what the issue is for these build errors.

**Comment by aaime** [comment]
Had a look, everything seems to check out. Merging.

**Pull request merged**
