### PR TITLE
[GEOS-7534] Make GeoServerPropertyOverrideConfigurer use replace method

### PR DESCRIPTION
**Pull request by nmco**
Associated issues: 
- https://osgeo-org.atlassian.net/browse/GEOS-7534
- https://osgeo-org.atlassian.net/browse/GEOS-7204

### CODE REVIEW

**Comment by simboss** [comment]
Did you some manual testing on Windows and Linux? Also with paths with spaces?

**Comment by nmco** [comment]
Yes I manually tested this on Windows and Linux and is working.

**Comment by simboss** [comment]
Cool,
if nobody objects I will merge on Mon.

**Comment by nmco** [comment]
Ok, thank you.

**Comment by bencaradocdavies** [comment]
Good tests @nmco. You might also consider adding some path elements with characters outside US-ASCII, like EntitéGénérique or 通用实体.

**Comment by simboss** [comment]
Good point Ben.

**Comment by nmco** [comment]
Thanks for the feedback @bencaradocdavies,tests updated with paths that contain non ascii chars.

**Comment by simboss** [comment]
merging...

**Comment by simboss** [comment]
thinking, does this needs to be backported to 2.9?

**Comment by simboss** [comment]
answering myself, yes it does.

Waiting for the backport.

**Pull request merged**
