### PR TITLE
Attempt updating to latest Marlin renderer

### PR DESCRIPTION
**Pull request by aaime**
Objectives: use latest, make it work with Java 17 and 21 out of the box.
Status: tested on Linux with java 11, 17 and 21, I can render maps, the renderer name does not show up in 17 and 21 (probably due to reflection being limited?). Untested on windows. Untested in deploys with spaces and other oddball chars in paths.

Shared branch, help welcomed.

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by groldan** [comment]
OS: ubuntu 24.04

---

For me the renderer shows up with
```
export JAVA_TOOL_OPTIONS="--add-opens=java.desktop/sun.java2d.pipe=ALL-UNNAMED"
```

I'm not sure if all JVMs will pick up `JAVA_TOOL_OPTIONS`, but in any case the `--add-opens` can be added to the script

In all cases I tried with and without the `marlin-0.9.4.8.jar` file in `webapps/geoserver/WEB-INF/lib`

---

```
sdk use java 11.0.23-tem 
java -version
Picked up JAVA_TOOL_OPTIONS: --add-opens=java.desktop/sun.java2d.pipe=ALL-UNNAMED
openjdk version "11.0.23" 2024-04-16
OpenJDK Runtime Environment Temurin-11.0.23+9 (build 11.0.23+9)
OpenJDK 64-Bit Server VM Temurin-11.0.23+9 (build 11.0.23+9, mixed mode)
```
image

---

```
sdk use java 21.0.3-tem
java -version
Picked up JAVA_TOOL_OPTIONS: --add-opens=java.desktop/sun.java2d.pipe=ALL-UNNAMED
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
```
image

---

```
sdk use java 21.0.3-graal
java -version
Picked up JAVA_TOOL_OPTIONS: --add-opens=java.desktop/sun.java2d.pipe=ALL-UNNAMED
java version "21.0.3" 2024-04-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37, mixed mode, sharing)
```
image

---

```
sdk use java 21.0.3-sem 
java -version
openjdk version "21.0.3" 2024-04-16 LTS
IBM Semeru Runtime Open Edition 21.0.3.0 (build 21.0.3+9-LTS)
Eclipse OpenJ9 VM 21.0.3.0 (build openj9-0.44.0, JRE 21 Linux amd64-64-Bit Compressed References 20240416_177 (JIT enabled, AOT enabled)
OpenJ9   - b0699311c7
OMR      - 254af5a04
JCL      - ac8f341bc20 based on jdk-21.0.3+9)
```
image

**Comment by jodygarnett** [comment]
If that is going to be required maybe we should provide a `serenv.sh` / `setenv.bat` for tomcat installation instructions also?

**Comment by aaime** [comment]
@jodygarnett good idea. I started this work on a shared branch in the geoserver repo so that others can also pitch in with more changes.

**Comment by mprins** [comment]
most of those are already listed in https://github.com/geoserver/geoserver/blob/03eb0a2cc1566ca95f13f573e085e4c4bc9960f0/doc/en/user/source/production/java.rst?plain=1#L37-L42

**Comment by aaime** [comment]
Review feedback applied. I've asked for more tests/comments on the devel list.

**Comment by petersmythe** [comment]
Win 11 & Java 17 works:

image

**Comment by petersmythe** [comment]
Win 11 & Java 21 works:

image

(also MINGW64 = Git Bash works)

**Review by petersmythe — APPROVED** [review]

**Comment by aaime** [comment]
Nice, thanks @petersmythe

**Comment by aaime** [comment]
Merged on main (without squashing, more than one author, went for a merge commit). Should we backport?

**Comment by jodygarnett** [comment]
Back port as this will allow more people to run trouble free.

- -
Jody Garnett

**Comment by jodygarnett** [comment]
Nice work @aaime and thanks for testing @petersmythe :D

**Pull request merged**
