### PR TITLE
[GEOS-10568] Fix module modularity for GWC

### PR DESCRIPTION
**Pull request by ahmedababnehgeo**
[GEOS-10568](https://osgeo-org.atlassian.net/browse/GEOS-10568)

We separated the REST APIs into another module. The new module name is `gs-gwc-rest`.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [x] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by ahmedababnehgeo** [comment]
@taba90 Ready for review

**Review by taba90 — CHANGES_REQUESTED** [review]
Looks to me that there are some things that are missing:
- the REST module has been separated by the core part but no container module for gwc-core and gwc rest was added.
- this class https://github.com/geoserver/geoserver/blob/fe4a8909d51df12f13dc0f3c7e368780add2a6e2/src/gwc/src/main/java/org/geoserver/gwc/layer/GWCGeoServerRESTConfigurationProvider.java should probably go in the new rest module as well as it is meant for serialization and deserialization of TileLayer instances.
- the dependency of gwc-rest should go also in the root pom.xml of GeoServer
- there are some community/extensions modules extending the gwc functionality, once the refactoring happened also for the gwc core the gs-gwc depedency in those modules should be updated as well in their pom.xml

@aaime any other feedback from you, or correction to what I wrote?

**Comment by ahmedababnehgeo** [comment]
No association was found between the `gwc-rest` and any of the community modules. We agreed to create the `gwc-rest` module on the same level of `gwc`. The rest of the comments have been addressed.

**Comment by taba90** [comment]
@aaime builds are now green and your feedback has been applied. I've tested this locally and seems to work fine.

**Review by taba90 — APPROVED** [review]

**Comment by aaime** [comment]
Merged, thanks!

**Pull request merged**
