### PR TITLE
[GEOS-11532] Update to JTS 1.20.0

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOS-11532](https://osgeo-org.atlassian.net/browse/GEOS-11532) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

See release notes https://github.com/GeoWebCache/geowebcache/pull/1317

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by mprins** [comment]
```
2024-09-07T16:26:14.4753520Z 16:26:14,475 [INFO] Running org.geoserver.wps.gs.SimplifyProcessTest
2024-09-07T16:26:15.2181918Z 16:26:15,217 [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.739 s <<< FAILURE! - in org.geoserver.wps.gs.SimplifyProcessTest
2024-09-07T16:26:15.2188001Z 16:26:15,218 [ERROR] testSimplify(org.geoserver.wps.gs.SimplifyProcessTest)  Time elapsed: 0.711 s  <<< FAILURE!
2024-09-07T16:26:15.2189660Z java.lang.AssertionError: expected:<5> but was:<4>
2024-09-07T16:26:15.2191045Z 	at org.geoserver.wps.gs.SimplifyProcessTest.testSimplify(SimplifyProcessTest.java:73)
```

could be a legit failure or just new algorithm output: https://github.com/geoserver/geoserver/blob/a5d10720f3f5913923542dcf8d2569e921a2a88d/src/extension/wps/wps-core/src/test/java/org/geoserver/wps/gs/SimplifyProcessTest.java#L72-L73

**Comment by jodygarnett** [comment]
based on the comment saying 4 sides is expected, and the test expecting 5 sides ... perhaps it is now returning the right answer (that matches the comment)

**Comment by mprins** [comment]
I think a 4 sided polygon will have (a shell with) 5 coordinates, one extra to close the ring, strictly the test does not test the number of sides.

Wondering why the test does not use Polygon#getNumPoints() instead

**Comment by jodygarnett** [comment]
Well changing the test fixes the build but is not informative; going to run locally.

**Comment by jodygarnett** [comment]
Changed to getNumPoints(), and yes 3 sides were expected due to https://github.com/locationtech/jts/pull/925

**Comment by aaime** [comment]
So the relateNG has not been enabled, right? I don't see changes to GeoServerInitStartupListener... for a parallel, that's [where we enable intersect ng](https://github.com/geoserver/geoserver/blob/0151b51af30f5f9a1a16d79a745592981e5ddce6/src/main/src/main/java/org/geoserver/GeoserverInitStartupListener.java#L81).

**Pull request merged**
