### PR TITLE
[GEOS-9255]: promote authkey community module to extension

### PR DESCRIPTION
**Pull request by mbarto**
## Description

Promoting the authkey module to extension.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)

The following are required only for core and extension modules, while they are welcomed, but not required, for community modules:
- [x] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] New unit tests have been added covering the changes
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by aaime** [comment]
Hi @mbarto checked and the changes look good, I've just noticed a small difference in the contents of the packaged zip files:

Selezione_808

As you can see, there is an extra json-20080701.jar file in the ZIP file generated by the PR. Probably not harmful, but wondering, did you double check running the result on a GeoServer (e.g., pick a nightly build, add the zip contents to it, see if everything still works as it is supposed to?)

**Comment by mbarto** [comment]
Thanks, I will double check the additional jar

**Comment by mbarto** [comment]
@aaime I made the ext-authkey.xml list more picky, to exclude that additional jar

**Comment by aaime** [comment]
Good to go then, at least IMHO :-)

**Pull request merged**
