### PR TITLE
GEOS-7020: additional fix to avoid overflows of hitArea outside of pa…

### PR DESCRIPTION
**Pull request by mbarto**
…inted area

### CODE REVIEW

**Comment by aaime** [comment]
Ouch, this one did not make into the release??

**Comment by mbarto** [comment]
nope

**Comment by aaime** [comment]
How easy is it to trigger this failure? Do we have a 2.7.1 with GetFeatureInfo not working in common cases?

**Comment by mbarto** [comment]
From what I have seen it can happen quite easily

**Pull request merged**
