### PR TITLE
[GEOS-10606] Generate html files for war and doc release assemblies

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOS-10606](https://osgeo-org.atlassian.net/browse/GEOS-10606)

Checking the 2.22-RC war and doc bundles the expected README.html file was not included.

With this change:
```
unzip -l target/release/geoserver-2.23-SNAPSHOT-war.zip | grep html
    18057  11-18-2022 09:39   README.html
    44465  11-18-2022 09:39   license/LGPL.html
    19579  11-18-2022 09:39   license/OGC.html
    27979  11-18-2022 09:39   license/apache-2.0.html
    18930  11-18-2022 09:39   license/HSQL.html
    19918  11-18-2022 09:39   license/GEOTOOLS_NOTICE.html
    24974  11-18-2022 09:39   license/EPSG.html
    47299  11-18-2022 09:39   license/NOTICE.html
    28769  11-18-2022 09:39   license/epl-1.0.html
    20158  11-18-2022 09:39   license/W3C.html
    19654  11-18-2022 09:39   license/apache-1.1.html
```

And javadoc:
```
unzip -l target/release/geoserver-2.23-SNAPSHOT-javadoc.zip | grep "license\|README"
        0  11-18-2022 22:11   license/
    18057  11-18-2022 09:39   README.html
    35647  11-18-2022 09:39   license/GPL.html
    47299  11-18-2022 09:39   license/NOTICE.html
```

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [x] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by jodygarnett** [comment]
Verify:
```
unzip -l target/geoserver-2.23-SNAPSHOT-api.zip | grep html
    20215  11-18-2022 21:16   geoserver-2.23-SNAPSHOT-api/index.html
    35116  11-18-2022 21:16   geoserver-2.23-SNAPSHOT-api/LICENSE.html
    18697  11-18-2022 21:16   geoserver-2.23-SNAPSHOT-api/README.html
    51617  11-18-2022 21:16   geoserver-2.23-SNAPSHOT-api/importerTasks/index.html
```

**Comment by jodygarnett** [comment]
verified geoserver-2.23-SNAPSHOT-developer.zip:
```
unzip -l target/geoserver-2.23-SNAPSHOT-developer.zip | grep html
    35116  11-18-2022 21:44   geoserver-2.23-SNAPSHOT-developer/LICENSE.html
    18697  11-18-2022 21:44   geoserver-2.23-SNAPSHOT-developer/README.html
    13951  11-18-2022 21:16   geoserver-2.23-SNAPSHOT-developer/release-testing-checklist/index.html
    ``

**Comment by jodygarnett** [comment]
The other files are fine; adjusted the README.html so the instructions work for all documentation bundles.

**Comment by jodygarnett** [comment]
@bradh since I updated some of the README txt I would like to ask for your proof reading :)

**Review by bradh — APPROVED** [review]
Applied a couple of minor fixes.

**Comment by jodygarnett** [comment]
Thanks @bradh rebased to get this into two clear commits for readability when back porting.

**Pull request merged**
