### PR TITLE
[GEOS-7826] Add check for no layers when instantiating Style Editor page

### PR DESCRIPTION
**Pull request by tbarsballe**
Fix for https://osgeo-org.atlassian.net/browse/GEOS-7826

Added null check to the page constructor.
Added error messages when trying to navigate to other tabs when no layers are available.

### CODE REVIEW

**Comment by jodygarnett** [comment]
Nice corner case, happens every time we startup without a data directory.

**Comment by aaime** [comment]
Hmm... the Travis build keeps on failing early in the build, but only on Travis (and only for this pull request... that's a bit crazy).

**Comment by tbarsballe** [comment]
That is odd, this should not be able to affect gs-main.
Re-kicked the build and looks like it is working again. I will go ahead and merge (+ backport to 2.10)

**Comment by tbarsballe** [comment]
Cherry-picked to 2.10.x

**Pull request merged**
