### PR TITLE
[i18n] Korean properties files synched from Transifex

### PR DESCRIPTION
**Pull request by fgdrf**
Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>

### CODE REVIEW

**Comment by fgdrf** [comment]
@mapplus This is the pull request represents the synchronized Resources from Trasifex project https://www.transifex.com/GeoServer/geoserver/language/ko/

I used [this](https://gist.github.com/fgdrf/6507286) Transifex configuration and executed ant-script [gs-transifex.xml](https://gist.github.com/fgdrf/6507435) (copied into [build](https://github.com/geoserver/geoserver/tree/master/build) directory with following command from root checkout folder :

`ant -f build/gs-transifex.xml -Dtx.language=ko`

**Comment by fgdrf** [comment]
Wondering why gs-wms fails on Travis, restarted the build ..

**Comment by bencaradocdavies** [comment]
@fgdrf [a commit on GeoTools master](https://github.com/geotools/geotools/commit/261fc592eda8419746eb8bade0453cc9a196837e) [broke GeoServer gs-wms](http://osgeo-org.1560.x6.nabble.com/Build-failed-in-Jenkins-geoserver-master-4047-td5311031.html). I have [reverted the problematic commit on GeoTools master](https://github.com/geotools/geotools/commit/a2da30e81c033baeed30574e1dbee82d0c67d735). Once the GeoTools build has completed, I will kick your Travis CI build again.

**Comment by bencaradocdavies** [comment]
@fgdrf I have restarted the Travis CI build.

**Comment by fgdrf** [comment]
@bencaradocdavies Thanks, looks good to me. What is the merge-strategy Ih should choose (rebase & merge, merge, or squash)?

**Comment by bencaradocdavies** [comment]
@fgdrf I favour merge for pull requests with a sufficiently clean history because it preserves history and authorship. I will sometimes squash at the command-line if the commits are a bit messy or require a few fixes; I then manually set the author to ensure that credit/blame is fairly assigned. Either way, it is all a matter of taste.

Your merge looks fine to me. Thanks!

**Pull request merged**
