### PR TITLE
[GEOS-8820][2.14.x Community Module] - GeoServer Keycloak Security Plugin

### PR DESCRIPTION
**Pull request by afabiani**

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
Please add a Jira issue so this improvement will appear in the release notes, and link the issue in the PR description.

**Comment by tbarsballe** [comment]
This could also benefit from a release descriptor file like those in https://github.com/geoserver/geoserver/tree/master/src/community/release

**Comment by afabiani** [comment]
https://osgeo-org.atlassian.net/browse/GEOS-8820

**Comment by bencaradocdavies** [comment]
That build failure was fixed on master three days ago in https://github.com/geoserver/geoserver/pull/2962 [GEOS-8818](https://osgeo-org.atlassian.net/browse/GEOS-8818). Once conflicts are fixed, try a close-reopen.

**Comment by afabiani** [comment]
@aaime changes committed as requested

**Comment by aaime** [comment]
And in it goes!

**Pull request merged**
