### PR TITLE
GEOS-6906 Fix bad calculation of source Coverage Transform

### PR DESCRIPTION
**Pull request by ahuarte47**
This pull request fixes the issue: https://jira.codehaus.org/browse/GEOS-6906

### CODE REVIEW

**Comment by aaime** [comment]
Look good, waiting for a test.

**Comment by ahuarte47** [comment]
Hi Andrea, thanks. I am trying implement a test using your WPS "ras:ScaleCoverage", I am confused, this module ignores the input translation parameters.

https://github.com/geotools/geotools/blob/master/modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/ScaleCoverage.java#L59

This is an error ?

**Comment by ahuarte47** [comment]
Opps, the Affine process has other error. It looses the "translateY" parameter,

https://github.com/geotools/geotools/blob/master/modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/AffineProcess.java#L68

**Comment by ahuarte47** [comment]
Hi Andrea, I provide a test as you advice me, all in one single commint.

Best Regards
Alvaro

**Comment by aaime** [comment]
Hi Alvaro, can you explain what the test does, and why it would have failed before the fix?

**Comment by ahuarte47** [comment]
Hi Andrea, It checks if the ClassName of the output Coverage contains 'Resampler2D' string.

DefaultWebCoverageService111::estimateOffsets() looses the translation parameters of the source Coverage transform and finally the source and target GridGeometry's are different even when the real GridGeometry's are equals.

It does that DefaultWebCoverageService111::getCoverage() resample the output Coverage.

**Comment by aaime** [comment]
Merged :-)
Would like to backport, but we are too close to 2.7.0... could you remind me once 2.7.0 is out?

**Comment by ahuarte47** [comment]
Thanks Andrea!

**Comment by bencaradocdavies** [comment]
Commit 21a6888afc6d55aeda88edd491601a88606a5e8e breaks the GeoServer build in gs-wps-core and has been reverted. Alvaro, please see:
https://jira.codehaus.org/browse/GEOS-6906

**Pull request merged**
