### PR TITLE
Metadata extension: remove stacktrace and before work-around

### PR DESCRIPTION
**Pull request by NielsCharlier**
# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
Hi @NielsCharlier , thanks for working on these fixes.

Looking at the logs, there is still a lot of errors being logged:
https://pipelinesghubeus22.actions.githubusercontent.com/dQNz5n7hOjGz08uFx9RQGlSCRCVqRRu9gT2eAdi6O60NWWaRvE/_apis/pipelines/1/runs/38390/signedlogcontent/3?urlExpires=2023-12-05T09%3A47%3A31.8717425Z&urlSigningMethod=HMACV1&urlSignature=okWgoA9a1CHkdCNyQ80vX1VEtkAtUyPPRV2F0rr12mE%3D

I believe the current action, to remove the one file I did mention from the tests, is not fixing the issue.
As I see it, the problem is that the loading code logs at SEVERE level 3 subsequent attempts at loading configuration files in a blind way, without having a way to know in advance what they might contain.
I would simply move those logs down to "FINE" level, and eventually log something at severe if after the various attempts, the file could not be loaded in any way (unless even that is a possible and reasonable occurrence, if that's the case, just leave the existing logging but at FINE level instead).

**Comment by NielsCharlier** [comment]
@aaime Yes you are right, the entire module overuses SEVERE. I have changed the logging that I think you mean to 'FINE' and I also changed all other ones to 'WARNING'.

**Comment by aaime** [comment]
Yep, much better compared to before, thanks!

**Comment by aaime** [comment]
The backport to `2.23.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 7af1cbd12b... Metadata extensions: remove stacktrace and before work-around
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
CONFLICT (modify/delete): src/extension/metadata/src/test/java/org/geoserver/metadata/EmptyConfigurationTest.java deleted in HEAD and modified in 7af1cbd12b (Metadata extensions: remove stacktrace and before work-around).  Version 7af1cbd12b (Metadata extensions: remove stacktrace and before work-around) of src/extension/metadata/src/test/java/org/geoserver/metadata/EmptyConfigurationTest.java left in tree.

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-2.23.x 2.23.x
# Navigate to the new working tree
cd .worktrees/backport-2.23.x
# Create a new branch
git switch --create backport-7310-to-2.23.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 7af1cbd12b7472606199a554da6933e7dd707de5,5ac7a4d60cd0fb330d63e16d28891aa40c9c6b18
# Push it to GitHub
git push --set-upstream origin backport-7310-to-2.23.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-2.23.x
```
Then, create a pull request where the `base` branch is `2.23.x` and the `compare`/`head` branch is `backport-7310-to-2.23.x`.

**Pull request merged**
