### PR TITLE
[GEOS-8470] Improved validation for LayerGroups containing Style Groups

### PR DESCRIPTION
**Pull request by tbarsballe**
See https://osgeo-org.atlassian.net/browse/GEOS-8470

### CODE REVIEW

**Comment by aaime** [comment]
Looks like we have a legit failure here:

{code}
Tests run: 13, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 5.434 sec <<< FAILURE!
testLayerGroupLinkWithWorkspace(org.geoserver.web.data.layergroup.LayerGroupEditPageTest)  Time elapsed: 1247 sec  <<< ERROR!
java.lang.IllegalArgumentException: Invalid style group: No layer or layer group named 'nestedLayerGroup' found in the catalog
	at org.geoserver.catalog.impl.CatalogImpl.validate(CatalogImpl.java:853)
	at org.geoserver.catalog.impl.CatalogImpl.add(CatalogImpl.java:805)
	at org.geoserver.security.SecureCatalogImpl.add(SecureCatalogImpl.java:1166)
	at org.geoserver.catalog.impl.AbstractFilteredCatalog.add(AbstractFilteredCatalog.java:541)
	at org.geoserver.catalog.impl.AbstractCatalogDecorator.add(AbstractCatalogDecorator.java:438)
	at org.geoserver.catalog.impl.LocalWorkspaceCatalog.add(LocalWorkspaceCatalog.java:214)
	at org.geoserver.web.data.layergroup.LayerGroupBaseTest.onSetUp(LayerGroupBaseTest.java:61)
	at org.geoserver.test.GeoServerSystemTestSupport.setUp(GeoServerSystemTestSupport.java:266)
{code}

**Comment by tbarsballe** [comment]
Fixed the failure (a valid failure almost seems novel; been dealing with so many false failures lately). Having some issues getting Travis to actually function right now - got a couple failed builds due to timeouts. I'll keep an eye on the build and restart again if necessary; standby.

**Comment by tbarsballe** [comment]
Closing and reopening to try and do a more forcible reset of Travis. Currently failing (timing out) on some community modules (NSG WMS?)

**Comment by aaime** [comment]
The community modules are built without tests, and the NSG ones do not add any "new" dependency so... not sure why they would get stuck?

**Comment by bencaradocdavies** [comment]
Close-reopen to pick up latest Travis fix on master.

**Comment by tbarsballe** [comment]
Well, build seems to have passed now. Maybe Travis was just overloaded / slow on Friday?

**Comment by aaime** [comment]
@tbarsballe nope, it's that Ben fixed a deadlock in Maven 3.5.2 by downgrading to 3.5.0 , see the geotools devel list

**Comment by tbarsballe** [comment]
Oh, that explains a bit.

**Comment by bencaradocdavies** [comment]
Yes, I did a close-reopen on three PRs whose Travis builds were affected by the Maven deadlock bug. This was one of them.

**Comment by tbarsballe** [comment]
Backported to 2.12.x

**Pull request merged**
