### PR TITLE
[GEOS-10618] Assemble release geoserver_dir for Docker use

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOS-10618](https://osgeo-org.atlassian.net/browse/GEOS-10618)

A quick assembly to package up the ``release`` geoserver data directory for use with the official docker image. Zip structured with ``geoserver_dir`` folder to match Dockerfile.

I have manually created a ``zip`` for the most recent 2.21.1 release to allow documentation to be written:

* https://sourceforge.net/projects/geoserver/files/GeoServer/2.21.1/geoserver-2.21.1-data.zip/download

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by jodygarnett** [comment]
website download page update https://github.com/geoserver/geoserver.github.io/pull/130

**Comment by aaime** [comment]
Looks good to me, merging.

**Comment by aaime** [comment]
Not sure if you need a backport, if so you can add the backport labels even after the PR is merged, and the bot will try to do the backport PRs for you.

**Comment by jodygarnett** [comment]
Thanks, no harm in back porting I have added the label.

**Pull request merged**
