### PR TITLE
GEOS-7026: fix failing tests on OpenJDK after GEOS-7020 fix

### PR DESCRIPTION
**Pull request by mbarto**

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
@mbarto thanks for the quick turnaround. I can confirm that this change fixes gs-wms tests for openjdk7, openjdk8, oraclejdk7, and oraclejdk8. If Travis CI passes and @aaime is happy to have antialiasing turned off, please merge and backport to 2.7.x and 2.6.x.

**Comment by mbarto** [comment]
@bencaradocdavies @aaime I think it was the original intention to turn off antialias (please @aaime confirm or deny), there is code to set an hint, but unfortunately it is set too late, when the Graphics2D object has already been created using other hints created from the antialias format_options request param and this one defaults to antialiasing set to on

**Comment by bencaradocdavies** [comment]
@mbarto full build with -Prelease passes with locally for me with openjdk7. Travis CI fails for this PR only on oraclejdk7 with a failure in gs-web-sec-core. Looks unrelated. I have seen similar failures before with oraclejdk7, and only in a full build. Nasty, but AFAIKT not your problem.

**Comment by aaime** [comment]
Yes @mbarto, that's fine.

**Pull request merged**
