### PR TITLE
Upgraded spring security version from 5.1.1 -> 5.1.5

### PR DESCRIPTION
**Pull request by JFBorsodi**
Upgraded spring security to latest bugfix version 5.1.5.

### CODE REVIEW

**Comment by aaime** [comment]
Simple change, no build failures, looks good to me. I don't have time to try it out interactively right now and our build servers are down, going to wait a bit before merging (either to get some play time with it or see the build servers operational again, at which point it will go onto some test servers that deploy off master daily).

**Comment by aaime** [comment]
Anyhow, looks like a good job, keep them coming :-D

**Comment by aaime** [comment]
Tried out the basics interactively, run a build of the Oauth2 modules in community, there is a test failure but it was already there and it's unrelated to security itself (it's a GUI test). @afabiani is going to check the integration with GeoNode (which also depends on Oauth) and then we should be good to go.

**Comment by aaime** [comment]
Tests done. @JFBorsodi any chance you can do backport PRs too?

**Comment by JFBorsodi** [comment]
@aaime I will try and get those figured out as soon as I get a chance. Thanks for the first merge!

**Comment by aaime** [comment]
@JFBorsodi for the backports the commit message should be "[GEOS-9221] Upgrade spring security to 5.1.5"

**Pull request merged**
