### PR TITLE
[GEOS-7648] Restablish embeded GeoFence default behavior

### PR DESCRIPTION
**Pull request by nmco**
Associated issue: https://osgeo-org.atlassian.net/browse/GEOS-7648
Mailing list discussion: http://osgeo-org.1560.x6.nabble.com/Embeded-GeoFence-automatic-schema-creation-td5277539.html

The default properties that allow Hibernate to manage the database schema are included again. The order in which overriding properties will be considered was also reestablished (last properties have priority, i.e. priority locations should appear last int he locations list).

The documentation was also updated with a description about GeoFence default behavior.

### CODE REVIEW

**Comment by afabiani** [comment]
Leaving geofence-datasource-ovr.properties inside the JAR will cause errors
when using a configuration different from a H2.

We should at least open an issue trying to fix the parameters override
failures or remove it from the jar.

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------

**Comment by nmco** [comment]
Yes your are correct there is an issue for that: https://osgeo-org.atlassian.net/browse/GEOS-7652

**Comment by aaime** [comment]
The embedded version is not designed to work with anything but H2, it was a design decision to make it quicker to integrate. Once it has a GUI to point to other databases then we can think about them no?

**Comment by nmco** [comment]
I'm lost here, why only using H2 database make GeoFence easy to integrate with GeoServer and how could this be a design decision if GeoFence already has all the necessary machinery to support other databases (and is using Hibernate behind the scenes anyway) ? I'm probably missing something so this is not a rhetoric question (internal vs external models maybe ?).

Unless by quicker to integrate you mean not providing an UI for configuring other databases or providing a clean way for users to contribute the extra db drivers.

Anyway, if the embedded version should only work with the H2 database this should not exist:
https://github.com/geoserver/geoserver/blob/master/src/community/geofence-server/src/main/resources/applicationContext.xml#L56-L74

**Comment by simboss** [comment]
Andrea, the embedded version does not work _right now_ with external DBMS but that's a limitation of the integration not a design intention.

We actually need it to run on top of PostgreSQL and Oracle if we want to use it for real in clustered environments.

**Comment by aaime** [comment]
I just said it was a decision to make GeoFence quicker to integrate, to reduce the scope of the work, never meant to imply it should not be fixed.

**Comment by simboss** [comment]
So I will merge.

**Comment by etj** [comment]
Please also check out commit https://github.com/geoserver/geoserver/commit/9a223558eb328bb089b00eb0828753d949196533 

Default ovr file has been renamed to ``geofence-default-override.properties``. Custom optional file is still named  ``geofence-datasource-ovr.properties``, so the setup is now more straightforward: if you define no other ovr file, the default H2 is used. The optional custom file will be loaded after the default file, so you can properly override any property now.

**Pull request merged**
