### PR TITLE
Build and packaging fixes related to module graduations and removals

### PR DESCRIPTION
**Pull request by aaime**
See: https://osgeo-org.atlassian.net/browse/GEOS-9951

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by aaime** [comment]
Checked the package contains the same jars as 2.18.x:

```
 unzip -t target/release/geoserver-2.20-SNAPSHOT-wps-plugin.zip  | sort
Archive:  target/release/geoserver-2.20-SNAPSHOT-wps-plugin.zip
No errors detected in compressed data of target/release/geoserver-2.20-SNAPSHOT-wps-plugin.zip.
    testing: GEOTOOLS_NOTICE.txt      OK
    testing: GPL.md                   OK
    testing: gs-web-wps-2.20-SNAPSHOT.jar   OK
    testing: gs-wps-core-2.20-SNAPSHOT.jar   OK
    testing: gt-csv-26-SNAPSHOT.jar   OK
    testing: gt-process-geometry-26-SNAPSHOT.jar   OK
    testing: gt-xsd-wps-26-SNAPSHOT.jar   OK
    testing: LGPL.md                  OK
    testing: net.opengis.wps-26-SNAPSHOT.jar   OK
    testing: NOTICE.md                OK
    testing: opencsv-5.0.jar          OK
    testing: serializer-2.7.2.jar     OK
```

```
unzip -t /tmp/geoserver-2.18.2-wps-plugin.zip | sort
Archive:  /tmp/geoserver-2.18.2-wps-plugin.zip
No errors detected in compressed data of /tmp/geoserver-2.18.2-wps-plugin.zip.
    testing: GEOTOOLS_NOTICE.txt      OK
    testing: GPL.md                   OK
    testing: gs-web-wps-2.18.2.jar    OK
    testing: gs-wps-core-2.18.2.jar   OK
    testing: gt-csv-24.2.jar          OK
    testing: gt-process-geometry-24.2.jar   OK
    testing: gt-xsd-wps-24.2.jar      OK
    testing: LGPL.md                  OK
    testing: net.opengis.wps-24.2.jar   OK
    testing: NOTICE.md                OK
    testing: opencsv-5.0.jar          OK
    testing: serializer-2.7.2.jar     OK
```

**Comment by aaime** [comment]
Builds were failing due to absence of arcsde plugin in GeoTools. Removed the GeoServer community module as well.

**Comment by aaime** [comment]
And now it failed because the community release module is looking for mapml. All right, fixing that one too :-D

**Review by dromagnoli — APPROVED** [review]
looks good to me although it seems complaining against a missing release/ext-arcsde.xml
(well, it has been removed :) )

**Comment by aaime** [comment]
Yup fixing it

**Comment by jodygarnett** [comment]
I saw from email that gabe had moved arcsde to a community module here: https://github.com/geoserver/geoserver/pull/3988

**Comment by aaime** [comment]
@jodygarnett that was one year ago. We recently removed the gt-arcsde store completely from the source code of GeoTools (along with gt-validation), the GeoServer commuknity module should have been removed too, but I forgot. This one amends it.

**Comment by aaime** [comment]
Merged on master, should be backported to 2.19.x too

**Pull request merged**
