### PR TITLE
[GEOS-6923] Slow JSON response on EPSG:900913 defined vector layer

### PR DESCRIPTION
**Pull request by aaime**
Pure performance optimization, thus no tests (the existing ones will guard against regressions)

### CODE REVIEW

**Comment by aaime** [comment]
Oh, the reason the change speeds up things is that CRS.lookupEPSGCode will internally leverage the CRS internal identifiers, if avaialble.

**Comment by simboss** [comment]
backport please :)

**Comment by smithkm** [comment]
Looks good to me.

**Comment by NBroomfield** [comment]
Just FYI it looks like you have a superfluous nested if statement that has the same condition at the parent if statement.

**Pull request merged**
