### PR TITLE
[GEOS-10874] Log4J: Windows binary zip release file with log4j-1.2.14

### PR DESCRIPTION
**Pull request by aaime**
[GEOS-10874](https://osgeo-org.atlassian.net/browse/GEOS-10874)

Apparently, just a leftover in the assembly file, from GISP 167 (GEOS-10426). The bin file appears to be running fine without that jar (just made a quick test).

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Review by jodygarnett — APPROVED** [review]

**Comment by bradh** [comment]
The gs-metadata failure is possibly related, but unsure.

**Comment by jodygarnett** [comment]
> The gs-metadata failure is possibly related, but unsure.

Un related; this change should only be visible/testable when running binary release.

**Comment by aaime** [comment]
@NielsCharlier we keep on seeing this failure in the PR... does it ring any bell? (the build has been restarted 4 times so far):

```
2023-06-19T10:28:31.1202664Z 10:28:31,118 [ERROR] Tests run: 9, Failures: 9, Errors: 0, Skipped: 0, Time elapsed: 0.022 s <<< FAILURE! - in org.geoserver.metadata.data.service.ComplexMetadataServiceTest
2023-06-19T10:28:31.1204077Z 10:28:31,118 [ERROR] testClean(org.geoserver.metadata.data.service.ComplexMetadataServiceTest)  Time elapsed: 0.001 s  <<< FAILURE!
2023-06-19T10:28:31.1205228Z java.lang.AssertionError: expected:<the-identifier-single> but was:<null>
2023-06-19T10:28:31.1205828Z 	at org.geoserver.metadata.data.service.ComplexMetadataServiceTest.testClean(ComplexMetadataServiceTest.java:476)
2023-06-19T10:28:31.1206197Z 
2023-06-19T10:28:31.1206532Z 10:28:31,118 [ERROR] testMergeListFields(org.geoserver.metadata.data.service.ComplexMetadataServiceTest)  Time elapsed: 0 s  <<< FAILURE!
2023-06-19T10:28:31.1206999Z java.lang.AssertionError: expected:<5> but was:<3>
2023-06-19T10:28:31.1207543Z 	at org.geoserver.metadata.data.service.ComplexMetadataServiceTest.testMergeListFields(ComplexMetadataServiceTest.java:163)
2023-06-19T10:28:31.1207930Z 
2023-06-19T10:28:31.1208211Z 10:28:31,118 [ERROR] testMergeObject(org.geoserver.metadata.data.service.ComplexMetadataServiceTest)  Time elapsed: 0 s  <<< FAILURE!
2023-06-19T10:28:31.1208842Z org.junit.ComparisonFailure: expected:<[templateValue]-code> but was:<[object]-code>
2023-06-19T10:28:31.1209409Z 	at org.geoserver.metadata.data.service.ComplexMetadataServiceTest.testMergeObject(ComplexMetadataServiceTest.java:126)
2023-06-19T10:28:31.1209781Z 
2023-06-19T10:28:31.1210084Z 10:28:31,118 [ERROR] testMergeListObjects(org.geoserver.metadata.data.service.ComplexMetadataServiceTest)  Time elapsed: 0 s  <<< FAILURE!
2023-06-19T10:28:31.1210538Z java.lang.AssertionError: expected:<4> but was:<2>
2023-06-19T10:28:31.1211078Z 	at org.geoserver.metadata.data.service.ComplexMetadataServiceTest.testMergeListObjects(ComplexMetadataServiceTest.java:228)
2023-06-19T10:28:31.1211465Z 
2023-06-19T10:28:31.1211780Z 10:28:31,118 [ERROR] testMergeListNestedObjects(org.geoserver.metadata.data.service.ComplexMetadataServiceTest)  Time elapsed: 0 s  <<< FAILURE!
2023-06-19T10:28:31.1212245Z java.lang.AssertionError: expected:<1> but was:<2>
2023-06-19T10:28:31.1212806Z 	at org.geoserver.metadata.data.service.ComplexMetadataServiceTest.testMergeListNestedObjects(ComplexMetadataServiceTest.java:281)
2023-06-19T10:28:31.1213220Z 
2023-06-19T10:28:31.1213494Z 10:28:31,118 [ERROR] testDerive(org.geoserver.metadata.data.service.ComplexMetadataServiceTest)  Time elapsed: 0 s  <<< FAILURE!
2023-06-19T10:28:31.1213945Z java.lang.AssertionError: expected:<targetb> but was:<null>
2023-06-19T10:28:31.1214454Z 	at org.geoserver.metadata.data.service.ComplexMetadataServiceTest.testDerive(ComplexMetadataServiceTest.java:452)
2023-06-19T10:28:31.1214808Z 
2023-06-19T10:28:31.1215114Z 10:28:31,119 [ERROR] testDuplicatedRemoved(org.geoserver.metadata.data.service.ComplexMetadataServiceTest)  Time elapsed: 0 s  <<< FAILURE!
2023-06-19T10:28:31.1215563Z java.lang.AssertionError: expected:<5> but was:<4>
2023-06-19T10:28:31.1216097Z 	at org.geoserver.metadata.data.service.ComplexMetadataServiceTest.testDuplicatedRemoved(ComplexMetadataServiceTest.java:401)
2023-06-19T10:28:31.1216489Z 
2023-06-19T10:28:31.1216780Z 10:28:31,119 [ERROR] testUnlink(org.geoserver.metadata.data.service.ComplexMetadataServiceTest)  Time elapsed: 0.019 s  <<< FAILURE!
2023-06-19T10:28:31.1217399Z org.junit.ComparisonFailure: expected:<t[emplate-identifier]> but was:<t[he-identifier-single]>
2023-06-19T10:28:31.1217962Z 	at org.geoserver.metadata.data.service.ComplexMetadataServiceTest.testUnlink(ComplexMetadataServiceTest.java:319)
2023-06-19T10:28:31.1218308Z 
2023-06-19T10:28:31.1218878Z 10:28:31,119 [ERROR] testMergeSimpleFields(org.geoserver.metadata.data.service.ComplexMetadataServiceTest)  Time elapsed: 0.001 s  <<< FAILURE!
2023-06-19T10:28:31.1219510Z org.junit.ComparisonFailure: expected:<t[emplate-identifier]> but was:<t[he-identifier-single]>
2023-06-19T10:28:31.1220118Z 	at org.geoserver.metadata.data.service.ComplexMetadataServiceTest.testMergeSimpleFields(ComplexMetadataServiceTest.java:53)
2023-06-19T10:28:31.1220502Z 
2023-06-19T10:28:31.1220734Z 10:28:31,119 [INFO] Running org.geoserver.metadata.data.service.ConfigurationServiceTest
2023-06-19T10:28:31.1345569Z 10:28:31,134 [ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.013 s <<< FAILURE! - in org.geoserver.metadata.data.service.ConfigurationServiceTest
2023-06-19T10:28:31.1346539Z 10:28:31,134 [ERROR] testFileRegistry(org.geoserver.metadata.data.service.ConfigurationServiceTest)  Time elapsed: 0.001 s  <<< FAILURE!
2023-06-19T10:28:31.1347091Z java.lang.AssertionError: expected:<15> but was:<0>
2023-06-19T10:28:31.1347714Z 	at org.geoserver.metadata.data.service.ConfigurationServiceTest.testFileRegistry(ConfigurationServiceTest.java:34)
2023-06-19T10:28:31.1348408Z 
2023-06-19T10:28:31.1348812Z 10:28:31,134 [ERROR] testGeonetworkMappingRegistry(org.geoserver.metadata.data.service.ConfigurationServiceTest)  Time elapsed: 0.003 s  <<< FAILURE!
2023-06-19T10:28:31.1349560Z java.lang.AssertionError: expected:<10> but was:<0>
2023-06-19T10:28:31.1350200Z 	at org.geoserver.metadata.data.service.ConfigurationServiceTest.testGeonetworkMappingRegistry(ConfigurationServiceTest.java:75)
2023-06-19T10:28:31.1350710Z 
2023-06-19T10:28:31.1351039Z 10:28:31,134 [INFO] Running org.geoserver.metadata.data.service.CustomNativeMappingServiceTest
2023-06-19T10:28:31.9628935Z 10:28:31,962 [ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.826 s <<< FAILURE! - in org.geoserver.metadata.data.service.CustomNativeMappingServiceTest
2023-06-19T10:28:31.9630025Z 10:28:31,962 [ERROR] testCustomToNative(org.geoserver.metadata.data.service.CustomNativeMappingServiceTest)  Time elapsed: 0.431 s  <<< FAILURE!
2023-06-19T10:28:31.9630599Z java.lang.AssertionError: expected:<4> but was:<0>
2023-06-19T10:28:31.9631262Z 	at org.geoserver.metadata.data.service.CustomNativeMappingServiceTest.testCustomToNative(CustomNativeMappingServiceTest.java:58)
2023-06-19T10:28:31.9631752Z 
2023-06-19T10:28:31.9632157Z 10:28:31,962 [ERROR] testNativeToCustomPartial(org.geoserver.metadata.data.service.CustomNativeMappingServiceTest)  Time elapsed: 0.173 s  <<< FAILURE!
2023-06-19T10:28:31.9632720Z java.lang.AssertionError: expected:<2> but was:<0>
2023-06-19T10:28:31.9633368Z 	at org.geoserver.metadata.data.service.CustomNativeMappingServiceTest.testNativeToCustomPartial(CustomNativeMappingServiceTest.java:219)
2023-06-19T10:28:31.9633881Z 
2023-06-19T10:28:31.9634263Z 10:28:31,962 [ERROR] testNativeToCustom(org.geoserver.metadata.data.service.CustomNativeMappingServiceTest)  Time elapsed: 0.165 s  <<< FAILURE!
2023-06-19T10:28:31.9634794Z java.lang.AssertionError: expected:<2> but was:<0>
2023-06-19T10:28:31.9635433Z 	at org.geoserver.metadata.data.service.CustomNativeMappingServiceTest.testNativeToCustom(CustomNativeMappingServiceTest.java:152)
2023-06-19T10:28:31.9635909Z 
2023-06-19T10:28:31.9636220Z 10:28:31,962 [INFO] Running org.geoserver.metadata.data.service.GeneratorServiceTest
2023-06-19T10:28:32.0031600Z 10:28:32,002 [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 s - in org.geoserver.metadata.data.service.GeneratorServiceTest
2023-06-19T10:28:32.0032581Z 10:28:32,003 [INFO] Running org.geoserver.metadata.data.service.GeonetworkXmlParserTest
2023-06-19T10:28:32.1547200Z 10:28:32,154 [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.149 s <<< FAILURE! - in org.geoserver.metadata.data.service.GeonetworkXmlParserTest
2023-06-19T10:28:32.1548190Z 10:28:32,154 [ERROR] testMapping(org.geoserver.metadata.data.service.GeonetworkXmlParserTest)  Time elapsed: 0.148 s  <<< FAILURE!
2023-06-19T10:28:32.1549204Z java.lang.AssertionError: expected:<1a2c6739-3c62-432b-b2a0-aaa589a9e3a1> but was:<null>
2023-06-19T10:28:32.1549860Z 	at org.geoserver.metadata.data.service.GeonetworkXmlParserTest.testMapping(GeonetworkXmlParserTest.java:67)
2023-06-19T10:28:32.1550293Z 
2023-06-19T10:28:32.1550611Z 10:28:32,154 [INFO] Running org.geoserver.metadata.data.service.PlaceHolderUtilTest
2023-06-19T10:28:32.1701584Z 10:28:32,169 [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 s - in org.geoserver.metadata.data.service.PlaceHolderUtilTest
2023-06-19T10:28:32.1703108Z 10:28:32,170 [INFO] Running org.geoserver.metadata.data.service.TemplateServiceTest
2023-06-19T10:28:32.3424242Z 10:28:32,341 [INFO] 
2023-06-19T10:28:32.3425159Z 10:28:32,341 [INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ gs-ogr-wps ---
2023-06-19T10:28:32.3667124Z 10:28:32,366 [INFO] 
2023-06-19T10:28:32.3668005Z 10:28:32,366 [INFO] -------------------------------------------------------
2023-06-19T10:28:32.3668384Z 10:28:32,366 [INFO]  T E S T S
2023-06-19T10:28:32.3668839Z 10:28:32,366 [INFO] -------------------------------------------------------
2023-06-19T10:28:32.9035583Z 10:28:32,903 [ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.731 s <<< FAILURE! - in org.geoserver.metadata.data.service.TemplateServiceTest
2023-06-19T10:28:32.9036511Z 10:28:32,903 [ERROR] testUpdate(org.geoserver.metadata.data.service.TemplateServiceTest)  Time elapsed: 0.19 s  <<< FAILURE!
2023-06-19T10:28:32.9037182Z java.lang.AssertionError: expected:<updated-value> but was:<null>
2023-06-19T10:28:32.9037759Z 	at org.geoserver.metadata.data.service.TemplateServiceTest.testUpdate(TemplateServiceTest.java:142)
```

**Comment by NielsCharlier** [comment]
No, at first sight I cannot comprehend how this is related and why this is happening

**Comment by aaime** [comment]
Confirmed we have a build failure in gs-metadata in both the [build server](https://build.geoserver.org/view/geoserver/job/geoserver-main/) and locally as well (Windows laptop that I was setting up for FOSS4G). If this does not get resolved promptly we'll have to start reverting PRs until we get back to a stable build.

**Comment by aaime** [comment]
Weird find: the build seems to work fine if it's run sequentially. So maybe it's either a shared files/TCP ports-related issue, or maybe related to the re-use of the JVMs for tests (the history of the JVM used to run gs-metadata tests would be different in a sequential build compared to a parallel build).

I can also confirm the build failure locally on my Linux machine, running a -T6 build, but it works fine, when building the module by itself.

**Pull request merged**
