### PR TITLE
[GEOS-9224] Add MapML preview link to the Layer Preview page

### PR DESCRIPTION
**Pull request by prushforth**
## Description

This PR provides users of the MapML Community Module with a simple way to view the MapML document in a built-in client, in a similar way to that used for OpenLayers.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)

The following are required only for core and extension modules, while they are welcomed, but not required, for community modules:
- [x] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [x] New unit tests have been added covering the changes
Some.  Could do with more, plus some integration tests would be good.
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [x] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by jodygarnett** [comment]
What remains to be done?
- looks like just an entry in the user interface docs?

**Comment by aaime** [comment]
If he wants to... a community module has no requirement for user docs, or updates of them. It's however a nice touch to have them, helps users use the module.

**Comment by prushforth** [comment]
>  a community module has no requirement for user docs, or updates of them. It's however a nice touch to have them, helps users use the module.

Sure, it's a good idea, I'll add a bit to what @cmhodgson has created already.

**Comment by prushforth** [comment]
I squashed all the commits.  It should pass travis etc.  I put a bit of documentation into the section on MapML visualization.

**Comment by jodygarnett** [comment]
Ah, my bad, keep forgetting this is a community module.

**Comment by prushforth** [comment]
Well, that brings me to the question about what is required for it to graduate?

**Comment by jodygarnett** [comment]
We have a list over [here](https://docs.geoserver.org/latest/en/developer/policies/community-modules.html#promoting-a-community-module) in our developers guide.

**Comment by prushforth** [comment]
@jodygarnett how can I tell what test coverage I have?

**Comment by jodygarnett** [comment]
We have a profile [here](https://docs.geoserver.org/latest/en/developer/maven-guide/index.html#generating-test-coverage-reports) in our developers guide.

Part of taking a module supported involves becoming a committer on the project, and we ask that you have read and understood the developer's guide :)

**Comment by prushforth** [comment]
> Part of taking a module supported involves becoming a committer on the project, and we ask that you have read and understood the developer's guide :)

OK thanks, that would be a good place to start :-)

**Comment by aaime** [comment]
@prushforth you'll also have to write a proposal and ask the PSC to discuss/vote it:
https://github.com/geoserver/geoserver/wiki/Proposals

Here is an example (there are more in the page above):
https://github.com/geoserver/geoserver/wiki/GSIP-170

**Comment by prushforth** [comment]
@aaime and @jodygarnett thank you both. I feel that before I write a proposal, the community module code needs to become more robust, and of course the format itself needs more hardening from usage.  As well, I need to lurk and code a bit more. The plan is to make it as easy as possible to serve and use MapML, so becoming a GeoServer extension or even a core module would be an improvement for users from an ease of access perspective.  So, hopefully it will progress in this direction.  And it would help us make the case that MapML is in demand if a browser or two showed some interest in implementing native support.  The format is meant to be a bridge between the Web browser and Web mapping communities (NOT a bridge too far!). Cheers!

**Pull request merged**
