### PR TITLE
[backport 2.12.x] Remove explicit PostgreSQL version in GeoGig module POM

### PR DESCRIPTION
**Pull request by emerkle826**
back-porting this pom change as it missed the 2.12/2.13 cutoff

### CODE REVIEW

**Comment by emerkle826** [comment]
closing this as commit : https://github.com/geoserver/geoserver/commit/20ec34645cbfa235ee12aed16e33b3f049a074c4#diff-96d5825f70d1b151527c8384ab158bce is not in the 2.12.x branch.

**Comment by bencaradocdavies** [comment]
@emerkle826 you can reopen this pull request when [GEOS-8314](https://osgeo-org.atlassian.net/browse/GEOS-8314) is backported.

**Comment by emerkle826** [comment]
Thanks @bencaradocdavies and will do!

**Comment by bencaradocdavies** [comment]
@emerkle826 I will reopen this PR once the [GEOS-8314 backport pull request](https://github.com/geoserver/geoserver/pull/2614) is merged.

**Comment by bencaradocdavies** [comment]
Ah, @emerkle826 you have deleted your geogig-pom branch so I cannot reopen this PR. Please resubmit these changes.

**Comment by emerkle826** [comment]
@bencaradocdavies I restored the branch and re-opened. Thanks again for staying on top of this one!

**Comment by bencaradocdavies** [comment]
Thanks @emerkle826.

**Pull request merged**
