### PR TITLE
[GEOS-8434, GEOS-8436, GEOS-8439, GEOS-8438] Allow WMTS to use CITE compliance mode

### PR DESCRIPTION
**Pull request by nmco**
Associated issues:
- https://osgeo-org.atlassian.net/browse/GEOS-8434
- https://osgeo-org.atlassian.net/browse/GEOS-8436
- https://osgeo-org.atlassian.net/browse/GEOS-8439
- https://osgeo-org.atlassian.net/browse/GEOS-8438

**Depends on this PR https://github.com/GeoWebCache/geowebcache/pull/572**

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
Close and reopen to fix Travis (stale GWC?).

**Comment by bencaradocdavies** [comment]
At least one of the failures was caused by a stale JTS jar in the Travis cache. Close-reopen to rebuild with latest head and cache.

**Comment by bencaradocdavies** [comment]
The JTS jar failure is fixed, but the gs-gwc failure remains:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project gs-gwc: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/geoserver/geoserver/src/gwc/src/main/java/org/geoserver/gwc/layer/StyleParameterFilter.java:[100,18] error: constructor ParameterException in class ParameterException cannot be applied to given types;
[ERROR]  actual and formal argument lists differ in length
[ERROR] /home/travis/build/geoserver/geoserver/src/gwc/src/main/java/org/geoserver/gwc/wmts/WMTSCapabilitiesProvider.java:[58,15] error: cannot find symbol
```

**Comment by aaime** [comment]
@bencaradocdavies this pull request depends on a GWC one that has not been merged yet: https://github.com/GeoWebCache/geowebcache/pull/572

**Pull request merged**
