### PR TITLE
[GEOS-10026] Link from user documentation to issue tracker

### PR DESCRIPTION
**Pull request by aaime**
[GEOS-10026](https://osgeo-org.atlassian.net/browse/GEOS-10026) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

image

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the `main` branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by aaime** [comment]
I've noticed the link also appears in the doc guide and in the developer guide:

- Is this a problem?
- If so, is there a simple way to recognize which guide is being built, and act accordingly?

**Comment by mprins** [comment]
I don't think having the link in docguide or devguide as well is a problem.
I think the only way around that is having different templates; the build already knows what is being built:
https://github.com/geoserver/geoserver/blob/62d5b01a9a637012f9b7a69e8acc5993f6f1c223/doc/en/build.xml#L78-L94
so I think those would need an extra option to set the template or perhaps use a variable condition to enable the link in the template.

**Comment by bradh** [comment]
That could be interpreted as "Found an issue (in the docs)?" Otherwise seems OK.

**Comment by aaime** [comment]
@bradh good point, anyone has suggestions to improve the wording? Ought to be a short sentence.

**Comment by bradh** [comment]
"Known GeoServer issues" perhaps

**Comment by aaime** [comment]
Updated

**Pull request merged**
