### PR TITLE
[GEOS-7675] ImageMosaic documentation refactor

### PR DESCRIPTION
**Pull request by simboss**
Initial work for refactoring the ImageMosaic documentation. More will come soon.

### CODE REVIEW

**Comment by jodygarnett** [comment]
Okay I screwed this up, thought this was ready - but then saw some of the docs say "not true", and simboss above saying "more coming soon".

While I reverted the commit I do not see a way to reopen the pull request.

**Comment by bmmpxf** [comment]
Hey, was just looking at this. It's fine, just let these commits in, and I'll fix it up and commit. It'll be easier than managing PRs anyway.

**Comment by jodygarnett** [comment]
okay I will cherry pick it back onto master, sorry for the trouble :(

**Comment by simboss** [comment]
My fault, I though I had updated that section after an internal discussion with @aaime  but I did not.
I am going to fix it and backport before the new stuff gets aded

**Pull request merged**
