### PR TITLE
[GEOS-10251] Update mapml-viewer to support refactored mapml vocabulary.

### PR DESCRIPTION
**Pull request by prushforth**
[GEOS-10251](https://osgeo-org.atlassian.net/browse/GEOS-10251)

This is the second commit (apologies, the first one broke the viewer, just discovered today during a backport) and PR to implement the change in the mapml vocabulary (introduces hyphenated custom element names, in accord with Web platform best practice).
  

# Checklist

- [x ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes. 
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by jodygarnett** [comment]
@prushforth I am having trouble checking out main, due to the file `src/extension/mapml/src/main/resources/viewer/widget/proj4leaflet.js` having the CRLF encoding.

As a result when I check out `main` it shows this file as modified.

Can you experiment with doing a `git reset --hard 05f42bf337ee9fc4c7c6336070a7066e27ca5488` to see if the file immediately shows up as modified for you?

**Comment by jodygarnett** [comment]
See c32fc10bb294bea9efa3a1b3dd4fcaa897c82dbc

**Comment by prushforth** [comment]
Ok I noticed that, was hoping it was just me

I will fix asap

Peter

**Comment by jodygarnett** [comment]
I think I fixed it everywhere :)

**Comment by prushforth** [comment]
🍻 cheers Jody, thank you!

Peter

**Pull request merged**
