### PR TITLE
[GEOS-8724] Intermittent build failure in NamespacesWfsTest

### PR DESCRIPTION
**Pull request by nmco**
Associated issue:
https://osgeo-org.atlassian.net/browse/GEOS-8724

### CODE REVIEW

**Comment by nmco** [comment]
Travis build failure is unrelated to this, I restarted the build two times already ... I will until until tomorrow to restart it.

**Comment by bencaradocdavies** [comment]
Thanks @nmco. I ran a batch of 30 geoserver builds on master after this PR was merged and saw not a single `NamespacesWfsTest` failure (just a single gs-main `ResourcePoolTest` failure). Looks good to me.

**Comment by nmco** [comment]
Phew, that's good news thank you @bencaradocdavies !

**Comment by bencaradocdavies** [comment]
@nmco celebrations might be premature: this change might break [geoserver-master-app-schema-online for postgis in `PagingTest`](https://build.geoserver.org/view/geoserver/job/geoserver-master-app-schema-online/1159/console). Repeatable every time locally. I am running a test revert to confirm.

**Pull request merged**
