### PR TITLE
[GEOS-6850] Multiple Thread Pools left running at shutdown

### PR DESCRIPTION
**Pull request by dieterstueken**
[GEOS-6850](https://osgeo-org.atlassian.net/browse/GEOS-6850)

The `OSHISystemInfoCollector` is missing the `thread.setDaemon(true)` flag. The other threads and thread pools mentioned are already daemon threads. Thus `OSHISystemInfoCollector` inhibits Tomcat from a clean shutdown.

I submitted two commits, one to solve the main problem. The other one is just a refactoring: The lambda expression is nice but also a bit confusing. I converted it into a separate method. Is also sets an appropriate name for the thread to ease locating it for debugging.

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by jodygarnett** [comment]
Triggered this to run; not quite sure how to write a test case for this one (as per our policy). Can you check if any of the other thread pools have a test case to confirm cleanup?

**Comment by mprins** [comment]
restored the mandatory checklist, 
@dieterstueken please fix formatting

**Comment by mprins** [comment]
the ticket mentioned (2015) predates the addition of monitoring by ~2 years (2017)

**Comment by aaime** [comment]
Ok, closing this PR then. Please make sure to run a maven build on the next PR so that formatting follows convention (otherwise the QA build will fail like in this one).

BTW, I did open a ticket specific to the OSHI collector, which you might want to use for the next PR.
https://osgeo-org.atlassian.net/browse/GEOS-10689

**Pull request closed without merging**
