### PR TITLE
[GEOS-11271] Upgrade spring-security to 5.8

### PR DESCRIPTION
**Pull request by awaterme**
[GEOS-11271](https://osgeo-org.atlassian.net/browse/GEOS-11271) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

Pull request for [GEOS-11271](https://osgeo-org.atlassian.net/browse/GEOS-11271)

Upgrades Spring Security 5.7.12 -> 5.8.13 (latest 5.8.x) and Spring 5.3.34 -> 5.3.37

**Spring Upgrade**
Spring-Security 5.8.13 depends on Spring 5.3.37, so I decided to upgrade Spring, too. The Spring upgrade is  comprising compatible release only, as per [Spring release notes](https://github.com/spring-projects/spring-framework/releases).

**Spring Security Upgrade**
The Spring Security upgrade is the preparation for the switch from deprecated [spring-security-oauth](https://spring.io/projects/spring-security-oauth) project (now https://github.com/spring-attic/spring-security-oauth) to the OAuth funtionality of spring security itself.

**Spring Security Upgrade - Compatibility**
According to the [Spring website](https://docs.spring.io/spring-security/reference/5.8/migration/index.html) "Spring Security 5.8 is fully compatible with Spring Security 5.7".

Checking the [Spring Security release notes](https://github.com/spring-projects/spring-security) I found the following breaking changes, which are not relevant for GeoServer, as far as I can see:

- https://github.com/spring-projects/spring-security/releases/tag/5.8.0-M1
   - SecurityExpressionHandler#createEvaluationContext should defer lookup of Authentication #9667
      - Result: OK, GeoServer is not using SecurityExpressionRoot

- https://github.com/spring-projects/spring-security/releases/tag/5.8.0-RC1
   - Make X-Xss-Protection header value configurable in ServerHttpSecurity #11908
      - Result: Ok, ServerHttpSecurity seems not to be used in GS

**Spring Security Upgrade - Testing Status**
Unit Tests
- "green"

Manual Tests:
- GeoServer application is basically running
- Form-based login is possible
- Basic Auth login is possible, checking WFS GetFeature
- OAuth2 Login with Github is working as before

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by awaterme** [comment]
The build failed due to usage of deprecated API in the area of Spring security. I will have a look at that.

**Comment by awaterme** [comment]
I have fixed the deprecation warnings: Some flexible Spring classes used by GeoServer have been deprecated and replaced by inflexible ones that are not useful in this context. As a solution, I have incorporated the flexible Spring code into GeoServer (as `AuthenticatedAuthorizationManager`, `RoleAuthorizationManager`, `AffirmativeAuthorizationManager`), simplified it accordingly, and adapted it to the new Spring API (`AuthorizationManager`).

The `AuthorizationManager `API requires the use of `HttpServletRequest` instead of `FilterInvocation`. This necessitated the adaptation of `RESTfulDefinitionSource`. `RESTfulPathBasedFilterInvocationDefinitionMap` was renamed to `RESTfulDefinitionSourceDelegateMap` because it no longer uses `FilterInvocation`. `RESTfulDefinitionSourceDelegateMap` no longer implements Spring interfaces, as this was obscuring the purpose of the class.

From my point of view, the probability of a defect arising from this change is low because the new implementation is very close to the previous one. However, I would appreciate a review by the responsible module maintainer.

I suppose this changes can be considered internal and are not breaking third party code.

I will be on holiday until 2024-08-13 now.

**Comment by jodygarnett** [comment]
Nice work :) Looks like there are some PMD failures to address

**Comment by awaterme** [comment]
Hi Jody,

From the build summary:

> Error: 7,507 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.14.0:check (default) on project gs-rest: You have 4 PMD violations. For more details see: /home/runner/work/geoserver/geoserver/src/rest/target/pmd.xml

I have not touched sources in the rest module. So I suppose those failures where there before.

It is in `org.geoserver.rest.util.IOUtilsTest` ([see build logs](https://github.com/geoserver/geoserver/actions/runs/10092235179/job/27905477179#step:6:1648))

**Comment by jodygarnett** [comment]
Oh no :) I will have a look. Enjoy your vacation.

**Comment by jodygarnett** [comment]
I have rebased locally, and am building (to test the community security plugins build):
```
mvn clean install -DskipTests -Prelease,communityRelease
```

And do a normal QA build (for PMD and formatting):
```
mvn clean install -Dqa -Prelease
```

**Review by jodygarnett — APPROVED** [review]
Marking this as approved, but I invite folks invested in the community module to do hands on testing. 

Or we can just merge as there is some weeks before 2.26.x release :)

**Comment by jodygarnett** [comment]
Rebase successful

**Review by mprins — APPROVED** [review]
lgtm

**Pull request merged**
