### PR TITLE
Travis CI: The 'sudo:' tag is deprecated in Travis

### PR DESCRIPTION
**Pull request by cclauss**
<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by cclauss** [comment]
[ERROR] /home/travis/build/geoserver/geoserver/src/platform/src/main/java/org/geoserver/platform/resource/FileSystemResourceStore.java:[238,39] unreported exception java.lang.Throwable; must be caught or declared to be thrown

**Comment by bradh** [comment]
I don't think anything beyond JDK11 is supported at this time.

**Comment by cclauss** [comment]
[_allow_failures_] [_lets you add in experimental and preparatory builds to test against versions or configurations that you are not ready to officially support._](https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail)

**Comment by aaime** [comment]
Correct,  only JDK 8 and 11 must be used in the build, nothing else is supported.

**Comment by bradh** [comment]
> 
> 
> [_allow_failures_] [_lets you add in experimental and preparatory builds to test against versions or configurations that you are not ready to officially support._](https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail)

Even if that was wanted, that doesn't match the entries you've added / modified.

**Comment by cclauss** [comment]
The test failure does not look difficult to fix and should works on previous versions of Java.
https://travis-ci.org/geoserver/geoserver/jobs/587991933#L1427

**Comment by aaime** [comment]
@cclauss yes that single failure is easy to fix... what scares me is what follows, and having to do it on geotools and geowebcache too (the 3 projects are a "train", what we do with one we do with the others).
I'd rather not go down that rabbit hole in my spare time, it has a tendency to end up poorly (long hours, family upset, and the like) :-D

**Comment by aaime** [comment]
Checked sudo tag is indeed deprecated and merged. Thanks!

**Pull request merged**
