### PR TITLE
[GEOS-10624] data directory ne workspace

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOS-10624](https://osgeo-org.atlassian.net/browse/GEOS-10624)

This key addition is of the ne workspace containing a geopackage and associated layers for a simple world map. The geopackage is produced by a build/data/build.xml ant script that downloads and processes a geopackage using gdal/ogr.

The main goal of this PR is to have a sample geopackage in our `data/release`, ideally with the countries, populated_places, roads layers used by the styling workshop. GeoServer PSC Meeting placed a guidelines of 1 MB for this activity and sadly the roads layer did not fit.

This change updates contact information in support of [GSIP 202] Welcome Page and thus requires #6122 (and is not suitable for backport):

* Welcome message introducing service
* For more information: both organization name and online resource to display a link
* Contact admin: requires email address mailto link

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by jodygarnett** [comment]
For #6122 @aaime wrote:

----

About the new NE map, labels at this scale denominator would have plenty of space, I keep on wondering if labels are broken as I zoom in and out:

image

They show up at the next zoom level, where the generalization of country borders is too visible:

image

The net result is that it's difficult to see a "nice map".

**Comment by jodygarnett** [comment]
@aaime you are correct labels were broken, changed to using label rank for better result.
image
image
image
image
image

**Comment by jodygarnett** [comment]
Adjusted the other styles to adjust line width and presentation based on scale
image

It is fine

**Comment by bradh** [comment]
Didn't review the PR, but for the purpose of having some linear features for styling, could we include railways instead of roads?

**Comment by aaime** [comment]
Agree the labels are now behaving in what feels a natural way.

**Comment by jodygarnett** [comment]
> Didn't review the PR, but for the purpose of having some linear features for styling, could we include railways instead of roads?

We could include railways or rivers; railways are not so exciting in North America I am afraid :)

But really anything that is not "roads" involves re-writing the styling workshop. Let me double check how large roads are when when scaled to the level of the other layers ...

**Comment by jodygarnett** [comment]
> Didn't review the PR, but for the purpose of having some linear features for styling, could we include railways instead of roads?

We have boundaries and coastlines which provide some examples of linear styling; just no good opportunities for labeling.

**Review by aaime — APPROVED** [review]
Looks good to me.

**Comment by jodygarnett** [comment]
* [x] Make the ne the default workspace

**Comment by jodygarnett** [comment]
> Didn't review the PR, but for the purpose of having some linear features for styling, could we include railways instead of roads?

I checked and railroads does not have any labels (so does not meet the goal).

**Comment by jodygarnett** [comment]
Labels updated base on feedback; looks a bit complicated (something to consider during RC).
image

**Pull request merged**
