### PR TITLE
[GEOS-6964] Collapse zero-length date ranges to just a date when formatting

### PR DESCRIPTION
**Pull request by bradh**
Also adds unit tests for existing ISO8601Formatter functionality.

### CODE REVIEW

**Comment by aaime** [comment]
Hum... I don't have the spec in front of my but wondering, is it going to be a problem if we end up mixing ranges and single values in the same list? Say that there are legit ranges, but mixed among them, some single value ones.

**Comment by bradh** [comment]
I had a look at the OGC best practice for time/elevation data (which basically "clarifies" WMS 1.3 spec in this area, but I couldn't see anything specific). On review of WMS 1.3 (OGC 06-042) Table C.2, I think that it would *not* be valid to have a mix of ranges and single values.

I'll have to think harder about this, almost certainly adding a formatter (or simplifier) at the whole dimension level.

**Comment by aaime** [comment]
I'd look into a fix in the netcdf reader if that is possible, it might have more information to decide how to present the data without having to scan the whole collection of values every time.
As an alternative, it could be a flag in GeoServer that forces it to flatten ranges to single values but... it kind of seems like a workaround for a problem that should be solved elsewhere.

**Comment by bradh** [comment]
I did look at netcdf, but its coupled to a TemporalDomain interface that only returns SortedSet<DateRange>, which makes it difficult...

**Pull request closed without merging**
