### PR TITLE
[GEOS-9333] choose image dialog for legend graphic

### PR DESCRIPTION
**Pull request by NielsCharlier**
In the style edit page, the "choose image" dialog that exists in the SLD editor could be used in the legend panel as well, so that the user can either select or upload an image

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [x] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [x] New unit tests have been added covering the changes
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [x] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by aaime** [comment]
Please do not remove the checklist, use it and fill instead. 
Part of the checklist includes updating the documentation for user visible changes, this is one of them.

I've tried to use the image selection dialog in the past and found it to be ... useless... this is because we normally keep images in a sub-directory, and the image dialog seems to only list images found in the styles directory itself. I guess that limitation still holds in this PR?

**Comment by NielsCharlier** [comment]
Yes. The main purpose of the dialog is actually not the selection but to allow the user to upload a new image using the GUI. Especially useful when using jdbc resource store or if the user doesn't have immediate access to the file structure of the server.

The dialog does indeed assume storage of the images in the same folder as the style. It would be a good addition to allow the selection of a subfolder, or perhaps a possibility to configure it to always use a specific subdirectory instead of the same directory. The last option is perhaps better, because not only is it less work to implement ; it would not burden the user with more clicking steps and choices.

I'm sorry about the checklist, I will not remove it in future PR's. I will add a documentation update.

**Comment by NielsCharlier** [comment]
The orange bar is a horizontal scroll bar on my system.
The svg should indeed be removed in this case as an option

**Comment by NielsCharlier** [comment]
fixed extensions

**Comment by aaime** [comment]
Looks good to me, merging.

**Pull request merged**
