### PR TITLE
Support decorations with multiple layers and legend styling in WPS downloads

### PR DESCRIPTION
**Pull request by jemacchi**
This PR involves improvements on decorations and legend styling on WPS downloads, in a way that:
1) allow to style the background color, opacity and other styling attributed for a LegendDecorator, 
2) allow to add multiple legend decorations based on layers that are requested in the WPS payload.

As an example of use, a request with this payload

```xml
<wps:Execute version="1.0.0" service="WPS"
   (...)
    <wps:Input>
      <ows:Identifier>layer</ows:Identifier>
      <wps:Data>
        <wps:ComplexData xmlns:dwn="http://geoserver.org/wps/download">
          <dwn:Layer>
            <dwn:Name>tiger:tiger_roads,</dwn:Name>
            <dwn:DecoratorName>layout1</dwn:Name>
          </dwn:Layer>
        </wps:ComplexData>
      </wps:Data>
    </wps:Input>
    (...)
    <wps:Input>
      <ows:Identifier>layer</ows:Identifier>
      <wps:Data>
        <wps:ComplexData xmlns:dwn="http://geoserver.org/wps/download">
          <dwn:Layer>
            <dwn:Name>tiger:poly_landmarks</dwn:Name>
            <dwn:DecoratorName>layout2</dwn:Name>
          </dwn:Layer>
        </wps:ComplexData>
      </wps:Data>
    </wps:Input>
  </wps:DataInputs>
  (...)
```

with these layouts definitions (layout1 and layout2) 

```
<layout>
	<decoration type="layout_roads" affinity="top,right" offset="6,6" size="auto">
               <option name="legend_options" value="bgColor:0xFFFFEE;"" />
        </decoration>
</layout>
```
and

```
<layout>
	<decoration type="layout_lands" affinity="top,left" offset="6,6" size="auto">
               <option name="legend_options" value="bgColor:0xFFFFEE;"" />
        </decoration>
</layout>
```
 would result in 

image

Also it's possible to set a header area at top of result on which legends can be placed (using a new optional Input for the WPS gs:downloadMap process)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [x] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [x] New unit tests have been added covering the changes
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [x] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [x] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by mprins** [comment]
Using the pull request template is not optional, so I've added that back.

Your code introduces formatting errors, you will need to run `mvn fmt:format` before committing to resolve that.
```
[INFO] Processed 44 files (2 non-complying).
[INFO] Compiling 12 source files to /home/travis/build/geoserver/geoserver/src/community/wfs3/target/test-classes
[ERROR] Found 2 non-complying files, failing build
[ERROR] To fix formatting errors, run "mvn fmt:format"
[ERROR] Non complying file: /home/travis/build/geoserver/geoserver/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java
[ERROR] Non complying file: /home/travis/build/geoserver/geoserver/src/community/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadMapProcessTest.java
[INFO] FAILURE build of project org.geoserver.community:gs-wps-download
[INFO] Builder state: blocked=3 finished=34 ready-or-running=60 
```
see: https://travis-ci.org/github/geoserver/geoserver/jobs/745964408#L13586-L13593

**Comment by jemacchi** [comment]
hi @mprins thanks for comment. I believed that mvn clean install (at root folder level) was applying that format rules at the community project too, but it seems that it was not doing that (or I missed something).  
A simple mvn fmt:format (as suggested) under community/wps-donwload  fixed those 2 files.
Thanks again!

**Comment by aaime** [comment]
@jemacchi a simple build with no profiles just builds the core modules:
* Add ``-Prelease`` to make it build the extension modules as well
* cd into ``community`` and run the builld with ``-PcommunityBuild -DskipTests`` to run a community build (community modules don't get their test run, only modules with a maintainer get that, bit of reciprocity for core devs having to care for anything in the build when working on supported modules). Or better yet, run a build in the module, with tests.

**Comment by jemacchi** [comment]
@aaime excellent ! thanks for detailed explanation.

**Comment by aaime** [comment]
@jemacchi can you please fill in the PR checklist? It has been added, but you should also check anything that applies yourself.
CLA wise, you're covered by GeoSolution's company own CLA (for the random reader, yep, Jose works with GeoSolutions).

**Review by aaime — CHANGES_REQUESTED** [review]
Noted a couple of minor issues. 

One thing I'm torn about is the handling of the ``headerheight`` parameter, on whether is should be added or removed from the specified height. This relates to the WMS handling of aspect ratio: the WMS builds a map exactly as requested, with the specified bbox, width and height, it's up to the client to make the two agree to have a 1:1 aspect ratio in the output.
For a visual depiction of this, try the following WMS request, it's highly deformed, but valid, it's the client that asked for that specific aspect ratio in the end:
https://tb16.geo-solutions.it/geoserver/dggs/wms?service=WMS&version=1.1.0&request=GetMap&layers=dggs%3Aworld&bbox=-180.0%2C-89.9%2C180.0%2C83.674733&width=768&height=100&srs=EPSG%3A4326&styles=&format=image/png

So going back to ``headerheight``:

* If it's removed from the requested height, then the client has to account for it when setting the parameters, and add to the output height the header height as well, in order to maintain a 1:1 aspect ratio.
* If it's added to the requested height instead, the bbox,widht and height can be determined like in a normal WMS client, but the resulting image will be taller.

There is no perfect solution there... one thing I've noticed, is that the "height" is declared as the "map height" in the code:
https://github.com/geoserver/geoserver/blob/69125489c91c8ac9bbaf77f4c7bba419d6b74a34/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadMapProcess.java#L147

So if you keep the current behavior, probably the description of width and height should be changed to "Output width" and "Output height". 
Regardless of the path chosen, it would be best to highlight the issue in the process documentation.

**Comment by aaime** [comment]
@jemacchi you checked the "There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)" but I cannot find one. 

The PR is ready to merge, but I need to squash merge it down to one commit, and put the final commit message in the "[GEOS-XYZW] title" form. There needs to be a Jira ticket to do that.

We also use Jira tickets to create changelogs for releases, and use the ticket number in commits to link commits to tickets. 

Please open one and let me know when you're done with it. For future work, please open a Jira ticket before creating the PR, and refer to it in the description.

**Comment by jemacchi** [comment]
> Please open one and let me know when you're done with it. For future work, please open a Jira ticket before creating the PR, and refer to it in the description.
@aaime 
Done.  https://osgeo-org.atlassian.net/browse/GEOS-9814
Thanks, and sorry. My bad.

**Comment by aaime** [comment]
Well done, thanks! PR merged.

**Comment by aaime** [comment]
Ah, since this is a community module, if you need to do backports, you can do so now (had it been a new feature in a supported module, we would have either have had to wait a month with no incident, or asked for an early backport on the devel list, argumenting why it's not dangerous).

**Comment by simboss** [comment]
@jemacchi please, backport to 2.18

**Comment by jemacchi** [comment]
> @jemacchi please, backport to 2.18
@aaime @simboss 
Created [PR](https://github.com/geoserver/geoserver/pull/4591) for backport to 2.18.x .

**Pull request merged**
