### PR TITLE
Change staging directory from release to distribution

### PR DESCRIPTION
**Pull request by jodygarnett**
This prevents gitignore from conflicting with src/release folder.

### CODE REVIEW

**Comment by bradh** [comment]
Ah. Missed docs update. Looks like there are two places the `release/<TAG>` gets mentioned. First one is at https://github.com/geoserver/geoserver/blob/bb7a1a12ee3400901d8ade4b1c5946639a240d46/doc/en/developer/source/release-guide/index.rst#build-the-release and the second is a few paragraphs down.

**Comment by jodygarnett** [comment]
> Ah. Missed docs update. Looks like there are two places the `release/<TAG>` gets mentioned. 

Remember this takes place on a worker, there needs to be a separate step (as with nightlies) to sync releases over to the build server. It is not strictly needed since we are uploading to source forge ....

**Comment by bradh** [comment]
> I am not sure we have any plans to make that work, new build server collects the artifacts on the job page.
> 
> Remember this takes place on a worker, there needs to be a separate step (as with nightlies) to sync releases over to the build server. It is not strictly needed since we are uploading to source forge ....

Valid. Probably just needs docs deletion.

**Comment by tbarsballe** [comment]
> I am not sure we have any plans to make that work, new build server collects the artifacts on the job page.

The original plan was to make that work eventually, but I still haven't been able to figure out how to get worker nodes to ssh to the master nodes (and that is a bit of an inversion of the expected secure process, so I'm not entirely sure we even want workers to be able to do that)

Either way, looks good to me. I'll verify everything actually works when I do the release next week.

**Pull request merged**
