### PR TITLE
[GEOS-11433] Upgrade maven-pmd-plugin to 3.23.0 and PMD 7.2.x

### PR DESCRIPTION
**Pull request by mprins**
This upgrades to the [current release of the maven-pmd-plugin](https://maven.apache.org/plugins/maven-pmd-plugin/releasenotes.html) which uses PMD 7.0.0 by default; override that version with [7.2.0 to benefit from the latest bugfixes](https://docs.pmd-code.org/pmd-doc-7.2.0/pmd_release_notes.html). 
While at it also update the build steps in the GH workflow.
In 7.0.0 some rules have changed, this requires some changes in the selected rules.
As a result some PMD warnings are now triggered that need fixing.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
Nice one! Ambitious, too :rofl: 
I'll see if I can help, but can't promise anything in the short term.

**Comment by mprins** [comment]
This turns out to be much more work than anticipated, unfortunately I've no run out of time due to upcoming holiday, so this PR will stall from my side for a couple of weeks. Anyone willing to spend some time on it is quite welcome 🤣

**Comment by aaime** [comment]
Migrated a couple of modules while I was travelling.

**Comment by aaime** [comment]
And a few more under "web" (but not all yet)

**Comment by aaime** [comment]
And a few more fixes today.

**Comment by mprins** [comment]
rebased and fixed merge conflicts

**Comment by aaime** [comment]
Expanded the work to GWC: https://github.com/GeoWebCache/geowebcache/pull/1279

**Comment by aaime** [comment]
@mprins I'm trying to do the same on GeoTools and there I've also tried to add the github action turning failures into comments (nice one!).

However... it's not working, looked up the error message but came up empty:

```
With the provided path, there will be 11 results uploaded
Creating annotations for /home/runner/work/geotools/geotools/build/maven/jjtree-javacc/target/pmd.xml
Creating annotations for /home/runner/work/geotools/geotools/modules/library/api/target/pmd.xml
Creating annotations for /home/runner/work/geotools/geotools/modules/library/http/target/pmd.xml
Creating annotations for /home/runner/work/geotools/geotools/modules/library/main/target/pmd.xml
Creating annotations for /home/runner/work/geotools/geotools/modules/library/metadata/target/pmd.xml
Creating annotations for /home/runner/work/geotools/geotools/modules/library/referencing/target/pmd.xml
Creating annotations for /home/runner/work/geotools/geotools/modules/library/sample-data/target/pmd.xml
Creating annotations for /home/runner/work/geotools/geotools/modules/plugin/epsg-hsql/target/pmd.xml
Creating annotations for /home/runner/work/geotools/geotools/modules/plugin/epsg-postgresql/target/pmd.xml
Creating annotations for /home/runner/work/geotools/geotools/modules/plugin/epsg-wkt/target/pmd.xml
Creating annotations for /home/runner/work/geotools/geotools/modules/plugin/iau-wkt/target/pmd.xml
Error: HttpError: Resource not accessible by integration
```

I've checked the actions permissions in both GeoTools and GeoServer, they look exactly the same. Do maybe you have experience with this kind of issue?

**Comment by aaime** [comment]
Almost there. Looks like there are legit failures in GWC and possibly app-schema.

**Comment by mprins** [comment]
yep I broke something along the way, will need to find some time to run a bisect to restore behaviour as I haven't been able to pinpoint my screw-up, it's gonna be mid-august though.

**Comment by aaime** [comment]
Merged with main and did some more cleanups. Still failing on GWC, but fixed the failure on app-schema.

**Comment by aaime** [comment]
And it's green... I'd say we merge ASAP

**Comment by mprins** [comment]
@aaime Thanks for picking this up! Please merge when you're ready

**Pull request merged**
