### PR TITLE
[GEOS-9340] Extra metadata for layers groups (enabled and advertised)

### PR DESCRIPTION
**Pull request by nmco**
Reopening of: https://github.com/geoserver/geoserver/pull/3778

### CODE REVIEW

**Comment by nmco** [comment]
That's actually a very good point @aaime, not sure how we forgot about that 😨!

**Comment by nmco** [comment]
Documentation updated @aaime, let us know if something else is missing, thank you.

**Comment by aaime** [comment]
Thanks, looks good to me.

**Comment by aaime** [comment]
I see the windows build failed with:

```
[00:06:06] [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.787 s <<< FAILURE! - in org.geoserver.wfs.remote.v2_0.WfsRemoteStoreTest
[00:06:06] [ERROR] testAddRemoteWfsLayerSpecialChars(org.geoserver.wfs.remote.v2_0.WfsRemoteStoreTest)  Time elapsed: 1.505 s  <<< FAILURE!
[00:06:06] java.lang.AssertionError: 
[00:06:06] 
[00:06:06] Expected: is <200>
[00:06:06]      but: was <400>
[00:06:06] 	at org.geoserver.wfs.remote.v2_0.WfsRemoteStoreTest.testAddRemoteWfsLayerSpecialChars(WfsRemoteStoreTest.java:182)
```

Seems like a failure that @taba90 fixed in another PR. @taba90 can you confirm?

**Comment by taba90** [comment]
Yes I'm fixing this

**Comment by nmco** [comment]
Can fix those conflicts @taba90 ?

**Comment by nmco** [comment]
Thx @taba90 !

**Pull request merged**
