### PR TITLE
Add osgeo dependency to implementing wps tutorial

### PR DESCRIPTION
**Pull request by lubojr**
Added osgeo dependency to fix Maven build. 
These were not downloaded before: 
*The following artifacts could not be resolved: jgridshift:jgridshift:jar:1.0, javax.media:jai_imageio:jar:1.1, javax.media:jai_codec:jar:1.1.3, javax.media:jai_core:jar:1.1.3: Could not find artifact jgridshift:jgridshift:jar:1.0 in boundless*

geoserver-users mail list message linked to this:
https://sourceforge.net/p/geoserver/mailman/message/36360921/

### CODE REVIEW

**Comment by lubojr** [comment]
I think it is not required either for osgeo or boundlessgeo actually, because it went through without both having snapshots = true. Should I remove it then?

**Comment by aaime** [comment]
Probably best to remove them

**Comment by Gnafu** [comment]
Since osgeo is already redirecting to https I suggest to use that instead of plain http

**Comment by aaime** [comment]
@Gnafu if I follow http://download.osgeo.org/webdav/geotools/ with the browser I'm getting no redirection, but both http and https seem to work.

**Comment by aaime** [comment]
Doh weird... now it does... maybe I had a cached page.

**Comment by Gnafu** [comment]
With curl the server does not redirect. Maybe its a FF/Chrome feature: once you reach a resource with https, they use it for http links automatically.

**Comment by lubojr** [comment]
Changed to https :)

**Comment by aaime** [comment]
Thanks!

**Pull request merged**
