### PR TITLE
GEOS-6986: Extended namespace validation for WFS-T replace

### PR DESCRIPTION
**Pull request by awaterme**
Same handling for WFS-T Insert and Replace.

### CODE REVIEW

**Comment by awaterme** [comment]
BTW: The entire class has no test cases, AFAIK, so I have not created one. Verified manually.

**Comment by aaime** [comment]
There used to be a time when GeoServer had no tests. Now we don't accept changes without one :-)

**Comment by awaterme** [comment]
Makes sense, I have created test cases.

**Comment by awaterme** [comment]
see https://osgeo-org.atlassian.net/browse/GEOS-6986

**Pull request merged**
