### PR TITLE
[GEOS-10682] GeoFence: data access control in WPS calls

### PR DESCRIPTION
**Pull request by etj**
[GEOS-10682](https://osgeo-org.atlassian.net/browse/GEOS-10682)

**WIP**

This PR includes also:
- https://github.com/geoserver/geoserver/pull/6207

It needs:
- https://github.com/geoserver/geoserver/pull/6215
- https://github.com/geoserver/geofence/pull/227

Changes in this PR:
- Add a new maven module repo `src/extensions/geofence`, moving the existing `geofence` and `geofence-server` under it
- Add a new maven module `src/extensions/geofence/geofence-wps`; since both `geofence` and `wps` are optional extensions, `geofence-wps` is a bridge module that allows geofence to get info created inside the wps module.
- Add the WPS checks for process+data
- Handles the new field `subfield` (https://github.com/geoserver/geofence/pull/227)
  - filtering
  - rest
  - wicket
- Some refactoring of util classes/methods
- Fixes some requests by replacing ANY with DEFAULT

### TODO

- [x] Fix some tests in geofence-server (@taba90 )
- [x] Complete the merging of `AccessInfo`
- [x] Add wps specific tests
- [x] Fix the assembly files since the modules have been moved one level deeper
- [x] Documentation

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by etj** [comment]
PR almost complete.
At the moment it can be run using https://github.com/geoserver/geofence/pull/227

Next steps:
- Create branch 3.6.x on GeoFence, merge geoserver/geofence#227 and release GeoFence 3.6.0.
- Change `gf.version` to 3.6.0.

**Comment by etj** [comment]
QA errors caused by a new @deprecate annotation on a method that will be removed in future release.

**Review by taba90 — APPROVED** [review]
Looks good to me. I've tested this manually and seems to work well.
Zip packaging seems to be fine too.

**Comment by aaime** [comment]
Ton of change but all located in the GeoFence modules, manually tested, going in.

**Pull request merged**
