### PR TITLE
[GEOS-4986] Removed order parser for virtualtable object (json/xml)

### PR DESCRIPTION
**Pull request by cippino**
This is a fix for:

* https://osgeo-org.atlassian.net/browse/GEOS-4986
* https://github.com/geosolutions-it/geoserver/issues/90

### CODE REVIEW

**Comment by aaime** [comment]
Please only refer to official GeoServer reports (https://osgeo-org.atlassian.net/projects/GEOS) , and always add a test to your pull requests

**Comment by cippino** [comment]
There is already a test for the parser I modified, so I think it would be not necessary.

**Comment by aaime** [comment]
No, it is necessary. There must be a test that fails without your patch, and succeeds with it. 
No test, no merge, project rules.

**Comment by cippino** [comment]
Ok, I'll procede adding that.

**Comment by aaime** [comment]
And oh, the pull request must be against the master branch (that's were we have Travis building and checking the pull requests). You can eventually backport it later if you want to

**Comment by jodygarnett** [comment]
Grinding through, this one is still waiting on a test case by the looks of things

**Comment by aaime** [comment]
@jodygarnett it's also done against the wrong branch. @cippino will you have time to fix the pull request?

**Comment by cippino** [comment]
Hi,
the fix was made on branch 2.6.x because I need to replace a geoserver with that version. I can't do that with 2.8.x. So this is the reason, it's not a fault. 
In the patch, I fix only a small section of the xml, so it not solve completly the issue, an my effort for this job is finished. In semptember I will have a week to complete the job (moving the patch on master too). If you can wait, I will very happy to make a complete patch.

**Comment by aaime** [comment]
Yep, we can wait, no problem :-)

**Comment by jodygarnett** [comment]
I note that the last 2.6.x release is scheduled to go out today ... but  has been delayed for a security fix. Please keep this in mind @cippino.

Do I understand that master is not affected by this bug?

**Comment by aaime** [comment]
Hi @cippino, how are things going? Are you working on the pull request update?

**Comment by cippino** [comment]
I still working on it. I planend to work on it last week, but I got a problem with internet connection. 
However, I think that is better close this pull request, because it is not on master branch. I'll try to find time next week.

**Comment by aaime** [comment]
Hi @cippino , any news? This is a good fix, I'd hate to lose it :-)

**Comment by aaime** [comment]
Hi @cippino, it's me again. Any chance we'll get this work completed? :-)

**Comment by cippino** [comment]
Hi, 
i'm working on it. I suppose to complete in 4/5 hours.  
I'll close this pull request, and make a new one.

**Comment by aaime** [comment]
Hi @cippino , this patch seems to have caused this regression: https://osgeo-org.atlassian.net/browse/GEOS-7400
Before your change the code was able to handle multiple geometry columns, now it just handles the last one found.

**Pull request closed without merging**
