### PR TITLE
[GEOS-6883] Improvements to app schema integration tests

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOS-6883](https://osgeo-org.atlassian.net/browse/GEOS-6883) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

I have run into challenges running app-schema tests locally, noticing they do not response to `online` profile, and instead require `app-schema-online-test` profile.

* [GEOS-6883](https://osgeo-org.atlassian.net/browse/GEOS-6883) app-schema online tests fail without test fixtures
  
  Profiles added to check for expected test fixture, only running tests if fixture is available, and skipping tests if not provided. With this change we could probably remove the `app-schema-online-test` profile as unnecessary?

* [GEOS-11465](https://osgeo-org.atlassian.net/browse/GEOS-11465) Update app-schema integration tests for PostGIS 2.1
  
  Update dependency used to fetch  Postgis_Data_ref_set.sql script used to establish sample data for integration tests.

* https://github.com/geotools/geotools/pull/4841
  
  Used to publish `refdataset-1.0` artifact, with version 1.0.8 updating Postgis_Data_ref_set.sql with fixes for more modern PostGIS releases. Apparently this last worked unaltered in PostGIS 2.1.
  
  When this is merged I will *deploy* this artifact allowing this PR to run without error.

These are improvements only, with these changes ``mvn clean install -Papp-schema-online-test -ntp -fae`` still has known failures (which I will not be fixing as my goal was the Postgis tests):
```
[INFO] Application Schema Support ......................... SUCCESS [  1.400 s]
[INFO] Application Schema Module .......................... SUCCESS [  2.872 s]
[INFO] Application Schema Integration Test ................ FAILURE [02:07 min]
[INFO] Sample DataAccess Integration Test ................. SUCCESS [  3.926 s]
[INFO] Application Schema Integration Online Test with Oracle Database SUCCESS [  0.339 s]
[INFO] Application Schema Integration Online Test with Postgis Database SUCCESS [02:40 min]
[INFO] Application Schema MongoDB Integration Test ........ SUCCESS [  0.118 s]
[INFO] Application Schema Solr Integration Test ........... SUCCESS [  0.146 s]
[INFO] Application Schema Indexes Integration Test ........ SUCCESS [  1.357 s]
[INFO] Application Schema Geopackage Integration Test ..... FAILURE [ 10.459 s]
```

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by jodygarnett** [comment]
I am marking this as ready for review as it *is* an improvement and has accomplished my goal of running the postgis tests.

**Comment by aaime** [comment]
Closing and re-opening to retrigger all builds.

**Comment by jodygarnett** [comment]
@jodygarnett  read above about geotools PR:

> When this is merged I will deploy this artifact allowing this PR to run without error.

**Comment by nmco** [comment]
Looks good, GeoTools PR merged, opening and closing to trigger the build.

**Comment by jodygarnett** [comment]
We have to deploy ``refdataset-1.0`` now that GEOT-7616 is merged before this can be expected to work.

**Comment by jodygarnett** [comment]
Had to update the instructions (https://github.com/geotools/geotools/pull/4892) but reddataset-1.0 v 1.0.8 is now published.

Restarting the jobs to see if it works

**Pull request merged**
