### PR TITLE
[GEOS-8430] Cache small amount of features in memory to avoid repeated data scans in GetFeature requests

### PR DESCRIPTION
**Pull request by aaime**
https://osgeo-org.atlassian.net/browse/GEOS-8430

Replaces #1355
Rebased the pull request on current master to make sure everything builds against today's code, and:

- Improve use of generic and use try with resources when possible
- Some fixes to docs, cut down on advertisement and augment code behavior description
- Made the class public (sigh) because subclasses of GetFeature in GeoServer extensions might actually need it (since the code is right in the middle of an extension point)
- Added test to make sure GetFeature works with both caching on and off
- Created a GeoServer ticket and made the commits refer to it

### CODE REVIEW

**Comment by aaime** [comment]
@ahuarte47 can you review?

**Comment by ahuarte47** [comment]
@aaime, it is right for me, thank you very much for your review and improvements!

**Comment by aaime** [comment]
@ianturton @jodygarnett @bencaradocdavies opinions?

**Comment by aaime** [comment]
@ianturton given how narrow this is and the mounting charge against the shapefile format (see http://switchfromshapefile.org/ ) I'd rather keep it in WFS for the time being. We can always move the file to GeoTools later.

**Comment by bencaradocdavies** [comment]
@aaime no objection from me. This is small increase in code base and thus complexity, but if the performance increase is noticeable, it may be worthwhile.

**Comment by ahuarte47** [comment]
Thanks to all!

**Pull request merged**
