### PR TITLE
[GEOS-10556] Cleanup of CSS, HTML DOM structure en rewrite of some CSS - New PR

### PR DESCRIPTION
**Pull request by MichelGabriel**
[GEOS-10556](https://osgeo-org.atlassian.net/browse/GEOS-10556)

Replacing PR https://github.com/geoserver/geoserver/pull/5984

This is a new PR with the same code changes (cherry picked) as the PR it is replacing. The new PR has been made because the old one couldn't be rebased properly.

The [old PR](https://github.com/geoserver/geoserver/pull/5984) contains all the comments that were made.

Link to proposal: https://github.com/geoserver/geoserver/wiki/GSIP-213

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
Had a quick go over the top level pages (and layers and some stores). Most look good, found the following issues:
* The WMS page does not load

```
org.apache.wicket.WicketRuntimeException: The component(s) below failed to render. Possible reasons could be that:
	1) you have added a component in code but forgot to reference it in the markup (thus the component will never be rendered),
	2) if your components were added in a parent container then make sure the markup for the child container includes them in <wicket:extend>.

1. [CheckBox [Component id = autoEscapeTemplateValues, page = org.geoserver.wms.web.WMSAdminPage, path = form:autoEscapeTemplateValues, type = org.apache.wicket.markup.html.form.CheckBox, isVisible = true, isVersioned = false]]

	at org.apache.wicket.Page.checkRendering(Page.java:666)
	at org.apache.wicket.Page.onAfterRender(Page.java:821)
	at org.apache.wicket.markup.html.WebPage.onAfterRender(WebPage.java:224)
	at org.apache.wicket.Component.afterRender(Component.java:919)
	at org.apache.wicket.Component.render(Component.java:2343)
	at org.apache.wicket.Page.renderPage(Page.java:1018)
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
```

* The WFS page does not load:

```
Tag  '<wicket:extend>' (line 3, column 3) has a mismatched close tag at  '</li>' (line 67, column 3)
 MarkupStream: [markup = file:/home/aaime/devel/git-gs/src/web/wfs/target/classes/org/geoserver/wfs/web/WFSAdminPage.html
<html xmlns:wicket="http://wicket.apache.org/">
<head></head><body>
  <wicket:extend>
    <fieldset>
```

* The Filter chain editor page (for the "web" filter chain, but also for ``rest`` , ``gwc`` and ``default``) does not load:

```
ag  '<fieldset class="border-0">' (line 29, column 19) has a mismatched close tag at  '</ul>' (line 33, column 5)
 MarkupStream: [markup = file:/home/aaime/devel/git-gs/src/web/security/core/target/classes/org/geoserver/security/web/auth/SecurityVariableFilterChainPage.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:wicket="http://wicket.apache.org/">
```

* In the style editor, when moving to full screen, and switching to a layer with many attributes, the pane does not have a scroll (but to be honest, I believe it was like that already, feel free to ignore):

image

**Comment by MichelGabriel** [comment]
@aaime Thank you for the review, I'm going to fix the errors

**Comment by MichelGabriel** [comment]
I pushed some changes/fixes for the bugs mentioned above by @aaime

**Comment by jodygarnett** [comment]
So last time I went through all the screens; is that the plan again this time?

**Comment by MichelGabriel** [comment]
@jodygarnett it should be the same as before, I didn't add new things

**Comment by aaime** [comment]
Did one more round, couldn't find issues. So merging, before it bit-rots again :rofl: 
Thanks @MichelGabriel !

**Comment by jodygarnett** [comment]
Thanks @MichelGabriel (and @aaime for review)

**Pull request merged**
