### PR TITLE
[GEOS-11275] Wicket 9 upgrade

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOS-11275](https://osgeo-org.atlassian.net/browse/GEOS-11275) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

This is continuation of focused on making a milestone docker release for A/B testing.

* [x] take brad fork wicket9 → shared wicket9 branch
* [x] relax dialog deprecation: GSModalWindow has SuppressWarnings applied (so done in one spot)
* [x] relax CSP restrictions: use system property

   * reporting is now the default, use system property use `org.geoserver.web.csp.strict=true` to enable blocking

* [x] make a milestone release → results in a docker image

   * extensions can be tested using docker

   * community modules can be tested if we manually release? may have to upload to SF extensions folder for testing

* [x] ask for help doing the A/B testing

   * @petersmythe and others were able to some testing identifying problems with layer preview and style editor

   * The results of A/B testing are collected in the following spreadsheet: [Wicket Test Plan](https://docs.google.com/spreadsheets/d/1pQmncG4zxpgJnHxeI4myFfOBD17U2CIMcy59II4XAfo/edit?usp=sharing)

* These issues have been resolved after the 2.26.0 release, so main branch is clear to merge this work

Thanks to:

* @bradh for initial wicket 8 work https://github.com/geoserver/geoserver/pull/7154
  Please see this PR for prior history (and videos)
* @davidblasby for looking ahead to wicket 10 dialog replacement https://github.com/geoserver/geoserver/pull/7871

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by jodygarnett** [comment]
@petersmythe so the next step is to announce this PR and ask for help.
I think we can do a "normal" release announcement, but the text will describe what assistance we are asking for.

Can you look at the test plan and can determine an appropriate way to figure out how to "test everything" :)

**Comment by petersmythe** [comment]
I have started a blog post here: https://github.com/geoserver/geoserver.github.io/pull/214, I will add various parameters as examples to make it easy to use.

**Comment by jodygarnett** [comment]
No issues have been found thus far in testing (as CSP checks have been reduced to warnings).
Even so this is being held until after the 2.26.0 release.

**Comment by jodygarnett** [comment]
From testing https://matrix.to/#/#geoserver/wicket-9-upgrade:gitter.im

>  the "All Formats" option in the "Layer Preview" section is not functioning as expected.

It is unclear if it is just a CSP warning; or if there is something broken with the drop down?

**Comment by jodygarnett** [comment]
I am taking this out of draft and intend to merge to the active 2.27-SNAPSHOT `main` branch. 
This should allow lots of small PRs resolving individual CSP warnings...

**Comment by jodygarnett** [comment]
@davidblasby and myself are going to fix the one outstanding issue reported by @petersmythe and @MiladRafiei:

> Noticed that the "All Formats" option in the "Layer Preview" section is not functioning as expected.

Thanks for testing!

**Comment by jodygarnett** [comment]
All formats fixed, thanks @davidblasby https://github.com/geoserver/geoserver/pull/7923

**Comment by jodygarnett** [comment]
I notice two things in the testing results:

1. blocker: testing spreadsheet says style editor save and apply do not work as expected - they actually do not work at all
1. minor: layer editor and style editor have : save / apply / abandon (rather than save / apply / cancel). Likely a translation?

**Comment by jodygarnett** [comment]
@petersmythe and @davidblasby when this passes I am going to merge this PR.

@petersmythe is it at all useful to share https://github.com/geoserver/geoserver.github.io/pull/214 with a note to test nightly builds?

**Comment by sikeoka** [comment]
FYI, I downloaded a snapshot war today and it is setting both the `Content-Security-Policy` and `Content-Security-Policy-Report-Only` headers and they are not the same value. The report header drops the default-src directive and adds `data:` to the img-src directive.
```
Content-Security-Policy:
default-src 'none'; script-src 'strict-dynamic' 'nonce-_c7GijjotQV8FLQAUvxYpg_A'; style-src 'nonce-_c7GijjotQV8FLQAUvxYpg_A'; img-src 'self'; connect-src 'self'; font-src 'self'; manifest-src 'self'; child-src 'self'; base-uri 'self'; frame-src 'self'
Content-Security-Policy-Report-Only:
script-src 'strict-dynamic' 'nonce-_c7GijjotQV8FLQAUvxYpg_A'; style-src 'nonce-_c7GijjotQV8FLQAUvxYpg_A'; img-src 'self' data:; connect-src 'self'; font-src 'self'; manifest-src 'self'; child-src 'self'; base-uri 'self'; frame-src 'self'
```

**Pull request merged**
