### PR TITLE
GEOS-7298, remove list items associated with removed parameter filters

### PR DESCRIPTION
**Pull request by smithkm**
https://osgeo-org.atlassian.net/browse/GEOS-7298

### CODE REVIEW

**Comment by aaime** [comment]
The test failed in the JDK8 build:

Tests run: 9, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 3.113 sec <<< FAILURE!
testRemoveFirstParamFilter(org.geoserver.gwc.web.layer.LayerCacheOptionsTabPanelTest)  Time elapsed: 75 sec  <<< FAILURE!

**Comment by smithkm** [comment]
Yes, there's also another problem when deleting from more than 2 filters I'm looking into.

**Comment by smithkm** [comment]
So far the best result I've gotten is that adding filters continues to work normally via ajax with changes to other filters preserved.  I can get removing filters to work without throwing errors, but it doesn't use ajax resulting in a page refresh, returning to the top of the page and any changes made to the other filters are lost.

**Comment by aaime** [comment]
This one has been around for a while, any update?

**Comment by smithkm** [comment]
Ended up assigned to other things and haven't had a chance to figure out how to make Wicket do what I want. This might be best to leave until the Wicket upgrade sprint.  A newer Wicket might provide more/better options.

**Comment by smithkm** [comment]
I think @NielsCharlier fixed this during the Wicket update.

**Pull request closed without merging**
