### PR TITLE
[GEOS-10303] Upgrade to jackson 2.13.0

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOS-10303](https://osgeo-org.atlassian.net/browse/GEOS-10303)

This is the last pre-jakarta release and may address some classpath woodstax issues

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue GEOS-10303
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by jodygarnett** [comment]
Well that did not work

**Comment by aaime** [comment]
I saw the other PR with Woodstock upgrade going in. So should this one be closed?

**Comment by jodygarnett** [comment]
Need to check in on this one again

**Comment by aaime** [comment]
@jodygarnett I've tried switching to 2.13.2 on the current main branch, seems to be building fine!

**Comment by jodygarnett** [comment]
Go for it!

**Comment by aaime** [comment]
Closing, superceded by https://github.com/geoserver/geoserver/pull/5747

**Pull request closed without merging**
