### PR TITLE
Use CoverageResourceListener to call CoverageCleanerCallback

### PR DESCRIPTION
**Pull request by jodygarnett**
Allows CoverageResourceListener to clean up after any coverages that failed to load (due to invalid crop).

See https://jira.codehaus.org/browse/GEOS-6921

### CODE REVIEW

**Comment by jodygarnett** [comment]
@aaime can I bump this for review?

**Comment by aaime** [comment]
Jody, I already used more time than I was allowed to for the security discussion... cannot promise I'll have this reviewed today.

**Comment by jodygarnett** [comment]
Yeah I saw that, not sure I cared about comments and code clarity on a release blocker.

Are you content if I ask @smithkm to review. The design/approach here is as we discussed in the code sprint. I manually wired things up and added a test case.

There was one oddness: clean can get called multiple times (one for each coverage parameter) but I was cool with that.

**Comment by aaime** [comment]
Yep, that works for me. Not sure we are under a fire drill on this one
however, the release is blocked on the security issue anyways. But yep,
move on with Kevin, I'm happy with him reviewing the request.

On Wed, Mar 18, 2015 at 5:51 PM, Jody Garnett <notifications@github.com>
wrote:

> Yeah I saw that, not sure I cared about comments and code clarity on a
> release blocker.
>
> Are you content if I ask @smithkm <https://github.com/smithkm> to review.
> The design/approach here is as we discussed in the code sprint. I manually
> wired things up and added a test case.
>
> There was one oddness: clean can get called multiple times (one for each
> coverage parameter) but I was cool with that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoserver/geoserver/pull/975#issuecomment-83055410>.
>



-- 
==
GeoServer Professional Services from the experts! Visit
http://goo.gl/NWWaa2 for more information.
==

Ing. Andrea Aime
@geowolf
Technical Lead

GeoSolutions S.A.S.
Via Poggio alle Viti 1187
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax: +39 0584 1660272
mob: +39  339 8844549

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

-------------------------------------------------------

**Comment by smithkm** [comment]
Looks good to me.

**Pull request merged**
