### PR TITLE
Make SecuredGridCoverage2DReader using a cached Crop operation instance

### PR DESCRIPTION
**Pull request by afabiani**
Related to JIRA GEOS-7427

### CODE REVIEW

**Comment by aaime** [comment]
One spurious change in importer, no copyright header update. I guess this one is more of a performance optimization and thus cannot be actually "tested" right?

**Comment by afabiani** [comment]
Yep, right.

Spurious change reverted!

**Comment by aaime** [comment]
Copyright header not updated though :)

**Comment by aaime** [comment]
Manually merged and backported to 2.8.x

**Pull request closed without merging**
