### PR TITLE
[GEOS-8957] Clean up remaining doc warnings, switch config.

### PR DESCRIPTION
**Pull request by bradh**

### CODE REVIEW

**Comment by bradh** [comment]
I don't think we're losing anything. Its already not highlighting. See http://docs.geoserver.org/latest/en/user/styling/css/cookbook/point.html#simple-point as an example.

I didn't check other highlighters though. Can take a look tomorrow.

**Comment by aaime** [comment]
Doh, you're right!

**Comment by bradh** [comment]
less and sass didn't work, but it looks like scss can give us some help.

image

The `:nth_image` part isn't great, but its probably OK overall.

**Comment by aaime** [comment]
@bradh I think it looks good (and much better better than what we have now), +1

**Comment by bradh** [comment]
Will close this PR and submit off a rebased / clean branch.

**Pull request closed without merging**
