### PR TITLE
Boundsmap

### PR DESCRIPTION
**Pull request by LisetteDanebjer**
I have implemented a function using OpenLayers to ease the process of establishing bounds. This project was done as a part of an internship. This is my first contribution to GeoServer. Feedback is appreciated.

### CODE REVIEW

**Comment by simboss** [comment]
Is there an issue for this?

**Comment by bradh** [comment]
Per the detail comments, it would be better if this worked when there is no internet connectivity.

**Comment by aaime** [comment]
We probably also need a bit of documentation update

**Comment by bradh** [comment]
This is probably still a worthwhile change, but to finish it off we'd probably need a contributor agreement (so we can re-use the work already done). Do you have one submitted, or was one done by the company you interned for?

**Comment by ianturton** [comment]
@LisetteDanebjer can you complete a contributor agreement.

**Comment by jodygarnett** [comment]
See above this was an intern, we need a contribution agreement form their employeer

**Comment by bencaradocdavies** [comment]
@LisetteDanebjer this pull request has gone stale. We cannot accept this contribution with a contributor agreement. Please create a new PR when you have submitted a contributor agreement. This will attract attention and trigger a fresh Travis CI run.

**Pull request closed without merging**
