### PR TITLE
[GEOS-11608] Update Bouncy Castle Crypto package from bcprov-jdk15on:1.69 to bcprov-jdk18on:1.79

### PR DESCRIPTION
**Pull request by mprins**
[GEOS-11608](https://osgeo-org.atlassian.net/browse/GEOS-11608) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

upgrade from Java 5 to Java 8 version and update to latest release

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
I think it's looking good? The failure on "Run CITE Tests / CITE (ogcapi-features10) (pull_request)" is unrelated and has been fixed, you can verify by rebasing this PR onto main.

**Comment by mprins** [comment]
There is a community module "gs-sec-oauth2-openid-connect" that has a dependency on the seemingly abandoned `org.springframework.security:spring-security-jwt:1.0.11.RELEASE` (dated 16-Oct-2019) which drags in `org.bouncycastle:bcprov-jdk15on`; I've fixed that using dependencyManagment, so all use of BCProv is now `org.bouncycastle:bcprov-jdk18on:1.79`
[dependency tree](https://github.com/user-attachments/files/17800104/deps.tree.log)

**Comment by aaime** [comment]
Ouch yeah, that module is still in use, need to figure out if the change affects it.

**Comment by mprins** [comment]
All oauth and oidc module tests pass locally after adding jupiter, but I don't have access to a oidc testing instance. 
AFAICT from documentation things should just work

**Pull request merged**
