### PR TITLE
[GEOS-11033] Take some care when updating bounds to protect against missing crs

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOS-11033](https://osgeo-org.atlassian.net/browse/GEOS-11033)

* [x] If bounds only includes crs, preserve original extent
* [x] if bounds only includes extent update, preserve original crs 

Scripts and code like importer and backup / restore that automate interaction with the catalog should be aware of this change.
 

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by jodygarnett** [comment]
This should be good to go :)

**Comment by jodygarnett** [comment]
Converting to draft as I am concerned that:
a) the the UI provides no ability to change missing crs; 
b) Change would prevent REST API users from publishing when they are unable to determine CRS? While they could use <crs>EPSG:404000</crs> that has not been defined as a requirement of ReferencedEnvelope

**Comment by GeoSander** [comment]
@jodygarnett I (also) doubt if this is a good idea. We probably should not introduce too much "smartness" into the REST API.

**Comment by jodygarnett** [comment]
This PR has been replaced by https://github.com/geoserver/geoserver/pull/6962

**Pull request closed without merging**
