### PR TITLE
There is error in ui Language.

### PR DESCRIPTION
**Pull request by emreozbek**
I'm using 2.10.1 version. I'm from Turkey. So It's installing tr language. But it is not working on turkish language. I am getting the following error. I'm not set language. When I installed 2.3.5 version, there was no problem. Because it version is english.  How you can help to me?

org.apache.wicket.WicketRuntimeException: Exception in rendering component: [Component id = filterMatch]
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2589)
	at org.apache.wicket.markup.html.WebComponent.onRender(WebComponent.java:60)
	at org.apache.wicket.Component.internalRender(Component.java:2380)
	at org.apache.wicket.Component.render(Component.java:2308)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1262)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1459)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1434)
	at org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:703)
	at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.renderAssociatedMarkup(AssociatedMarkupSourcingStrategy.java:77)
	at org.apache.wicket.markup.html.panel.PanelMarkupSourcingStrategy.onComponentTagBody(PanelMarkupSourcingStrategy.java:112)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2565)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1398)
	at org.apache.wicket.Component.internalRender(Component.java:2380)
	at org.apache.wicket.Component.render(Component.java:2308)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1262)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1459)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1434)
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1357)
	at org.apache.wicket.markup.html.form.Form.onComponentTagBody(Form.java:1705)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2565)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1398)
	at org.apache.wicket.Component.internalRender(Component.java:2380)
	at org.apache.wicket.Component.render(Component.java:2308)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1262)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1459)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1434)
	at org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:703)
	at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.renderAssociatedMarkup(AssociatedMarkupSourcingStrategy.java:77)
	at org.apache.wicket.markup.html.panel.PanelMarkupSourcingStrategy.onComponentTagBody(PanelMarkupSourcingStrategy.java:112)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2565)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1398)
	at org.apache.wicket.Component.internalRender(Component.java:2380)
	at org.apache.wicket.Component.render(Component.java:2308)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1262)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1459)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1434)
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1357)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2565)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1398)
	at org.apache.wicket.Component.internalRender(Component.java:2380)
	at org.apache.wicket.Component.render(Component.java:2308)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1262)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1459)
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1434)
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1357)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2565)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1398)
	at org.apache.wicket.Component.internalRender(Component.java:2380)
	at org.apache.wicket.Component.render(Component.java:2308)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1262)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1459)
	at org.apache.wicket.Page.onRender(Page.java:879)
	at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:141)
	at org.apache.wicket.Component.internalRender(Component.java:2380)
	at org.apache.wicket.Component.render(Component.java:2308)
	at org.apache.wicket.Page.renderPage(Page.java:1018)
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:865)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
	at org.apache.wicket.protocol.http.WicketServlet.doGet(WicketServlet.java:137)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:158)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:75)
	at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:71)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:46)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:50)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:54)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.geoserver.security.filter.GeoServerUserNamePasswordAuthenticationFilter.doFilter(GeoServerUserNamePasswordAuthenticationFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:157)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:53)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:152)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:87)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:42)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: An error occurred while getting the model object for Component: [Component id = filterMatch, page = org.geoserver.web.demo.MapPreviewPage, path = 3:table:filterForm:navigatorTop:filterMatch.Label, isVisible = true, isVersioned = true, markup = [markup = jar:file:/D:/GeoServer-2.10.1/webapps/geoserver/WEB-INF/lib/gs-web-core-2.10.1.jar!/org/geoserver/web/wicket/GeoServerTablePanel$Pager.html
<span wicket:id="filterMatch">Matched xxx out of yyy</span>, index = 0, current =  '<span wicket:id="filterMatch">' (line 0, column 0)]]
	at org.apache.wicket.Component.getDefaultModelObject(Component.java:1631)
	at org.apache.wicket.Component.getDefaultModelObjectAsString(Component.java:1654)
	at org.apache.wicket.markup.html.basic.Label.onComponentTagBody(Label.java:115)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2565)
	... 159 more
Caused by: java.lang.IllegalArgumentException: Unmatched braces in the pattern.
	at java.text.MessageFormat.applyPattern(Unknown Source)
	at java.text.MessageFormat.<init>(Unknown Source)
	at org.apache.wicket.model.StringResourceModel.getString(StringResourceModel.java:481)
	at org.apache.wicket.model.StringResourceModel.getString(StringResourceModel.java:424)
	at org.apache.wicket.model.StringResourceModel.load(StringResourceModel.java:617)
	at org.apache.wicket.model.StringResourceModel.load(StringResourceModel.java:199)
	at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:134)
	at org.apache.wicket.model.StringResourceModel$AssignmentWrapper.load(StringResourceModel.java:267)
	at org.apache.wicket.model.StringResourceModel$AssignmentWrapper.load(StringResourceModel.java:226)
	at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:134)
	at org.apache.wicket.Component.getDefaultModelObject(Component.java:1626)
	... 163 more

### CODE REVIEW

**Comment by mprins** [comment]
@emreozbek What is the point of this pull request?

**Comment by aaime** [comment]
I believe it's a misguided attempt to get help. The Turkish translation has issues and it's causing the UI to fail, there are already 2 tickets about it the tracker, but no developer that can read that language I'm afraid.

**Comment by emreozbek** [comment]
@mprins I'm sorry. I'm new. @aaime Where Can I make standart language is english?

**Comment by aaime** [comment]
@emreozbek there is no easy way to do that, we had a feature request to change the UI language open for something like 10 years and nobody implemented it, it was eventually closed. Right now you'd have to switch the browser default language to english for GeoServer to follow, there are plugins for browsers allowing to do that. 
All I can offer right now, if we don't find anyone to fix the Turkish translation, is to remove it.

**Pull request closed without merging**
