### PR TITLE
[GEOS-11161] Address build warnings for running unit tests

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOS-11161](https://osgeo-org.atlassian.net/browse/GEOS-11161) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

Address some build warnings associated with running tests, non-functional change.

- [x] community modules with no tests have a warning
- [x] surefire uses maven java, the parameters source and target are not used at all :) 

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
Does that skipIfEmpty prevent the building of the test jar maybe?

```
Error: 2,344 [ERROR] Failed to execute goal on project gs-sec-oauth2-google: Could not resolve dependencies for project org.geoserver.community:gs-sec-oauth2-google:jar:2.25-SNAPSHOT: Could not find artifact org.geoserver.community.security:gs-sec-oauth2-web:jar:tests:2.25-SNAPSHOT in osgeo-snapshots (https://repo.osgeo.org/repository/snapshot/) -> [Help 1]
Error: 2,344 [ERROR] Failed to execute goal on project gs-sec-oauth2-github: Could not resolve dependencies for project org.geoserver.community:gs-sec-oauth2-github:jar:2.25-SNAPSHOT: org.geoserver.community.security:gs-sec-oauth2-web:jar:tests:2.25-SNAPSHOT was not found in https://repo.osgeo.org/repository/snapshot/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of osgeo-snapshots has elapsed or updates are forced -> [Help 1]
Error: 2,345 [ERROR] Failed to execute goal on project gs-sec-oauth2-geonode: Could not resolve dependencies for project org.geoserver.community:gs-sec-oauth2-geonode:jar:2.25-SNAPSHOT: org.geoserver.community.security:gs-sec-oauth2-web:jar:tests:2.25-SNAPSHOT was not found in https://repo.osgeo.org/repository/snapshot/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of osgeo-snapshots has elapsed or updates are forced -> [Help 1]
Error: 2,345 [ERROR] Failed to execute goal on project gs-sec-oauth2-openid-connect-core: Could not resolve dependencies for project org.geoserver.community.security:gs-sec-oauth2-openid-connect-core:jar:2.25-SNAPSHOT: org.geoserver.community.security:gs-sec-oauth2-web:jar:tests:2.25-SNAPSHOT was not found in https://repo.osgeo.org/repository/snapshot/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of osgeo-snapshots has elapsed or updates are forced -> [Help 1]
Error: 2,346 [ERROR] Failed to execute goal on project gs-sec-keycloak: Could not resolve dependencies for project org.geoserver.community:gs-sec-keycloak:jar:2.25-SNAPSHOT: org.geoserver.community.security:gs-sec-oauth2-web:jar:tests:2.25-SNAPSHOT was not found in https://repo.osgeo.org/repository/snapshot/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of osgeo-snapshots has elapsed or updates are forced -> [Help 1]
```

**Comment by aaime** [comment]
> > Does that skipIfEmpty prevent the building of the test jar maybe?
> 
> If so it would be an empty test jar ...

Then you'll have to change the build dependencies so that the build is not looking for the jars not being built (that's my understanding of the build error above, at least).

**Comment by jodygarnett** [comment]
oh wow, that means that the osgeo repo is getting uploaded with empty test jars, which would actually have content if they were built locally.

That is a surprisingly deep trouble to find.

**Comment by jodygarnett** [comment]
I cannot reproduce this issue locally for some reason; isolating the test dependencies in a profile - does not work (tests were still compiling).

So it must of gotten them somehow; or an older copy lurking in local or remote repo.
```
  <profiles>
    <profile>
      <id>oauth2-test</id>
      <activation>
        <property>
          <name>!skipTests</name>
        </property>
      </activation>
      <!-- community test dependencies are only available when tests are being run -->
      <dependencies>
        <dependency>
          <groupId>org.geoserver.community.security</groupId>
          <artifactId>gs-sec-oauth2-core</artifactId>
          <version>${project.version}</version>
          <classifier>tests</classifier>
          <scope>test</scope>
        </dependency>

        <dependency>
          <groupId>org.geoserver.community.security</groupId>
          <artifactId>gs-sec-oauth2-web</artifactId>
          <version>${project.version}</version>
          <classifier>tests</classifier>
          <scope>test</scope>
        </dependency>
      </dependencies>
    </profile>
  </profiles>
```

**Comment by jodygarnett** [comment]
Turns out using profiles to selectively add test jar dependency based on skipTests ... was too complicated to live.

Allowing oath-web to generate an empty test jar worked ... but was stupid.

Removing the dependencies on an empty (or missing) test jar was the easiest approach that made the most sense.

**Review by aaime — APPROVED** [review]
Looks good, thanks!

**Comment by jodygarnett** [comment]
Thanks @aaime for reviewing.

**Pull request merged**
