### PR TITLE
Change to OAuth core to take token from header and parameter.

### PR DESCRIPTION
**Pull request by tlann**
Authorization header in the doFilter function and getPreAuthenticatedPrincipal.  Previosuly it was not getting token from header in the getPreAuthenticatedPrincipal function.  This is to get change into 2.14.x branch for future release of 2.14

### CODE REVIEW

**Comment by aaime** [comment]
Hi @tlann thanks for the PR. I believe that compared to master it's missing one call to getAccessTokenFromRequest in the getCacheKey method.

**Comment by tlann** [comment]
> Hi @tlann thanks for the PR. I believe that compared to master it's missing one call to getAccessTokenFromRequest in the getCacheKey method. Was that intentional?

Apologies.  Please see the updated PR.

**Comment by aaime** [comment]
Seems ok to me, @afabiani opinions?

**Comment by aaime** [comment]
PR merged, thanks @tlann for providing and @afabiani for reviewing :-)

**Pull request merged**
