### PR TITLE
Update user/group services documentation to include LDAP and apply consistent wording

### PR DESCRIPTION
**Pull request by petersmythe**
Please double check me that there are 3 built in types of user/group services.  The documentation just listed 2.

Then I changed the wording to `User group service` in 2 places in the code, to correct this inconsistency:
```
XML - Default user group service stored as XML
AuthKEY WebService Body Response - UserGroup Service from WebService Response Body
LDAP - A UserGroup service provider which sources its information from a LDAP directory
JDBC - User group service stored in database
```

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the `main` branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by petersmythe** [comment]
Sorry, I don't know how to squash these 3 commits into one using the Github web interface.

**Comment by sharkAndshark** [comment]
> Sorry, I don't know how to squash these 3 commits into one using the Github web interface.

maybe try git rebase -i HEAD~3...?

**Comment by mprins** [comment]
they can be squashed during merge; that is not a problem 
right now however the docs build fails, I assume bacause of these messages: https://github.com/geoserver/geoserver/pull/4834/checks?check_run_id=2057238607#step:5:5598

**Comment by petersmythe** [comment]
> > Sorry, I don't know how to squash these 3 commits into one using the Github web interface.
> 
> maybe try git rebase -i HEAD~3...?

Thanks, but I am not using the command line, I specified the Github web interface above.  But good to hear from Mark that it's not important.

**Comment by petersmythe** [comment]
> they can be squashed during merge; that is not a problem
> right now however the docs build fails, I assume bacause of these messages: https://github.com/geoserver/geoserver/pull/4834/checks?check_run_id=2057238607#step:5:5598

Apologies, I will take a look at this tomorrow.

**Comment by petersmythe** [comment]
TIL about Sphinx and labels!  And the importance of building even the smallest change on my local machine first.

**Pull request merged**
