### PR TITLE
[GEOS-7753] - Cannot update existing store configuration, GeoServer complains with a "store already exists" error

### PR DESCRIPTION
**Pull request by afabiani**
Make use of the correct ResourcePool "clone" methods everywhere

### CODE REVIEW

**Comment by aaime** [comment]
No tests, no party :-)

**Comment by afabiani** [comment]
Well, the tests for the ResourcePool clone methods are already there. The PR basically removes wrong custom methods used by web core in favor of ResourcePool ones, which are correct.

However I'm going to add some tests which explicitly checks for missing properties, simulating the   previous error. This would be useful for future updates.

**Comment by afabiani** [comment]
Tests added!

**Comment by aaime** [comment]
Awesome, merging. Will you backport to 2.9.x?

**Comment by afabiani** [comment]
Yep

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------

**Comment by afabiani** [comment]
Fix available here

https://github.com/geoserver/geoserver/pull/1858

I will backport it as soon as the PR has been merged

**Pull request merged**
