### PR TITLE
TestWfsPost - improve url validation

### PR DESCRIPTION
**Pull request by tbarsballe**

### CODE REVIEW

**Comment by tbarsballe** [comment]
Test failures should be fixed by https://github.com/geoserver/geoserver/pull/3545

**Comment by tbarsballe** [comment]
Appveyor failure appears to be an unrelated issue downloading artifacts for gs-wps-cluster-hazelcast, not really sure whats going on there

**Comment by aaime** [comment]
Remaining test failure should be fixed by a rebase (new scale read parameter in mosaic)

**Comment by tbarsballe** [comment]
Rebased against master, looks to be finally passing.

**Comment by aaime** [comment]
Looks good to me. Did you do interactive tests too?

**Comment by tbarsballe** [comment]
Yes, I did a bunch of manual tests. I'll merge + backport.

**Pull request merged**
