### PR TITLE
[GEOS-9243] Upgrade Jetty to 9.4.18.v20190429 version

### PR DESCRIPTION
**Pull request by fernandor777**
## Description

The purpose of this PR is to upgrade Jetty servlet container to 9.4.18.v20190429 version.

Issue:
https://osgeo-org.atlassian.net/browse/GEOS-9243

### CODE REVIEW

**Comment by tbarsballe** [comment]
Please [create a JIRA issue](https://osgeo-org.atlassian.net/projects/GEOS/issues) for this fix.
While the change is quite small, it is a version update, and a JIRA issue will ensure that the update is listed in the GeoServer Release notes (this is particularly relevant if you are intending to backport the fix).

Otherwise, the fix looks good to me.

**Comment by fernandor777** [comment]
Thanks for your advise, JIRA issue created and linked in the PR.

**Comment by aaime** [comment]
@fernandor777 the checklist contained that info, please don't edit it out :-D

**Comment by aaime** [comment]
Tried it out, GeoServer starts from Start.java, from "mvn jetty:run", but the bin assembly fails on startup with:

```
 bin/startup.sh 
GEOSERVER_HOME environment variable not found, using current 
directory.  If not set then running this script from other 
directories will not work in the future.
GEOSERVER DATA DIR is /home/aaime/devel/git-gs/src/target/release/geoserver-2.16-SNAPSHOT/data_dir
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/ManifestUtils
	at org.eclipse.jetty.start.StartArgs.<clinit>(StartArgs.java:69)
	at org.eclipse.jetty.start.Main.processCommandLine(Main.java:293)
	at org.eclipse.jetty.start.Main.main(Main.java:75)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.ManifestUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information
```

To generate the bin run something like the following (not fully tested):

```
mvn clean install -T1C -Prelease -DskipTests
mvn assembly:attached
cd target/release
unzip geoserver-2.16-SNAPSHOT-bin.zip
```

**Comment by fernandor777** [comment]
Seems like start.jar from maven repos is the problem, using distribution package one from jetty site fixes the problem.

**Comment by aaime** [comment]
Tried agai, works. Looks good, merging and having the bot generate backports.

**Comment by aaime** [comment]
@fernandor777 any chance you can perform the upgrades in GWC?

**Comment by fernandor777** [comment]
@aaime yes, GWC upgrade on the way.

**Pull request merged**
