### PR TITLE
[GEOS-11142] Add mime type mapping for yaml files

### PR DESCRIPTION
**Pull request by sikeoka**
[GEOS-11142](https://osgeo-org.atlassian.net/browse/GEOS-11142) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

This PR adds a mime type mapping for yaml files so that the Style Publisher will return a "Content-Type: text/plain" response header for YSLD styles instead of no Content-Type header.  There is no unit test since this is a web.xml change.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by sikeoka** [comment]
That mime type is relatively new and I didn't know it existed since I had set this on my end a long time ago but only recently saw a mention of this.  The point of this PR is to register ANY mime type to resolve a potential vulnerability with YSLD styles.  Interestingly the OGC API modules use application/x-yaml which may be better to be consistent throughout the GeoServer codebase.  I will test out all three formats and update this PR tomorrow.

**Comment by sikeoka** [comment]
I tested out the other mime types and the one advantage that text/plain has is that it still allows YSLD (and other .yaml) files to be rendered in a browser instead of forcing a download.  There are only a few cases where GeoServer uses the servlet mime type mappings so I don't see this as a big deal.  I'll let @jodygarnett decide on the mime type since he is also using the YSLD extension.

**Comment by aaime** [comment]
We already have cases where the respose is not readable by browsers, because OGC decided on odd mime types, e.g., WMS 1.1 Capabilities response, and GML 3.2 in any WFS version (which also means WFS 2.0 responses by default are downloaded rather than shown).

**Comment by mprins** [comment]
I'd prefer using the IANA registered string for compliance reasons, for the OGC API as well (`application/x-yaml` is listed as deprecated in the document I linked to)

Aside from that I don't see much value in having a browser render any yaml file as text, but that is just my 2&cent;

**Comment by sikeoka** [comment]
The application/yaml media type is actually still in the Draft stage so it probably shouldn't be used yet:
https://datatracker.ietf.org/doc/draft-ietf-httpapi-yaml-mediatypes/

I will change this to application/x-yaml.

**Comment by sikeoka** [comment]
I changed this back to text/plain and my opinion is to just merge this.  It can be changed later after an official YAML media type is added to Spring if someone complains about it.

**Review by jodygarnett — APPROVED** [review]
Excellent, is a backport desired for this change?

**Pull request merged**
