### PR TITLE
GEOS-9285 Escape roles in backend before using in frontend to fix XSS

### PR DESCRIPTION
**Pull request by 1Jesper1**
GEOS-9285 Escape roles in backend before using in frontend to fix XSS
It would be better to prevent the XSS in the frontend, if someone has an idea to do this, feel free to change this. For now I escape the roles in the backend.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [x] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by 1Jesper1** [comment]
Why do the builds fail?

**Comment by mprins** [comment]
not sure if related but: https://travis-ci.org/geoserver/geoserver/jobs/632476374#L6495-L6502

**Comment by aaime** [comment]
Might be one of the random test failures, re-kicked the builds.

**Comment by 1Jesper1** [comment]
Thanks @aaime but the AppVeyor build still fails

**Comment by 1Jesper1** [comment]
@aaime Could you rekick the AppVeyor build please?

**Comment by aaime** [comment]
I have checked a bit the docs, it seems that Wicket should be doing the escaping automatically for us... in any case, did you try calling setEscapeModelStrings on the TextArea field?

**Comment by aaime** [comment]
Also, this is the administration UI, one needs full admin rights to get there, it's not something open to the public. And roles are manually entered by the same administrator. What's the actual XSS risk?

**Comment by 1Jesper1** [comment]
@aaime Yes, I tried that, but it didn't seem to work.

**Comment by aaime** [comment]
Final note, the PR lacks tests, as such, it cannot be merged. I would also recommend checking that data gets properly un-escaped on the save side, confirming that it does not end up saving HTML escape codes in the security subsystem configuration.

Btw, forget about the Windows faiulres, we are, we are looking into getting a different Windows build server to see if it's more reliable. If that also fails, Windows tests will have to be dropped, we don't have anyone working on Windows anymore that would be willing to take on this (if you want to step up for it, or know someone that would, it would be great news indeed!).

**Comment by 1Jesper1** [comment]
@aaime XSS possibility to let another admin execute an action. I have changed the place of the html escaping to the RolesAutoCompletedBehavior file. I don't know how to create a test for this case, I need to mock the RolesAutoCompletedBehavior class and then invoke the GetChoices protected method.

**Comment by aaime** [comment]
Was this tested interactively? I checked out the branch, added a role called "a&b", and here is what shows up in the UI after completion:

image

Not what was intended, I presume?

**Comment by 1Jesper1** [comment]
@aaime This output already happened before my changes. I found the XSS.

**Comment by aaime** [comment]
Definitely not, without your change the auto-complete results in:

image

which is the expected result (if one names a role "a&b" that's the output I expect to see in the UI).

If you have an actual attack vector, could you share it with geoserver-security@lists.osgeo.org? Sorry , never received formal training regarding security and know close to nothing on client side development either, so would not know where to start looking at this myself.

**Comment by aaime** [comment]
Closing due to inactivity, tried to get some traction  the geoserver-security list for a repeatable test case, in order to prepare a fix that does not break role editing.

**Pull request closed without merging**
