### PR TITLE
Cascaded stored query docs

### PR DESCRIPTION
**Pull request by sampov2**
This pull request is for the documentation related to new cascaded stored queries feature. I'd love some feedback, thanks!

### CODE REVIEW

**Comment by jodygarnett** [comment]
Looks good, you will have to wait for the RC1 to get feedback from real users. Indeed sending an email to geoserver users asking for testing (and linking to the docs) is the way to go.

Other than that @bmmpxf is the contact point for GeoServer docs and may be in position to offer an initial review.

**Comment by bmmpxf** [comment]
Without being familiar with the feature in question, the content looks good. I do wonder if maybe this should be merged in with the External WFS section, considering how linked it appears to be, as opposed to sitting parallel to it. But you tell me.

**Comment by sampov2** [comment]
I was struggling with the choice of having the in the External WFS or not as well. The basic arguments are:
* It should be included with External WFS because it sits structurally / architecturally in the same category and shares the same data store configuration.
* Cascaded stored queries (CSQ) will probably be a rarely used feature, having it's documentation mixed in with a more common basic WFS cascading might muddle the waters for the reader.

It's a difficult choice. I favored having them separate based on visual appearance: the documentation styling seems to be geared towards concise pages and does not visualize hierarchies and structure clearly. It's a real possibility that the reader might confuse which parts only have only to do with CSQ's and which parts apply to external WFS's in general. As CSQ's is a rather exotic feature, I thought it's best to keep the External WFS concise and to the point.

Any thoughts?

**Comment by jodygarnett** [comment]
I would like this merged before RC1

**Comment by sampov2** [comment]
I'm still happy with my decision to have the documentation on a separate page. Do you @bmmpxf  have any further thoughts?

**Comment by bmmpxf** [comment]
Apologies for the delay. Yes, I think your reasoning is sound to keep things as-is. Thanks!

**Pull request merged**
