### PR TITLE
[GEOS-8746] Style editor - fullscreen / side by side

### PR DESCRIPTION
**Pull request by tbarsballe**
See https://osgeo-org.atlassian.net/browse/GEOS-8746

Extension of https://github.com/geoserver/geoserver/pull/2867, adding styling and JS to support responsive Editor and Map preview height.

### CODE REVIEW

**Comment by aaime** [comment]
Made a pull request against this one to add docs and a small visual tweak: https://github.com/tbarsballe/geoserver/pull/6

**Comment by tbarsballe** [comment]
Ok, this has a JIRA issue and docs now, should be good to merge.

Anything else we need here?

**Comment by aaime** [comment]
I believe we're good to go, build permitting :-)

**Comment by aaime** [comment]
Build green, good to merge.

**Pull request merged**
