### PR TITLE
[GEOS-10158] POST request -> j_spring_security_check is in http plain…

### PR DESCRIPTION
**Pull request by shadab-geo**
[GEOS-10158](https://osgeo-org.atlassian.net/browse/GEOS-10158)

Jira ticket: [GEOS-10158](https://osgeo-org.atlassian.net/browse/GEOS-10158)

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by dromagnoli** [comment]
I think there is no need to register the GeoServerFilter in web.xml. They are pluggable, being retrieved by a fixed filter.

Moreover, since Dispatcher is not being used anymore, It can be removed from the test.

**Comment by shadab-geo** [comment]
> I think there is no need to register the GeoServerFilter in web.xml. They are pluggable, being retrieved by a fixed filter.
> 
> Moreover, since Dispatcher is not being used anymore, It can be removed from the test.

Applied feedback

**Comment by dromagnoli** [comment]
looks good to me

**Comment by chrischjh** [comment]
Hi, when could this be released? thanks a lot

**Comment by bradjones1** [comment]
I hate commenting on closed PRs, however drawing attention to https://osgeo-org.atlassian.net/browse/GEOS-11108 which addresses the conundrum of not being able to log in to set a proxy URL with HTTPs, and GeoServer not respecting the reverse-proxy headers on a fresh install.

**Comment by bradjones1** [comment]
Update, seems like this works if you set the `PROXY_BASE_URL` environment variable, and it respects that protocol. I'll be writing up my new-user experience on a ticket to hopefully provide some constructive feedback on the difficulties getting started from zero. Not to nitpick but perhaps reveal some gaps in documentation, etc.

**Comment by ianturton** [comment]
Don't forget you can edit the documentation if you find any issues

**Pull request merged**
