### PR TITLE
[GEOS-9430] Integration Test involving app-schema MongoDB datasource …

### PR DESCRIPTION
**Pull request by taba90**
…with empty list on MongoDB collections

<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [X] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [X] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [X] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [X] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [X] PR for bug fixes and small new features are presented as a single commit
- [X] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [X] New unit tests have been added covering the changes
- [X] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [X] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [x] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by taba90** [comment]
Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-9430?filter=-4

**Comment by fernandor777** [comment]
Just checked on local environment and seems like 2 tests are failing due the the extra feature added to the whole testing data setup.  Tests needs to adjust assert parameters are:
`
[ERROR] Failures: 
[ERROR]   ComplexMongoDBTest.testAttributeIsNull:51->ComplexMongoDBSupport.checkCount:375 
Expected: is <2>
     but: was <3>
[ERROR]   ComplexMongoDBTest>ComplexMongoDBSupport.testStationsWmsGetMap:305 Images are visibly different, found 233 different pixels, against a threshold of 10
`

**Comment by taba90** [comment]
Failures seems not related with the code in this pr. From Travis build: 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project gs-importer-rest: There are test failures.

**Comment by fernandor777** [comment]
This test is still failing, even rebasing with master branch:
`ComplexMongoDBTest>ComplexMongoDBSupport.testStationsWmsGetMap:305 Images are visibly different, found 233 different pixels, against a threshold of 10.`

Perhaps you need to adjust the image check on this WMS test.

**Pull request merged**
