### PR TITLE
[GEOS-7635] Fixing auto-fill for legend in the styles page.

### PR DESCRIPTION
**Pull request by goudine**

### CODE REVIEW

**Comment by tbarsballe** [comment]
Could you add a description of the fix to this PR, and include the JIRA ticket id in the commit message?

**Comment by tbarsballe** [comment]
This looks good, I will merge.
@jodygarnett - did you backport #1749 to 2.8.x as well, or just to 2.9.x? I am wondering if this will need to be backported to 2.8.x?

**Comment by bencaradocdavies** [comment]
@tbarsballe note that there are no more scheduled 2.8.x releases.

**Comment by tbarsballe** [comment]
Ah, thanks. Hadn't noticed we had made to the last 2.8 release already.
I took a look and didn't see a backport of #1749 to 2.8.x, so that makes sense.

**Comment by bencaradocdavies** [comment]
Backports to 2.8.x might be useful. Sometime a client funds an extra maintenance release; I think 2.7.6 was an example. if these happen, they are documented in the usual place:
https://github.com/geoserver/geoserver/wiki/Release-Schedule

**Pull request merged**
