### PR TITLE
Convert tabs to spaces

### PR DESCRIPTION
**Pull request by tbarsballe**
All tabs (`\t`) converted to four (4) spaces.

This will likely make a considerable number of open PRs unmergeable, but given that we are on a new 2.10.x branch, now is probably the best time to do it.

### CODE REVIEW

**Comment by jodygarnett** [comment]
🍰  @aaime from the victoria office

**Comment by bencaradocdavies** [comment]
I am in two minds about this one. I love expunging tabs, but it the mass change and breaking pending merges worth it? I think this change should be discussed on the mailing lists.

Another point of view is that this change does not go far enough! We need to do XML files as well. And we should update the guide to require tab-free XML files. And settle on an XML indentation level (I like 4 spaces) as we currently have a mix of 1, 2, 4 spaces and tabs, sometimes in the same file.

We could also fix imports. And reformat the entire codebase.

The showstopper for this one is the impact it could have on backports. No more clean cherry-picking for you! I guess one solution is to do 2.8.x and 2.9.x at the same time.

@tbarsballe ask @jodygarnett to tell you about the fun times we had in this project and GeoServer trying to use [http://jalopy.sourceforge.net/](Jalopy) and svn.

**Comment by jodygarnett** [comment]
We have discussed previously, result was we should do it one day as a
distinct commit at the start of a new branch.

We could do the same steps to our three active branches to make subsequent
pull requests easier.
On Thu, May 12, 2016 at 6:57 PM Ben Caradoc-Davies <notifications@github.com>
wrote:

> I am in two minds about this one. I love expunging tabs, but it the mass
> change and breaking pending merges worth it? I think this change should be
> discussed on the mailing lists.
>
> Another point of view is that this change does not go far enough! We need
> to do XML files as well. And we should update the guide to require tab-free
> XML files. And settle on an XML indentation level (I like 4 spaces) as we
> currently have a mix of 1, 2, 4 spaces and tabs, sometimes in the same file.
>
> We could also fix imports. And reformat the entire codebase.
>
> The showstopper for this one is the impact it could have on backports. No
> more clean cherry-picking for you! I guess one solution is to do 2.8.x and
> 2.9.x at the same time.
>
> @tbarsballe <https://github.com/tbarsballe> ask @jodygarnett
> <https://github.com/jodygarnett> to tell you about the fun times we had
> in this project and GeoServer trying to use http://jalopy.sourceforge.net/
> <http://Jalopy> and svn.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/geoserver/geoserver/pull/1598#issuecomment-218933292>
>
-- 
--
Jody Garnett

**Comment by simboss** [comment]
Quick stab at this, I am not keen on this PR.

Here is my counter proposal, which I will discuss with andrea and then bring to the ML.

We do a remote coordinate sprint to review all (or better most) of the PR in the flow then we do this step. I mean there are 23 PRs out there and many of them seem useful. Do we want to loose them?

As usual, not wanting to be a showstopper, just trying to have an open discussion.

**Comment by tbarsballe** [comment]
My main concern is that if this gets deferred on behalf of pending PRs, it will continue to get put off indefinately. Tabs / Spaces has been a problem for quite some time (longer than I have been part of this project at least), and the argument has consistently been along the lines of "we should do this eventually, but it will be a hassle".
Right now, we are actually in a reasonably good situation make this change.

Last PSC meeting we did a (brief) review of both GeoTools and GeoServer pull requests, and merged those that could be merged (although GeoTools did get a bit more attention than GeoServer).

An attempt to review and merge all (or even most of) the current PRs will likely not succeed without a substantial time investment:
We have 23 open pull requests on this repo (including this one)
10 of them are over a year old, and are blocked for one reason or another.
Of the remaining 13, another 7 fail CI checks or have merge conflicts. A couple more are waiting for feedback of one sort or another. This leaves about 3 PRs that could maybe be merged in there current state.
Given this, the vast majority of open Pull Requests require code changes before being merged. Anywhere this is the case, fixing any conflicts caused by this PR would not be a significant amout of additional work.


I agree that there is more that could be done in this vein, but this is an easy, relatively safe start. Most of the other changes you mention would require a significant review of the codebase. See above for info on the currently open PRs.


However, if there are still concerns, we can close this PR and wait until everyone feels we are in a state to make this change. I expect this would result in this not getting done until GeoServer 2.11.x or later...

**Comment by jodygarnett** [comment]
I think we have lost the opportunity of a fresh master branch, @simboss the idea of cleaning up outstanding pull requests (or creating an open jira issue with a link before closing them) is worthwhile.

**Pull request closed without merging**
