### PR TITLE
Add space between type and variable

### PR DESCRIPTION
**Pull request by petersmythe**
Fixes: [storage.DefaultStorageFinder] - Found system environment variableGEOSERVER_DATA_DIR set to

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Review by bradh — APPROVED** [review]
LGTM.

**Comment by petersmythe** [comment]
Restarting failing tests

**Comment by aaime** [comment]
The backport to `2.24.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'

```
</details>

<details>
<summary>stdout</summary>

```
[backport-7663-to-2.24.x ffde91014f] Add space between type and variable Fixes: [storage.DefaultStorageFinder] - Found system environment variableGEOSERVER_DATA_DIR set to
 Author: Peter Smythe <peter@afrigis.co.za>
 Date: Sun May 19 12:43:20 2024 +0200
 1 file changed, 2 insertions(+), 2 deletions(-)
On branch backport-7663-to-2.24.x
You are currently cherry-picking commit 84663e54cf.
  (all conflicts fixed: run "git cherry-pick --continue")
  (use "git cherry-pick --skip" to skip this patch)
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

nothing to commit, working tree clean

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-2.24.x 2.24.x
# Navigate to the new working tree
cd .worktrees/backport-2.24.x
# Create a new branch
git switch --create backport-7663-to-2.24.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick b316ebfe5a4879705b7a2dd348c1ad44aab9ccff,4eae466f2b6d4428469f4cea42a7843fd2068f31,84663e54cfbb03320080660a109954d22a235bff,78f1df87695cb1ec38f782ea0276a82ec4166c57
# Push it to GitHub
git push --set-upstream origin backport-7663-to-2.24.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-2.24.x
```
Then, create a pull request where the `base` branch is `2.24.x` and the `compare`/`head` branch is `backport-7663-to-2.24.x`.

**Comment by aaime** [comment]
The backport to `2.25.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'

```
</details>

<details>
<summary>stdout</summary>

```
[backport-7663-to-2.25.x e9c11dea03] Add space between type and variable Fixes: [storage.DefaultStorageFinder] - Found system environment variableGEOSERVER_DATA_DIR set to
 Author: Peter Smythe <peter@afrigis.co.za>
 Date: Sun May 19 12:43:20 2024 +0200
 1 file changed, 2 insertions(+), 2 deletions(-)
On branch backport-7663-to-2.25.x
You are currently cherry-picking commit 84663e54cf.
  (all conflicts fixed: run "git cherry-pick --continue")
  (use "git cherry-pick --skip" to skip this patch)
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

nothing to commit, working tree clean

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-2.25.x 2.25.x
# Navigate to the new working tree
cd .worktrees/backport-2.25.x
# Create a new branch
git switch --create backport-7663-to-2.25.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick b316ebfe5a4879705b7a2dd348c1ad44aab9ccff,4eae466f2b6d4428469f4cea42a7843fd2068f31,84663e54cfbb03320080660a109954d22a235bff,78f1df87695cb1ec38f782ea0276a82ec4166c57
# Push it to GitHub
git push --set-upstream origin backport-7663-to-2.25.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-2.25.x
```
Then, create a pull request where the `base` branch is `2.25.x` and the `compare`/`head` branch is `backport-7663-to-2.25.x`.

**Comment by petersmythe** [comment]
Manually done: https://github.com/geoserver/geoserver/pull/7670  & https://github.com/geoserver/geoserver/pull/7671

**Pull request merged**
