### PR TITLE
Fix build (tests) on Windows with Java 8

### PR DESCRIPTION
**Pull request by bradh**
I think both these fixes are Windows specific. They were done with java 8 though, which might have exposed the issues.

### CODE REVIEW

**Comment by bradh** [comment]
GEOS-7090 - https://osgeo-org.atlassian.net/browse/GEOS-7090

**Comment by aaime** [comment]
Hi, I've just tested on Windows with java 7, the test fails as modified, but works fine in its current version.

**Comment by bradh** [comment]
OK, thanks for the advice. I don't see this as a noted change in Java 8, so will need to investigate further.

**Comment by aaime** [comment]
Hi Brad, I have made one more test, with java 8 (u40)... the pull fails for me, and master builds fine instead. Maybe it's environment specific. Venturing a guess... are you building under cygwin, or the git shell?

**Comment by bradh** [comment]
I'm doing it under netbeans.

**Comment by aaime** [comment]
Interesting... have you tried with maven on the command line?

**Pull request closed without merging**
