### PR TITLE
Add drag and drop rules

### PR DESCRIPTION
**Pull request by nmco**
Make spacing consistent

### CODE REVIEW

**Comment by aaime** [comment]
Hi Nuno, pull requests must be accepted on master first, and then they can be backported. This will also remind us to do something about the rule dnd during the wicket upgrade sprint

**Comment by simboss** [comment]
I would also first open a JIRA report :)

**Comment by nmco** [comment]
I will do the pull request on master and open the JIRA report. Thank you for the feedback.

**Comment by nmco** [comment]
New pull request created: https://github.com/geoserver/geoserver/pull/1368

**Pull request closed without merging**
