### PR TITLE
[GEOS-10813] -- jdbcconfig cache bug,changed the workspace name

### PR DESCRIPTION
**Pull request by Tian-geer**
[GEOS-10813](https://osgeo-org.atlassian.net/browse/GEOS-10813)

See jira ticket for details.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
@NielsCharlier or @groldan could you have a look?

**Comment by sikeoka** [comment]
I tested this and it seems to work but could you add a line in the comments to explain why changing the priority is fixing this problem?

**Comment by Tian-geer** [comment]
Because the cache is cleared in 【CatalogClearingListener】, but oldName is cached again in 【NamespaceWorkspaceConsistencyListener#handleModifyEvent <NamespaceInfo ns = catalog.getNamespaceByPrefix(oldName)>】. The listeners are sorted by priority in 【CatalogImpl#addListener】. Raise the priority of xx so that the cache can be cleared at the end
jdbcConfig bug
image
image
image

**Comment by Tian-geer** [comment]
Comments have been added for description

**Comment by NielsCharlier** [comment]
Looks good to me

**Comment by sikeoka** [comment]
Can you revert your CatalogImpl change so that this PR is only changing one file (ConfigDatabase).  The QA check is failing on your CatalogImpl change.

**Comment by Tian-geer** [comment]
Comments for catalogImpl were deleted

**Pull request merged**
