### PR TITLE
Intellij Quickstart

### PR DESCRIPTION
**Pull request by tbarsballe**
Another result of some feedback at the FOSS4G 2017 code sprint.

Split out the Eclipse section of the quickstart into its own page, and added an Intellij quickstart to go alongside it.

Also added a docguide tag to the extlinks, and extlinks to the developer guide, to simplify some linking.

### CODE REVIEW

**Comment by nmco** [comment]
Interesting, I always use the ``Search for projects recursively`` option to retrieve the nested projects like the web ones, I guess this option is not needed anymore.

**Comment by nmco** [comment]
An option I find useful when configuring the GeoServer start is the ``Single instance only`` option, we can only have one GeoServer instance running on the same port, this option will stop any running instance on that port and restart it automatically.

**Comment by tbarsballe** [comment]
> Interesting, I always use the `Search for projects recursively` option to retrieve the nested projects like the web ones, I guess this option is not needed anymore.

I haven't needed to no, I think it can read the nested submodules out of the pom.

> An option I find useful when configuring the GeoServer start is the Single instance only option, we can only have one GeoServer instance running on the same port, this option will stop any running instance on that port and restart it automatically.

That seems super usefull; I might add that as a note.

**Comment by jodygarnett** [comment]
If you folks are happy this can be merged.

**Comment by nmco** [comment]
It looks good to me.

**Pull request merged**
