### PR TITLE
Added prior psc members

### PR DESCRIPTION
**Pull request by mtCarto**

### CODE REVIEW

**Comment by mtCarto** [comment]
@bmmpxf, can you approve? Just another small change with Jody

**Comment by aaime** [comment]
This does not sound right, Dave already left the project when a PSC was formally created via PSC nr 1: https://github.com/geoserver/geoserver/wiki/GSIP%201%20-%20Project%20Steering%20Committee%20formation

**Comment by bmmpxf** [comment]
Resolve and I'll merge?

**Comment by mtCarto** [comment]
Resolved

On Thu, Oct 15, 2015 at 2:28 PM, bmmpxf <notifications@github.com> wrote:

> Resolve and I'll merge?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoserver/geoserver/pull/1265#issuecomment-148526086>.
>



-- 
Morgan Thompson
Junior Engineer | Boundless
mthompson@boundlessgeo.com

**Pull request merged**
