### PR TITLE
Comment web.xml DTD reference to start when disconnected [GEOS-7813]

### PR DESCRIPTION
**Pull request by jodygarnett**
For more information: https://osgeo-org.atlassian.net/browse/GEOS-7813

### CODE REVIEW

**Comment by jodygarnett** [comment]
This is a small change suitable for backport.

**Comment by aaime** [comment]
Wondering if we can put the dtd in the package instead? We do the same for all other OGC schemas for the same reason (to run offline)

**Comment by jodygarnett** [comment]
Kind of up to the configuration of the parser done by Jetty, Tomcat, etc...  (best case is they would contain their own copy of these files as part of "implementing" the Java EE spec).

**Comment by aaime** [comment]
But if they were doing that already, they'd be ignoring the local DTD declaration. What bothers me about removing it is that it makes editing the file harder in tools that are aware of DTDs.

**Comment by jodygarnett** [comment]
Can we include the local DTD, and reference it at the top of the file? (Downside some application servers may freak out since it is not matching one of the standards they support).

**Comment by jodygarnett** [comment]
Tried this a couple ways, including the file locally did not work.

Digging into jetty code they do have a copy of dtd23, and even set up a redirect:

````

redirectEntity("-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN",dtd23);
````

**Comment by jodygarnett** [comment]
I could not determine why jetty is not using its dtd23, this bug fix is still a valid approach.

An alternative would be to upgrade to a newer version of servlet spec - @dvntucker do you have an opinion on this?

**Comment by Sammers21** [comment]
why this pull request in already open?

**Comment by jodygarnett** [comment]
@Sammers21 because it has not been merged (accepted) or closed (rejected) yet.  We are kind of stuck. Do you know anything about how jetty handles redirects?

**Comment by Sammers21** [comment]
@jodygarnett nope. I really have no idea. Have you tried to solve this problem by watching through jetty sources?

**Comment by aaime** [comment]
@jodygarnett it's been many months, time to close this one?

**Comment by jodygarnett** [comment]
I would still like this fix merged, as far as I know I cannot start geoserver when disconnected.

**Comment by aaime** [comment]
All right, you know what the practice is, pull requests that stay there too long get closed and linked from a ticket.

**Pull request closed without merging**
