### PR TITLE
Xstream whitelist backport to 2.6, GEOS-7124

### PR DESCRIPTION
**Pull request by smithkm**

### CODE REVIEW

**Comment by smithkm** [comment]
Running into some strangeness with unit tests on my machine so I'm going to see what Travis makes of it.

**Comment by aaime** [comment]
Heh, Travis only builds master, the work I did to make the Travis build actually work was committed only there. Once we cut 2.8.x we can enable Travis there too though.

**Comment by aaime** [comment]
Run it on my machine during a meeting, here is the one failure I can see (run it with -fae,):

````
-------------------------------------------------------------------------------
Test set: org.geoserver.wps.WPSXStreamLoaderTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.607 sec <<< FAILURE!
testLoadFromXML(org.geoserver.wps.WPSXStreamLoaderTest)  Time elapsed: 1601 sec  <<< ERROR!
com.thoughtworks.xstream.converters.ConversionException: accessInfo : accessInfo
---- Debugging information ----
message             : accessInfo
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : accessInfo
class               : java.util.ArrayList
required-type       : java.util.ArrayList
converter-type      : org.geoserver.config.util.XStreamPersister$ProxyCollectionConverter
line number         : 35
class[1]            : org.geoserver.wps.ProcessGroupInfoImpl
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : org.geoserver.wps.WPSInfoImpl
version             : 2.6-SNAPSHOT
-------------------------------
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:98)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:91)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:85)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:80)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1169)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1049)
        at org.geoserver.config.util.XStreamPersister.load(XStreamPersister.java:587)
        at org.geoserver.wps.WPSXStreamLoaderTest.testLoadFromXML(WPSXStreamLoaderTest.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
````

**Comment by smithkm** [comment]
Thanks @aaime, It was a result of backporting unit tests for a feature that wasn't in 2.6.x.

I'm still getting strange failures in WFS, but I'm confident that they are a result of the tests screwing up, and it's working just fine on Jody's machine.

**Pull request merged**
