### PR TITLE
[GEOS-11623] Refactor GSModalWindow to use ModalDialog instead of deprecated ModalWindow

### PR DESCRIPTION
**Pull request by sikeoka**
[GEOS-11623](https://osgeo-org.atlassian.net/browse/GEOS-11623) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

This PR refactors GSModalWindow to use ModalDialog instead of ModalWindow which is deprecated in Wicket 9 and removed from Wicket 10 which is required for the Jakarta EE migration. The new modals should be visually very similar to the old modals. Two capabilities of the old modals that have not been ported into the new modals are dragging modals around the screen and resizing modals. They can be future enhancements if anyone really needs that.

The PageCreator interface was removed and everything now sets a Component as the modal content instead of a Page. The only case where this caused issues besides styling issues was with the WPS subprocess builder which required a workaround to get the select2 dropdown working properly. Unused ModalWindow API was removed and resizing-related API was also removed since that isn't currently supported.

This PR includes the changes in https://github.com/geoserver/geoserver/pull/7988 and replaces that PR. If this PR were merged along with https://github.com/geoserver/geoserver/pull/7985 and https://github.com/geoserver/geoserver/pull/7986, the only three remaining CSP violations are inline script usage in the importer extension and elasticsearch and taskmanager community modules. The core GeoServer webapp should be fully functional with the blocking CSP enabled.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
@DBlasby you might be interested in this one

**Comment by davidblasby** [comment]
I just saw this.  There are a lot of changes, I will test it later in the week.

Cheers for doing this!

**Comment by aaime** [comment]
We were looking at it during the PSC meeting, the idea is to merge this one and @davidblasby will look into adding ability to resize and move the window. Unless @sikeoka beats him to the punch? :rofl: 

I'm going to try and do a code review before merge, so far I've only done some interactive testing.

**Comment by aaime** [comment]
Overall looking good, thanks @sikeoka 

@davidblasby I've opened one ticket for the resizing:
* https://osgeo-org.atlassian.net/browse/GEOS-11657

I've also opened two tickets for unrelated issues, pre-existing this work, that I've noticed while interacting with the UI:
* https://osgeo-org.atlassian.net/browse/GEOS-11656
* https://osgeo-org.atlassian.net/browse/GEOS-11655

On the bright side... editing a subprocess works! Not sure if this is the change the fixed it, or the wicket upgrade... but happy to close this one: https://osgeo-org.atlassian.net/browse/GEOS-7967

**Pull request merged**
