### PR TITLE
[GEOS-11314] Fix error in IconService with multiple FeatureTypeStyles

### PR DESCRIPTION
**Pull request by iaunzu**
[GEOS-11314](https://osgeo-org.atlassian.net/browse/GEOS-11314) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

This is a PR for [GEOS-11314](https://osgeo-org.atlassian.net/browse/GEOS-11314)

These changes attempt to filter FeatureTypeStyles with empty rules specifically for this case. It should probably be done whenever IconPropertyInjector.injectProperties is called, but I am not entirely certain.

# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [X] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [X] New unit tests have been added covering the changes.
- [X] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [X] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [X] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [X] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [X] Bug fixes and small new features are presented as a single commit.
- [X] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by iaunzu** [comment]
In that case, the code is simpler. Pushed.

**Comment by aaime** [comment]
Thanks, merged.

**Comment by aaime** [comment]
The backport to `2.25.x` failed:
```
The process '/usr/bin/git' failed with exit code 128
```
<details>
<summary>stderr</summary>

```
error: commit 151b2b0b35079fedbefa40b40b6296c8be2af480 is a merge but no -m option was given.
fatal: cherry-pick failed

```
</details>

<details>
<summary>stdout</summary>

```
[backport-7447-to-2.25.x 7f6989e780] [GEOS-11314] Fix error in IconService with multiple FeatureTypeStyles
 Author: iaunzu <inigo.alcalde@gmail.com>
 Date: Wed Feb 28 11:34:28 2024 +0100
 4 files changed, 37 insertions(+), 5 deletions(-)
[backport-7447-to-2.25.x 919f53b994] Filter empty rules in all cases
 Author: iaunzu <inigo.alcalde@gmail.com>
 Date: Wed Mar 20 13:49:05 2024 +0100
 2 files changed, 4 insertions(+), 11 deletions(-)

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-2.25.x 2.25.x
# Navigate to the new working tree
cd .worktrees/backport-2.25.x
# Create a new branch
git switch --create backport-7447-to-2.25.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick f951c67e163c6396de878502d9544f97098882d6,4ac4f08263c5ef7ab1f023f7abea0b01caa7893c,151b2b0b35079fedbefa40b40b6296c8be2af480
# Push it to GitHub
git push --set-upstream origin backport-7447-to-2.25.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-2.25.x
```
Then, create a pull request where the `base` branch is `2.25.x` and the `compare`/`head` branch is `backport-7447-to-2.25.x`.

**Comment by aaime** [comment]
The backport to `2.24.x` failed:
```
The process '/usr/bin/git' failed with exit code 128
```
<details>
<summary>stderr</summary>

```
error: commit 151b2b0b35079fedbefa40b40b6296c8be2af480 is a merge but no -m option was given.
fatal: cherry-pick failed

```
</details>

<details>
<summary>stdout</summary>

```
[backport-7447-to-2.24.x e3b6112425] [GEOS-11314] Fix error in IconService with multiple FeatureTypeStyles
 Author: iaunzu <inigo.alcalde@gmail.com>
 Date: Wed Feb 28 11:34:28 2024 +0100
 4 files changed, 37 insertions(+), 5 deletions(-)
[backport-7447-to-2.24.x d468c1b806] Filter empty rules in all cases
 Author: iaunzu <inigo.alcalde@gmail.com>
 Date: Wed Mar 20 13:49:05 2024 +0100
 2 files changed, 4 insertions(+), 11 deletions(-)

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-2.24.x 2.24.x
# Navigate to the new working tree
cd .worktrees/backport-2.24.x
# Create a new branch
git switch --create backport-7447-to-2.24.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick f951c67e163c6396de878502d9544f97098882d6,4ac4f08263c5ef7ab1f023f7abea0b01caa7893c,151b2b0b35079fedbefa40b40b6296c8be2af480
# Push it to GitHub
git push --set-upstream origin backport-7447-to-2.24.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-2.24.x
```
Then, create a pull request where the `base` branch is `2.24.x` and the `compare`/`head` branch is `backport-7447-to-2.24.x`.

**Pull request merged**
