### PR TITLE
GEOS-7937 - Remove use of deprecated Files method in ResourcePool

### PR DESCRIPTION
**Pull request by dvntucker**
This one is a little tricky, I don't have a test right now because the actual conditions under which this is a problem are extremely specific:

- Using a non-default ResourceStore. When doing this no base directory gets set in GeoServerResourceLoader, which causes a few other things to fail when they start trying to munge things into a File based off the base directory.

- Using a custom GridFormat AND a custom DataStorePanelInfo implementation for it. We're testing a GridFormats that use things like S3 and HDFS internally right now, which have custom URL protocols (eg. s3://). We have a custom UI that skips all file-y validations for these URLs. However the ResourcePool still attempts to convert this to a file in order to pass to the GridReader.

Thankfully this is all fixed by using Resources.fromURL instead of the now-deprecated loader.fromURL. 

Unfortunately I don't have a test for this, but thankfully the test coverage for getGridCoverageReader is already quite good, and the change is moving from a deprecated method to its non-deprecated alternative, so maybe we can merge it anyway? If there are concerns I can look at writing a test for the specific bug being addressed.

### CODE REVIEW

**Comment by aaime** [comment]
How hard is it to write a test? 
Mind, it seems the change broke a test in the importer module:

````
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.756 sec <<< FAILURE!
testPopulateEmptyMosaic(org.geoserver.importer.mosaic.ImporterMosaicTest)  Time elapsed: 65 sec  <<< ERROR!
java.lang.IllegalArgumentException: Contains invalid . path: 
	at org.geoserver.platform.resource.Paths.toPath(Paths.java:168)
	at org.geoserver.platform.resource.Paths.path(Paths.java:114)
	at org.geoserver.platform.resource.Paths.path(Paths.java:96)
	at org.geoserver.platform.resource.FileSystemResourceStore$FileSystemResource.get(FileSystemResourceStore.java:422)
	at org.geoserver.platform.resource.Resources.fromURL(Resources.java:580)
	at org.geoserver.platform.GeoServerResourceLoader.fromURL(GeoServerResourceLoader.java:187)
	at org.geoserver.platform.resource.Resources.fromURL(Resources.java:512)
	at org.geoserver.catalog.ResourcePool.getGridCoverageReader(ResourcePool.java:1488)
````

**Comment by dvntucker** [comment]
Just saw the failure, not sure why I missed it when I ran tests.

**Comment by dvntucker** [comment]
Actually, thinking about it this may be one of those instances where we *do* want to rely on the direct file system access rather than the Resources APIs, since most likely grid coverages are actual files and not typically stored along with GeoServer resources...

I may need to go back to the drawing board a bit on this one.

**Comment by jodygarnett** [comment]
Curious about lack of "base directory" - even with JDBCStore we need a "base directory" for those rare api calls where a file has to be passed in; so the blob is saved out to the "base directory" (assumed to be a tmp folder) just so we can make the API call. 

I hope such calls are now rare - I think templates were some of the new remaining examples.

**Comment by dvntucker** [comment]
Ok, I changed this one around a little. Instead of using the Resources code it checks the URL to see if it's a file or doesn't have a scheme and converts it to a file, otherwise it uses the String on its own. It's basically an explicit version of what the code was doing by happenstance anyway.

@aaime WRT how difficult it is to test the actual bug we ran into, it only happens under the following conditions:

- Not using the default file based store, instead using one such as JDBCStore.
- Using a GridFormat that relies on actual URLs rather than files (such as S3 or HDFS)
- Using a custom grid edit panel that skips the file check validations.

I'm certainly open to advice on testing it. Maybe by mocking out the ResoureStore implementation some how? But then I'm not sure how to inject that implementation in during a single test.

The good news is that it's a fairly minor refactor to a method that already has very good test coverage.

@jodygarnett It's possible that baseDirectory should be set for other resource store implementations... but, to what? I'd like to look at code that still relies on a directory because any code that explicitly requires file system access at this point shouldn't really be going through the ResourceStore, right?

**Comment by aaime** [comment]
Looks good to me

**Comment by tbarsballe** [comment]
Merged + Backported to 2.10.x

**Pull request merged**
