### PR TITLE
GEOS-8804 - Allow for subsets on multiple custom dimensions

### PR DESCRIPTION
**Pull request by Mrc0113**
Fix Bug: https://osgeo-org.atlassian.net/browse/GEOS-8804

Note I did not see an existing test that would be easy to modify, but it should be pretty easy to see that the dimensionsFilter was previously being overwritten each time through the loop.

### CODE REVIEW

**Comment by aaime** [comment]
Wondering if there is something suitable in the netcdf or grib modules (they do have WCS tests specific to n-dimensional inputs/outputs)

**Comment by Mrc0113** [comment]
@dromagnoli Thanks for the suggestion. I should be able to take a closer look at the tests early next week.  Will let you know!

**Comment by Mrc0113** [comment]
@dromagnoli Test added, but build failed due to what I think may have been a timeout?  It looks like 4 builds were going on simultaneously when mine failed.  Is it possible to have it rebuild?

**Comment by bencaradocdavies** [comment]
@Mrc0113 I have restarted the Travis CI build. That failure is was unrelated. It is a nasty test that uses a thread to test app-schema local resolve timeouts. Hard to test otherwise, and vulnerable to irregular scheduling on VMs.

**Comment by bencaradocdavies** [comment]
The Travis CI build passed.

**Comment by dromagnoli** [comment]
Thanks for the fix and the updated test @Mrc0113.
Merging it right now.

**Comment by dromagnoli** [comment]
@Mrc0113 Do you have any chance to backport it on 2.13.x too?

**Comment by Mrc0113** [comment]
@dromagnoli Is the proper way for me to do that to pull the latest changes on the 2.13.x branch into my repo, merge my commits from my master branch, make sure the build works, and then create a pull request on that branch?  Or is there some other process I should follow

**Comment by dromagnoli** [comment]
Hi @Mrc0113. Yep. something like that.
What I usually do is to align my 2.13 repo to the latest changes (via git pull as you said). Then cherry-pick the commit (and fix any conflict in case they are), build it and create the PR for 2.13.x.

**Comment by Mrc0113** [comment]
@dromagnoli Thanks - I should be able to get to that at some point today or tomorrow.

**Comment by Mrc0113** [comment]
@dromagnoli Created backport PR https://github.com/geoserver/geoserver/pull/2999

**Pull request merged**
