### PR TITLE
[GEOS-10143] Set up PMD cognitive complexity checks, start cleaning up methods that are too complex

### PR DESCRIPTION
**Pull request by aaime**
[GEOS-10143](https://osgeo-org.atlassian.net/browse/GEOS-10143)

Cleaned methods that are too complex down to 130. 

I could not get a grip on the mapml issue so marked for ignore, @prushforth if you have time could you have a look?
Cognitive complexity is [explained in a short paper](https://www.sonarsource.com/docs/CognitiveComplexity.pdf).

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the `main` branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by prushforth** [comment]
> 
> I could not get a grip on the mapml issue so marked for ignore, @prushforth if you have time could you have a look?
> Cognitive complexity is [explained in a short paper](https://www.sonarsource.com/docs/CognitiveComplexity.pdf).

Sorry, overlooked this until now. I will have a look.

**Comment by prushforth** [comment]
@aaime I made a first pass at splitting that long method up to reduce the complexity, which does work to get it in under the plugin score you set. However, it is a first pass and could you advise: I don't think it improves the readability too much because there are so many conditions to check and they all become parameters to the [introduced method](https://github.com/Maps4HTML/geoserver/blob/6240927eb0ef20961ac6d64f9e256bd113c64481/src/extension/mapml/src/main/java/org/geoserver/mapml/MapMLController.java#L601).  I was thinking of making an inner class with all these fields and setting them up on an instance then passing just that instance.  It would shorten the method signature, but does that improve readability??  Maybe.  What is your view?  Thank you.

**Comment by aaime** [comment]
Yeah that's a lot of parameters. For code that's highly tangled up using a [method object](https://refactoring.guru/replace-method-with-method-object) approach is normally the way to go. 
Of course, the result should read better:
* main method reading as a summary of the steps
* each step method isolated enough from the others that it can be read and understood by itself

If the result is just technically passing the QA check, but not actually any better to read, we can just leave the suppression there.

**Comment by prushforth** [comment]
OK, I'll take the method object approach.  Please go ahead with this, leaving the suppression in place, and I'll make a separate issue for this, if that's appropriate. Thanks for your help.

**Review by dromagnoli — APPROVED** [review]
Looks good to me. (only a minor TYPO spotted on a new method)

**Comment by prushforth** [comment]
@aaime 

> OK, I'll take the method object approach. Please go ahead with this, leaving the suppression in place, and I'll make a separate issue for this, if that's appropriate. Thanks for your help.

Note I went ahead and submitted a PR to your fork.  It passes the QA checks on my machine, so hopefully if you merge, it will show up here as another commit and prove itself in these checks.  Seemed easier than opening a separate issue, but if not, please just close that PR and I'll make the change as a separate issue.

**Comment by aaime** [comment]
@prushforth seen it. This work has no funding backing it, so I'm doing it in my spare time. I hope to have a look at the PR this weekend, otherwise it might have to wait a couple of weeks (next week, including Sunday, I'm away in vacation, which means no computer with me). Don't worry, your work is appreciated, I just have precious little time to push it forward, but it's going to happen.

**Comment by aaime** [comment]
@prushforth uh oh, looks like there is a conflict after merge

**Comment by prushforth** [comment]
> Don't worry, your work is appreciated, I just have precious little time to push it forward, but it's going to happen.

Cool I will have a look at it tonight.  Thanks for your work on this, and the nudge to improve my code is much appreciated.

**Pull request merged**
