### PR TITLE
[GEOS-10606] Geneate html files for assemblies

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOS-10606](https://osgeo-org.atlassian.net/browse/GEOS-10606)

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by jodygarnett** [comment]
@bradh if you can review? Goal is to generate html files; found a few missing licenses along the way. No functional change.

**Comment by bradh** [comment]
@jodygarnett Will try to do so over the weekend.

**Comment by jodygarnett** [comment]
Trying to assemble a working story for Docker use ahead of foss4g workshop if we can.

**Comment by juanluisrp** [comment]
This has broken the Windows installer script that needs a `NOTICE.md` file in the `geoserver-*-bin.zip` file that it's used for generating the exe. Currently this is the error thrown:
```
!system: "pandoc -s -f markdown -t rtf "..\source\NOTICE.md" -o license.rtf"
pandoc.exe: ..\source\NOTICE.md: openBinaryFile: does not exist (No such file or directory)
!makensis: returned 1, aborting
!system: returned 1
Error in script "geoserver_winsetup.nsi" on line 130 -- aborting creation process
!insertmacro: MUI_PAGE_WELCOME
```

https://github.com/geoserver/geoserver/blob/169d2502d24ec044bf4f4796ab2aa951c5d1e5d6/src/release/installer/win/build/geoserver_winsetup.nsi#L187-L191

**Pull request merged**
