### PR TITLE
[GEOS-8909] Layer/LayerGroup Name order ASC on WMS 1.1.1 GetCapabilitiesTransformer

### PR DESCRIPTION
**Pull request by fernandor777**

### CODE REVIEW

**Comment by nmco** [comment]
Restarting the windows build, not sure if the failure is related or not:
```
[INFO] gs-restconfig ...................................... FAILURE [02:07 min]
```

**Comment by nmco** [comment]
Closing and reopening to start the build.

**Comment by aaime** [comment]
The failure looks indeed unrelated:

````
[00:20:06] Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.203 sec <<< FAILURE!
[00:20:06] testGetStatusAsHTML(org.geoserver.rest.catalog.AboutControllerTest)  Time elapsed: 406 sec  <<< ERROR!
[00:20:06] org.xml.sax.SAXParseException; lineNumber: 46; columnNumber: 8530; An invalid XML character (Unicode: 0xf) was found in the element content of the document.
[00:20:06] 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
[00:20:06] 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
[00:20:06] 	at org.geoserver.test.GeoServerSystemTestSupport.dom(GeoServerSystemTestSupport.java:1552)
[00:20:06] 	at org.geoserver.test.GeoServerSystemTestSupport.dom(GeoServerSystemTestSupport.java:1531)
[00:20:06] 	at org.geoserver.test.GeoServerSystemTestSupport.getAsDOM(GeoServerSystemTestSupport.java:1409)
[00:20:06] 	at org.geoserver.test.GeoServerSystemTestSupport.getAsDOM(GeoServerSystemTestSupport.java:1256)
[00:20:06] 	at org.geoserver.rest.catalog.AboutControllerTest.testGetStatusAsHTML(AboutControllerTest.java:97)
[00:20:06] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:20:06] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:20:06] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:20:06] 	at java.lang.reflect.Method.invoke(Method.java:498)
````

**Comment by simboss** [comment]
I will go ahead and merge then @aaime

**Comment by aaime** [comment]
I did not review the PR, just looked at the failure, but... ok, the changes seem obvious, same logic as in the WMS 1.3 code.

**Comment by nmco** [comment]
I reviewed the PR @aaime, I was not clear about that indeed.

**Pull request merged**
