### PR TITLE
[GEOS-10462] Upgrade to org.apache.httpcomponents:httpclient completed

### PR DESCRIPTION
**Pull request by jodygarnett**
[GEOS-10462](https://osgeo-org.atlassian.net/browse/GEOS-10462)

The dependency on ``commons-httpclient`` is no longer required. In addition to building, I checked ``dependency:tree`` on main and web to look out for any remaining transitive dependencies.

This depends on [GEOT-5859](https://osgeo-org.atlassian.net/browse/GEOT-5859) and https://github.com/geoserver/geoserver/pull/5702

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
Several compile failures, seems the upgrade is not complete... at least 3 modules still using it?

**Comment by jodygarnett** [comment]
Well that is discouraging:
- GWC
- Web Processing Service Module
- Importer

**Comment by sikeoka** [comment]
I created a PR for WPS: https://github.com/geoserver/geoserver/pull/5971

I am not familiar with the Importer or SAML modules so I can't upgrade either of those modules.

**Comment by jodygarnett** [comment]
This issue is of interest to me although I lack funding to work directly on it; please stale bot keep this PR alive :)

**Pull request closed without merging**
