### PR TITLE
[GEOS-10698] - OGCAPI and REST API coexistence issue

### PR DESCRIPTION
**Pull request by taba90**
[GEOS-10698](https://osgeo-org.atlassian.net/browse/GEOS-10698)

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by mprins** [comment]
This might also fix https://osgeo-org.atlassian.net/browse/GEOS-10659

**Comment by aaime** [comment]
@taba90 I'd say it is the same as GEOS-10659 by the description of the behavior, would you agree?

**Comment by taba90** [comment]
> @taba90 I'd say it is the same as GEOS-10659 by the description of the behavior, would you agree?

@aaime @mprins yes is the same.

**Comment by aaime** [comment]
@taba90 I've done a full build locally and deployed the war in Tomcat 9.0.55, alongside the OGC API. I can access the OGC API fine, but when I go to "http://localhost:8080/geoserver/rest" (after being logged in of course) I get:

image

```
org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class org.geoserver.rest.wrapper.RestWrapperAdapter] with preset Content-Type 'null'
	org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:299)
	org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:181)
	org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:123)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1043)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
	org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:73)
	org.geoserver.ows.HTTPHeadersCollector.doFilter(HTTPHeadersCollector.java:48)
	org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
	org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:194)
	org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:70)
	org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:43)
	org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:39)
```

Am I missing anything? The about page reports the revision of this commit, 2495d0599ebf9c7b65b627d8b308cc58353afcb3

**Comment by taba90** [comment]
@aaime I've changed the fix to have the ApiConfiguration class extending directly the RestConfiguration one. With previous one the Freemarker converter was indeed not added when ogcapi was loaded before and thus html output format was failing.
Seems to work everything fine now.

**Comment by taba90** [comment]
gwc REST api has been manually tested as well

**Comment by aaime** [comment]
Guess you need to rebase this branch to make it build.

**Comment by aaime** [comment]
Tested again, works fine. Found a test failure in OGCAPI, but it's not related to these changes.

**Pull request merged**
