### PR TITLE
[GEOS-9585] Add an "apply" button to most catalog and service configuration pages

### PR DESCRIPTION
**Pull request by aaime**
When working on some configuration object, it's handy to just "apply" the change without leaving the page, to see its effects and keep on working. The style page has this, but many other pages could use the same. Will cover most data related pages, as well as services and common configs like global/raster.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [X] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [X] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [X] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [X] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [X] PR for bug fixes and small new features are presented as a single commit
- [X] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [X] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [X] New unit tests have been added covering the changes
- [X] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by NielsCharlier** [comment]
This looks great. 
I have been wondering though, why sometimes "submit" and sometimes "save"? Submit I have noticed is confusing to users, because it usually means you are sending something to somewhere else. Shouldn't this be made more consistent?
Also, on the Style edit page the submit and apply buttons are in the opposite order.
Just suggestions...

**Comment by jodygarnett** [comment]
To sum up email discussion:

- This is great!
- Use Save / Apply / Cancel for forms that immediately persist their change
- Use Okay / Cancel for dialogs or form that update form contents but do not persist their change
- Ian, Jody, Niels volunteer to help update the documentation

Andrea can we merge this in and handle the internationalization efforts in a separate branch / PR?

**Comment by aaime** [comment]
@jodygarnett I agree it's a good idea to have a separate PR for the submit/save bit. I still need to re-order the buttons to make them be save/Submit - Apply - Cancel, that is on me.

**Comment by jodygarnett** [comment]
Thanks, if the PR is not ready you can mark them as draft now in github.

**Comment by aaime** [comment]
@jodygarnett the PR was ready for review, it got the review, and now the review feedback is being applied, see no need for the DRAFT state here (DRAFT is "not ready for review", it is not "not ready for merge"). See also https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by aaime** [comment]
Ok, made it consistent with "Submit/Apply/Cancel" pattern, which mean changing the style page. While I was at it, changed only the style page to use "save" instead of "submit". This caused quite a bit of changes in the tests, because, for consistency, I also changed the wicket id of the button.

Anyhow, should be good to go.

**Pull request merged**
