### PR TITLE
Update GH Windows workflow

### PR DESCRIPTION
**Pull request by mprins**
Add some options to close TCP connection for Maven and update workflow items while here.

Windows builds have been failing for a while due to connection resets.
Apparently this is caused by Azure hanging up the connection after 4mins. without proper notification as described here: https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by aaime** [comment]
Interesting find! Wondering if this would affect the osx builds too... are they running on Azure too? Hmm... nope, it seems not, this arcticle points at macstadium: https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners

**Comment by mprins** [comment]
Yeah, but the Mac builds have been going strong, I'm not sure this relates to OSgeo-repo-failed builds, bid Windows has been having things like this: https://github.com/geoserver/geoserver/pull/4492#issuecomment-694191023 where downloading from Maven central fails

**Comment by mprins** [comment]
Have restarted the windows build a few times, but I think once your have a populated cache for a branch it doesn't matter anymore anyway. In any case does not make things worse and gives us timestamped logging of the Maven build.

**Comment by aaime** [comment]
@mprins the cache does not contain any SNAPSHOT dependency from GeoTools or GeoWebCache though, those are deleted before caching, and thus downloaded every time. So is this good to go, or do you have to work on it more?

**Comment by mprins** [comment]
Nope, I'm done. Lets see how it goes. 

This is actually to fix problems with Maven central like https://github.com/geoserver/geoserver/pull/4504/checks?check_run_id=1159734676 and https://github.com/geoserver/geoserver/pull/4510/checks?check_run_id=1180646081

not snapshotted dependencies from the osgeo repo (though those may be affected too)

**Pull request merged**
