### PR TITLE
GSIP 132: Resource Store Changes

### PR DESCRIPTION
**Pull request by NielsCharlier**

### CODE REVIEW

**Comment by aaime** [comment]
I'll leave the review of the actual contents of the pull request to @jodygarnett , but as a quick check, the files copyright headers have not been updated.

**Comment by aaime** [comment]
Also, it seems that Travis got some legit test failures?

````
Tests run: 36, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 6.241 sec <<< FAILURE!
theoryLeavesHaveNoListOfChildren(org.geoserver.platform.resource.FileSystemResourceTheoryTest)  Time elapsed: 9 sec  <<< ERROR!
org.junit.experimental.theories.internal.ParameterizedAssertionError: theoryLeavesHaveNoListOfChildren(testPaths[0])
	at org.junit.experimental.theories.Theories$TheoryAnchor.reportParameterizedError(Theories.java:192)
	at org.junit.experimental.theories.Theories$TheoryAnchor$1$1.evaluate(Theories.java:146)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithCompleteAssignment(Theories.java:127)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:111)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithIncompleteAssignment(Theories.java:120)
	at org.junit.experimental.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:109)
	at org.junit.experimental.theories.Theories$TheoryAnchor.evaluate(Theories.java:96)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
````

**Comment by jodygarnett** [comment]
Fixed the headers, and fixed the API / Tests to be in sync.

Based on the test failures I expect a commit was missing (to return an empty list for UNDEFINED / RESOURCE).

**Comment by NielsCharlier** [comment]
In the proposal I actually suggested to throw an exception when you do list() on an existing file (not directory). I did already change this, but I forgot to fix the test to my most recent change. It is fine by me to be lenient in this regard as well, but then we need to change the javadoc

**Comment by jodygarnett** [comment]
You can review, javadoc is already changed.

**Pull request closed without merging**
