### PR TITLE
Separate panels for layer defaults and general caching options

### PR DESCRIPTION
**Pull request by smithkm**
Having the locking mode mixed in with the layer defaults was confusing so I split them into two separate panels.

### CODE REVIEW

**Comment by jodygarnett** [comment]
smithkm can this be fixed before the code freeze?

**Comment by smithkm** [comment]
Just rebased to master and tried running in both Eclipse+Jetty and Tomcat.  The page works fine either way for me.  Trying again with an empty maven repo.

**Comment by smithkm** [comment]
Rebuilt with empty maven repo.  I did run into a problem with image-io-tiff not being available but other than that it built fine and the page works.

**Comment by jodygarnett** [comment]
Andrea do you want to try and check again? Kevin is otherwise in position to accept this change?

**Comment by smithkm** [comment]
This probably conflicts with #837.  It looks like @n-lagomarsini has some conflicts to resolve there anyway though.  If it comes down to just one of them making the deadline, this is rather less important.

**Comment by n-lagomarsini** [comment]
Hi Kevin, #837  will not be merged before the freeze so you can merge this pull request before the freeze if you want.

**Comment by smithkm** [comment]
I need to look at this again now the freeze is over.

**Comment by bencaradocdavies** [comment]
No activity for over a year.

**Pull request closed without merging**
