### PR TITLE
fixed bug GEOS-9217

### PR DESCRIPTION
**Pull request by dodeFrancois**
Fix https://osgeo-org.atlassian.net/browse/GEOS-9217

### CODE REVIEW

**Comment by ianturton** [comment]
can you please add a test and complete a contributor license https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md

**Comment by dodeFrancois** [comment]
@ianturton I add a test and complete the contributor license

**Comment by ianturton** [comment]
To fix formatting errors, run "mvn fmt:format"

**Comment by dodeFrancois** [comment]
Done

**Comment by aaime** [comment]
The appveyor failure is a random failure, not caused by the changes in this PR. I've kicked it.
About the CLA, we still haven't received confirmation from OSGeo (you signed and sent the CLA to info@osgeo.org right?)

**Comment by dodeFrancois** [comment]
@aaime Yes I sent it. I received a response from Astrid Emde. She added my CLA on their database.

**Comment by aaime** [comment]
Had a look, this is really really bizarre... I did not know it was even possible to do what this ticket is talking about, and indeed, it was not possible in the original REST API before the Spring MVC switch:
https://docs.geoserver.org/latest/en/user/rest/api/featuretypes.html

Someone must have thought it would have been useful to extend it during the Spring MVC switch sprint, documented it, half implemented it, but never really tested it was actually working. So thanks for fixing it.

Merging, in case you want the fix also to be on 2.15.x and 2.14.x can you do backport PRs?

**Comment by aaime** [comment]
Ah, I did very the CLA is there on file.

**Comment by dodeFrancois** [comment]
Thank you. I will open a PR on 2.15.x branch.

**Pull request merged**
