### PR TITLE
[GEOS-7444] Handle unmarshalling of GridGeometry2D objects when the J…

### PR DESCRIPTION
**Pull request by dispiste**
…SON/XML definition follows an arbitrary order

### CODE REVIEW

**Comment by aaime** [comment]
Hi,have a look at the contribution guide here:
https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md

Haven't checked the pull request details, but from a glance, it's missing copyright header updates and lacks a test

**Comment by dispiste** [comment]
Regarding the copyright header, I have read the documentation but it is not
clear to me. Should I just add 2016 to OSGEO copyright, or should I add my
organization on the top?

Then probably we'll need to sign the corporate contribution agreement,
because I have personally signed the agreement in the past, but I think it
will be more appropriate to sign a corporate agreement in this case.

On 3 March 2016 at 19:03, Andrea Aime <notifications@github.com> wrote:

> Hi,have a look at the contribution guide here:
> https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md
>
> Haven't checked the pull request details, but from a glance, it's missing
> copyright header updates and lacks a test
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoserver/geoserver/pull/1525#issuecomment-191889274>.
>



-- 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   César Martínez Izquierdo
   GIS developer
   -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
   SCOLAB: http://www.scolab.es
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by aaime** [comment]
You just need to update the last year for OSGeo to be 2016.

**Comment by dispiste** [comment]
Thanks Andreas, I've added a check and updated the copyright header.

**Comment by aaime** [comment]
Hi, thank you. Just noticed you did not respect the coding conventions, no tabs please, just spaces.
The contributor guide has a reference to it, please read it all and check if there is any other deviation to fix.

**Comment by dispiste** [comment]
I have re-formatted according Geotools conventions. In order to keep the fix clear I've only modified the methods involved on the fix.  Note that there are still some wrongly formatted methods (already  present).

**Comment by aaime** [comment]
Looks like I have manually merged this one and backported to 2.8.x and 2.7.x, but forgot to close the pull request. Doing so now.

**Pull request closed without merging**
