### PR TITLE
Synchronize translations with Transifex

### PR DESCRIPTION
**Pull request by AlexGacon**
Manual merge with Transifex translation to ensure correct encoding of files.
  

# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by mprins** [comment]
failure:

```
2022-01-02T20:52:15.9559528Z 20:52:15,955 [INFO] --- maven-enforcer-plugin:3.0.0:enforce (localization-encodings) @ gs-web-wms ---
2022-01-02T20:52:15.9590407Z 20:52:15,958 [WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireEncoding failed with message:
2022-01-02T20:52:15.9592482Z src/main/resources/GeoServerApplication_zh_CN.utf8.properties==>US-ASCII

...

2022-01-02T20:57:11.9090745Z 20:57:11,899 [INFO] ------------------------------------------------------------------------
2022-01-02T20:57:11.9148264Z 20:57:11,909 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce (localization-encodings) on project gs-web-wms: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
2022-01-02T20:57:11.9149698Z 20:57:11,909 [ERROR] 
2022-01-02T20:57:11.9150502Z 20:57:11,909 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
2022-01-02T20:57:11.9151470Z 20:57:11,909 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2022-01-02T20:57:11.9152024Z 20:57:11,909 [ERROR] 
2022-01-02T20:57:11.9152740Z 20:57:11,909 [ERROR] For more information about the errors and possible solutions, please read the following articles:
2022-01-02T20:57:11.9153886Z 20:57:11,909 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
2022-01-02T20:57:11.9154678Z 20:57:11,909 [ERROR] 
2022-01-02T20:57:11.9155433Z 20:57:11,909 [ERROR] After correcting the problems, you can resume the build with the command
2022-01-02T20:57:11.9156293Z 20:57:11,909 [ERROR]   mvn <args> -rf :gs-web-wms
```

So that file seem to be ASCII encoded while the rules require it to be UTF-8

**Comment by aaime** [comment]
Correct. Wicket wants ISO-8859-1 for any simple property file, but requires UTF-8 encoding for the ones ending in ".utf8.properties".

**Comment by AlexGacon** [comment]
I revert to the previous file which seems more up-to-date than the one in Transifex.

**Comment by AlexGacon** [comment]
I think that the last error is not linked to my changes.

**Comment by mprins** [comment]
restarted the Java 17 build that failed with `java.lang.OutOfMemoryError: Java heap space`

**Review by mprins — APPROVED** [review]

**Pull request merged**
