### PR TITLE
[GEOS-10002] Update url for Inspire Schemas in gs-inspire extension

### PR DESCRIPTION
**Pull request by taba90**
[GEOS-10002](https://osgeo-org.atlassian.net/browse/GEOS-10002) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

Jira ticket https://osgeo-org.atlassian.net/browse/GEOS-10002
this pr udpates the Inspire schemas url from http to https.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the `main` branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [x] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by nmco** [comment]
Documentation should be updated too: https://docs.geoserver.org/stable/en/user/extensions/inspire/using.html#extended-wms-and-wmts-capabilities

**Comment by nmco** [comment]
Should we not need to update at least one test?

**Comment by taba90** [comment]
thanks for your review @nmco documentation updated.
Regarding tests:  test of the new namspaces uri is implicit in the already existing tests since, element are checked by TagNameNS using the updated constants eg check [here ](https://github.com/geoserver/geoserver/blob/6e9e25c0c7cdda9ada9f33f8255130d3afc76801/src/extension/inspire/src/test/java/org/geoserver/inspire/wms/WMSExtendedCapabilitiesTest.java#L84) or [here ](https://github.com/geoserver/geoserver/blob/b12a833ec3b04ff3606e023681fd90205f22417e/src/extension/inspire/src/test/java/org/geoserver/inspire/wfs/WFSExtendedCapabilitiesTest.java#L69)

**Comment by nmco** [comment]
Thx @taba90, this is a pure bug fix and can be back-ported right away.

**Pull request merged**
