### PR TITLE
ConfigurableBlobStore must add listeners to delegate

### PR DESCRIPTION
**Pull request by groldan**
ConfigurableBlobStore must add listeners to delegate regardless of its configuration status.

ConfigurableBlobStore is precluding blob store listeners from being added to
the delegate blob store at start up time, since GWCInitializer.initialize
calls ConfigurableBlobStore.setChanged() after the beans have been loaded.

This is making the disk-quota subsystem unusable, since it needs to register
a blobstore listener at startup time. Moreover, adding the listener should
not depend on whether the ConfigurableBlobStore has set up its caching
preferences.

### CODE REVIEW

**Comment by aaime** [comment]
Hi Gabriel, the delegate can be modified at runtime from the GUI, won't you lose the listeners when that happens? How about collecting the listeners in the ConfigurableBlobStore, and then attach them to the current delegate on configuration when configureBlobStore is called instead?

**Comment by groldan** [comment]
Hi Andrea, sorry for the long delay, been swamped by other stuff. I've updated the PR so that the listeners are not lost but reapplied instead when the config changes. Let me know if it looks better.

**Comment by groldan** [comment]
hey @aaime I'm preparing a PR for GWC pluggable blobstores + S3 support. It'd be nice if this PR can be applied first, or taken care of, given its an independent bug introduced by ConfigurableBlobStore which makes disk quota unusable. Let me know if this last patch looks OK to you. TIA.

**Comment by aaime** [comment]
Ah sorry, I did look at this one yesterday but then forgot to comment!
+1

**Pull request merged**
