### PR TITLE
[GEOS-10420] GeoFence group list is too limiting

### PR DESCRIPTION
**Pull request by shadab-geo**
[GEOS-10420](https://osgeo-org.atlassian.net/browse/GEOS-10420)

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by bradh** [comment]
Failure on the Mac OS build looked unrelated - have restarted it.

**Comment by shadab-geo** [comment]
> Failure on the Mac OS build looked unrelated - have restarted it.

Thanks for restarting, build have passed on the Mac OS

**Review by taba90 — CHANGES_REQUESTED** [review]
Looks good to me. I would only perform another request with a different user and different role after  the successful one to test that the second is user is indeed not granted.

**Comment by shadab-geo** [comment]
> Looks good to me. I would only perform another request with a different user and different role after the successful one to test that the second is user is indeed not granted.

thanks @taba90 ,
have added the test for unauthorized user.

**Comment by taba90** [comment]
thanks @shadab-geo looks good to me. Merging.

**Review by taba90 — APPROVED** [review]

**Comment by jodygarnett** [comment]
This commit has broken the build: https://build.geoserver.org/view/geoserver/job/geoserver-main/1058/

```
[INFO] Running org.geoserver.security.auth.GuavaAuthenticationCacheTest
01 Apr 12:22:13 WARN [entry.DefaultAttribute] - ERR_04486_VALUE_ALREADY_EXISTS The value 'tlsKeyInfo' already exists in the attribute (objectClass)
01 Apr 12:22:13 WARN [entry.DefaultAttribute] - ERR_04486_VALUE_ALREADY_EXISTS The value 'inetOrgPerson' already exists in the attribute (objectClass)
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.275 s <<< FAILURE! - in org.geoserver.security.auth.GuavaAuthenticationCacheTest
[ERROR] testExpireByCreation(org.geoserver.security.auth.GuavaAuthenticationCacheTest)  Time elapsed: 1.763 s  <<< FAILURE!
java.lang.AssertionError
```

```
[ERROR] Failures: 
[ERROR]   GuavaAuthenticationCacheTest>BaseAuthenticationCacheTest.testExpireByCreation:60
```

**Comment by jodygarnett** [comment]
Never mind, it appears the build is "just" unstable, the next commit through built okay.

**Pull request merged**
