### PR TITLE
[GEOS-8250] WFS 2.0 DescribeFeatureType responses for app-schema types contain a spurious WFS 2.0 jar import

### PR DESCRIPTION
**Pull request by ridethepenguin**
Link to related JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOS-8250

This is the backport of #2676 to GeoServer 2.11.x (maintenance).

### CODE REVIEW

**Comment by ridethepenguin** [comment]
@bencaradocdavies Sorry, this time you won't be able to sneak the fix into 2.11.4, I'm one day late to the party... :-(

**Comment by bencaradocdavies** [comment]
@ridethepenguin yes, sad about that. It is a nice fix.

**Comment by aaime** [comment]
Legit failure here?

````
Tests run: 33, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 14.107 sec <<< FAILURE!
testDescribeFeatureTypeNoWfsSchemaImport(org.geoserver.test.FeatureChainingWfsTest)  Time elapsed: 41 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at org.geoserver.test.AbstractAppSchemaTestSupport.assertXpathCount(AbstractAppSchemaTestSupport.java:372)
	at org.geoserver.test.FeatureChainingWfsTest.testDescribeFeatureTypeNoWfsSchemaImport(FeatureChainingWfsTest.java:428)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.ja
````

**Comment by ridethepenguin** [comment]
Strange, I was sure my local build had passed, but probably was wrong: I'll look into this.

**Comment by ridethepenguin** [comment]
@aaime I was victim of the typeName vs typeNames confusion... [glad to read](https://osgeo-org.atlassian.net/browse/GEOS-8417?focusedCommentId=78193&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-78193) I'm not alone finding the WFS 2.0 spec contradictory :wink:

Any plans to backport your fix for GEOS-8417? Anyway, all should be well now.

**Comment by aaime** [comment]
@ridethepenguin no plans currently to backport the changes for WFS 2.0 compliance, they were too many and it may not be easy to untangle them (some build on top of others): https://osgeo-org.atlassian.net/issues/?filter=12102

**Pull request merged**
