### PR TITLE
[GSIP-144] LDAP UserGroupService + refactoring to share code with RoleService

### PR DESCRIPTION
**Pull request by NielsCharlier**
Please see https://github.com/geoserver/geoserver/wiki/GSIP-144

### CODE REVIEW

**Comment by NielsCharlier** [comment]
build failure seems to be unrelated, libjpegturbo?

**Comment by jodygarnett** [comment]
Niels is their a bug report for this one? The spring-4-update branch is ready to merge with a lot of security changes - so any work you are doing here is likely to conflict.

**Comment by NielsCharlier** [comment]
It's a new feature. This can wait.

**Comment by simboss** [comment]
New feature?

No discussion+No proposal+No JIRA=No party!

Joking aside, bypassing project management rules does not really build confidence.

**Comment by NielsCharlier** [comment]
Okay, see https://github.com/geoserver/geoserver/wiki/GSIP-144-- and https://osgeo-org.atlassian.net/browse/GEOS-7473

This is code I had to do anyway that I am contributing back to the project. It is not urgent. I didn't think anyone would object the existence of an LDAP usergroupservice, it doesn't change anything else. I'll put the proposal for vote after the code freeze.

**Comment by NielsCharlier** [comment]
Proposal has enough votes, I have added documentation. This is ready to be reviewed.

**Comment by NielsCharlier** [comment]
Don't see how failures are related

**Comment by jodygarnett** [comment]
@tbarsballe can you kick travis

**Comment by jodygarnett** [comment]
@mcrmcr are you in position to review? You do have a handly LDAP test against ...

**Comment by mcrmcr** [comment]
Hi Jody

At a first glance this looks ok. I have no LDAP test setup at the moment
but i think tests use an internal directory server.

I think merging the pull request will not cause any problems, the
implementation is according to the security plugin architecture.

Cheers

On Tue, May 17, 2016 at 10:31 PM, Jody Garnett <notifications@github.com>
wrote:

> @mcrmcr <https://github.com/mcrmcr> are you in position to review? You do
> have a handly LDAP test against ...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/geoserver/geoserver/pull/1540#issuecomment-219844194>
>



-- 
DI Christian Mueller MSc (GIS), MSc (IT-Security)
OSS Open Source Solutions GmbH

**Comment by jodygarnett** [comment]
Is this ready to go! proposal is approved after all...

**Pull request merged**
