### PR TITLE
WIP on upgrading some dependencies.

### PR DESCRIPTION
**Pull request by bradh**
DO NOT COMMIT

### CODE REVIEW

**Comment by aaime** [comment]
I tried to have a look but run out of time before I could complete. Found the conflict is easily solved, and the following extra change makes the build pass:

```
--- a/src/extension/security/cas/src/main/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilter.java
+++ b/src/extension/security/cas/src/main/java/org/geoserver/security/cas/GeoServerCasAuthenticationFilter.java
@@ -247,7 +247,8 @@ public class GeoServerCasAuthenticationFilter extends GeoServerPreAuthenticatedU
         return "POST".equals(request.getMethod())
                 && CommonUtils.isNotBlank(
                         CommonUtils.safeGetParameter(
-                                request, ConfigurationKeys.LOGOUT_PARAMETER_NAME.getDefaultValue()));
+                                request,
+                                ConfigurationKeys.LOGOUT_PARAMETER_NAME.getDefaultValue()));
     }
```

**Comment by aaime** [comment]
Hi @bradh are you going to work further on this one? (I'm asking only because this was left in WIP state and you switched to other PRs)

**Comment by aaime** [comment]
@bradh I see you closed this, but I'm not sure what it means in terms of work allocation. Do we need to find someone else to look at it, or will you come up with a new pull request replacing this one?

**Comment by bradh** [comment]
Since part of it is done / merged, I will create two new PRs (probably one tonight, my time, and one tomorrow). I may still need some support, but will coord that with the new PRs.

**Comment by aaime** [comment]
Awesome, thanks for letting me know! :)

**Pull request closed without merging**
