### PR TITLE
OGC Tiles module

### PR DESCRIPTION
**Pull request by aaime**
First draft implementation of the OGC Tiles API (still incomplete, but somewhat working already)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by bradh** [comment]
Thanks for the work on this - looking forward to doing some client integration when I get some time.

One suggestion: I think the GWC changes should be broken out as a separate commit for easier review.

**Comment by aaime** [comment]
I just moved some methods in GWC and made them static to allow reuse (seems to be the place for utility methods in gs-gwc), if you think that needs review then I'll clone them in the community module instead... sorry, dealing with brutal deadlines, this could should have been merged yesterday...

**Comment by aaime** [comment]
Oh, forgot to reply about the testing... it is of course welcomed, but I want to warn you, the API is still being defined its definition being changed on a daily basis. Even the features module, that was supposed to be sort of finalized and already got a beta CITE tests developed, has been changed recently the module needs amending. These modules are there to test the API, discuss it, change it, they are a far cry away from anything stable (both the API and code) and are developed prototype style.

**Comment by aaime** [comment]
Merging, but if anyone objects to the method moves in the gs-gwc module I'm more than happy to just clone the code in the community module and restore gs-gwc, just let me know!

**Pull request merged**
