### PR TITLE
GEOS-9460 change to SQL server installation steps

### PR DESCRIPTION
**Pull request by RussellGrew**
Minor documentation change to align with https://osgeo-org.atlassian.net/browse/GEOS-9460

I did ponder removing the Microsoft JDBC section entirely as it is no longer required for stable Geoserver installations.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by aaime** [comment]
I guess the section can indeed be removed entirely, the documentation is versioned along with the code, master is "2.18.x", older version retain the instructions.

**Comment by mprins** [comment]
Yes, I think that whole "Microsoft files" section can just be dropped for master/18.x/17.x branches
I don't see much value talking about old releases but it can't hurt I guess.

Since we're reworking this file it's worth to note that things work just fine for current (2017/2019) releases of sql server

just my 2-cents

**Comment by RussellGrew** [comment]
Thanks Gents.

Please amend the latest commit as you see fit. 

I am a recent Geoserver user. It is great.

**Comment by aaime** [comment]
Looks good to me, merging.

**Pull request merged**
