### PR TITLE
DefaultTileLayerCatalog to mimick the GS own default catalog and keep everything in memory

### PR DESCRIPTION
**Pull request by aaime**
One last speedup to the integrated GWC, allows to startup the 40k layers sample data dir within 45s on a hot cache.
Rationale: the DefaultCatalogFacade is fully memory based, there is no reason not to have the same for the DefaultTileLayerCatalog. A jdbc based configuration should have its own JDBC based alternative (I have the strong impression that JDBCConfig is not actually used in combination with embedded GWC anyways)

### CODE REVIEW

**Comment by ianturton** [comment]
I notice you aren't using a ConcurentHashMap in the parallel stream section any more - I assume this is ok with the two Maps? Otherwise it looks much cleaner and I can believe it's faster though I haven't tested it.

**Comment by aaime** [comment]
The local ConcurrentHashMap has been removed because it has been replaced by a field that's a ConcurrentHashMap. Before it was there because the "syncronized bimap" was killing scalability in the parallel stream.

**Comment by aaime** [comment]
The build failure in the "WCS netcdf output format" is unrelated, looks like this branch got caught in an API change:

{code}
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStore.java:[19,24] error: cannot find symbol
[ERROR]  package org.geotools.data
/home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStore.java:[20,24] error: cannot find symbol
[ERROR]  package org.geotools.data
/home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStore.java:[69,39] error: cannot find symbol
[ERROR]  class AbstractDataStore
/home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStoreFactory.java:[20,15] error: incompatible types: MultiDimDataStore cannot be converted to DataStore
[ERROR] /home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStore.java:[140,4] error: method does not override or implement a method from a supertype
[ERROR] /home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStore.java:[145,4] error: method does not override or implement a method from a supertype
[ERROR] /home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStore.java:[168,4] error: method does not override or implement a method from a supertype
[ERROR] /home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStore.java:[348,4] error: method does not override or implement a method from a supertype
[ERROR] /home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStore.java:[388,17] error: cannot find symbol
[ERROR]  class MultiDimDataStore
/home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStore.java:[413,4] error: method does not override or implement a method from a supertype
[ERROR] /home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStore.java:[415,12] error: cannot find symbol
[ERROR]  class MultiDimDataStore
/home/travis/build/geoserver/geoserver/src/extension/netcdf-out/src/test/java/org/geoserver/wcs2_0/MultiDimDataStore.java:[415,34] error: cannot find symbol
[INFO] 12 errors 
[INFO] ---------------------
{code}

**Comment by aaime** [comment]
Yep, removing AbstractDataStore broke the build exactly in that module (on Ares too). Merging, no need to wait for that to be fixed (I guess @jodygarnett &co will handle this tomorrow)

**Pull request merged**
