### PR TITLE
[2.19.x Backport]Fix sphinx build warnings indicating where extlinks can be used  (#5593)

### PR DESCRIPTION
**Pull request by yashwanthanands**
* fix up developer guide links

Signed-off-by: Jody Garnett <jody.garnett@gmail.com>

* remove gml it is no longer available

Signed-off-by: Jody Garnett <jody.garnett@gmail.com>

* Fix extlink warnings, mostly extension download links

Signed-off-by: Jody Garnett <jody.garnett@gmail.com>

* Fix zhCN docs

Signed-off-by: Jody Garnett <jody.garnett@gmail.com>

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by yashwanthanands** [comment]
@taba90 

[2.19.x Backport]Fix sphinx build warnings indicating where extlinks can be used (#5593)

**Comment by aaime** [comment]
Still one legit failure:

```
sphinx:
     [echo] Running sphinx-build -D release=2.19-SNAPSHOT -W -b html -d "/home/runner/work/geoserver/geoserver/doc/en/target/user/doctrees" . "/home/runner/work/geoserver/geoserver/doc/en/target/user/html"
     [exec] /home/runner/work/geoserver/geoserver/doc/en/user/source/community/imagemosaic-jdbc/index.rst:13: WARNING: hardcoded link 'http://geoserver.org/download' could be replaced by an extlink (try using ':website:`download`' instead)
```

This one is not happening in 2.20.x because the imagemosaic-jdbc module was removed there.

**Comment by ianturton** [comment]
This is now failing on `user/source/services/csw/installing.rst` which needs line 8 fixing to 

    #. Visit the GeoServer :website:`download` page and navigate to the download page for the version of GeoServer

**Comment by yashwanthanands** [comment]
Thanks for the review. Feedback has been applied.

**Comment by aaime** [comment]
Thanks, merged.

**Pull request merged**
