### PR TITLE
[GEOS-8813] Add support for WMTS layers to GeoFence plugin

### PR DESCRIPTION
**Pull request by tbarsballe**
See https://osgeo-org.atlassian.net/browse/GEOS-8813

When WMTS was added to GeoServer
 a) GeoFence was not updated with support for it
 b) The GeoServer Security subsystem was only updated to include minimal support for it.

This fixes both these issues, and as a result, the linked bug (The geofence changes are split into a separate commit from the core api changes).

Note: This fix required nontrivial API changes to the core WMTSLayerInfo API (so that SecuredWMTSLayer would actually delegate to the wrapped WMTSLayer properly). 

(Now that Planet Federal has a signed CLA again, I've got a bit of a backlog of bugfixes I'm contributing. Obviously, merging them is going to have to wait until the build server is working again)

### CODE REVIEW

**Comment by gtbuildergh** [comment]
Looks like we have legit test failures:

```
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.644 sec <<< FAILURE!
testWmsLimited(org.geoserver.geofence.AccessManagerWMTSLayerTest)  Time elapsed: 2604 sec  <<< ERROR!
com.google.common.util.concurrent.UncheckedExecutionException: org.springframework.remoting.RemoteConnectFailureException: Could not connect to HTTP invoker remote service at [http://localhost:9191/geofence/remoting/RuleReader]; nested exception is java.net.ConnectException: Connection refused (Connection refused)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at org.geoserver.geofence.cache.CachedRuleReader.getAccessInfo(CachedRuleReader.java:23
```

**Comment by tbarsballe** [comment]
Indeed, this was working locally, might be an issue with how the GeoFence online tests are configured (I think that test isn't supposed to run if there isn't also a GeoFence instance running). I'll look into it.

**Comment by tbarsballe** [comment]
Failure fixed (the test teardown was incorrectly still running when the test was online). All tests are passing now.

**Comment by tbarsballe** [comment]
Updated to fix merge conflicts.

**Comment by aaime** [comment]
@afabiani or @etj could you review this one?

**Comment by simboss** [comment]
@etj are we then merging or not ? :)

**Pull request merged**
