### PR TITLE
Adjust for change of Matrix library (GEOS-7009)

### PR DESCRIPTION
**Pull request by jodygarnett**
Adjust expected result test result for GetFeatureInfo test due to difference in transform accuracy.

This request requires that https://github.com/geotools/geotools/pull/829 be applied first

### CODE REVIEW

**Comment by aaime** [comment]
Please allow for some more time to review. I was too busy trying to get the windows server going and the build sped up to look at this one.

**Comment by aaime** [comment]
See review on the mailing list, the shift is too big, there is something going on that we need to understand better. Please do not merge this one.

**Comment by jodygarnett** [comment]
Understood, I have only observed differences in invert result. I could use a hand here as I am a bit out of my depth on the math front.

**Comment by jodygarnett** [comment]
merged just the change to the pom.xml organization.

**Pull request merged**
