### PR TITLE
Bump junit from 4.12 to 4.13.1 in /src, fix deprecated methods and tidy Assert.* imports 

### PR DESCRIPTION
**Pull request by ianturton**
This bumps the JUnit version to the latest version, fixes the deprecations that have popped up in that change. 

I have also tidied up all the old import Assert.* that were scattered about - this way future deprecation changes should become a simple sed find and replace rather than hours of hunt the method call in Eclipse. 

I have a PDM rule we can add to prevent this in future but PDM fails with dozens of errors on gs-main currently so I gave up messing with it.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [x] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by aaime** [comment]
Interesting, tell me more about that PMD rule?

**Comment by ianturton** [comment]
`<rule name="wildcards" language="java" message="No Wildcard Imports" class="net.source  forge.pmd.lang.rule.XPathRule">     <description>Don't use wildcard imports
      </description>
     <priority>3</priority>
     <properties>
       <property name="version" value="2.0"/>
       <property name="xpath">
         <value><![CDATA[
           //ImportDeclaration[@ImportedName=@PackageName]
           ]]></value>
       </property>
     </properties>
_  </rule>`

**Review by mprins — APPROVED** [review]
Not sure if changing imports on a half-K of files requires a Jira ticket, since that is mostly codestyling; you might want to squash-merge tho.

:+1: for the effort

**Review by aaime — APPROVED** [review]
Looks good to me.

**Pull request merged**
