### PR TITLE
Hazelcast based clustering module

### PR DESCRIPTION
**Pull request by jdeolive**

### CODE REVIEW

**Comment by jodygarnett** [comment]
@aaime are you in position to review this one? I know it is only a community module...

**Comment by aaime** [comment]
Jody, not sure I can, I'm swamped as I have get color compositing and blending in before the beta...

**Comment by jodygarnett** [comment]
Understood, and the beta is supposed to be a code freeze... let us see if this hits any of the core modules.

**Comment by jodygarnett** [comment]
Okay this pull request is limited to a community module - however I note a lot of the headers are empty. I think at a minimum I would like them filled in with today's date (so we do not have any IP questions in the future).

**Comment by smithkm** [comment]
Was merged outside of pull request by @jodygarnett

**Comment by jodygarnett** [comment]
Yeah had to add the headers

**Pull request closed without merging**
