### PR TITLE
Get debug output from Maven, might help understand the snapshot retrieval issue (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by aaime**
PLEASE DO NOT MERGE!
(but cannot do "draft" PR, Travis does not build them AFAIK).

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by aaime** [comment]
The OSX build failed immediately without finding the gwc-core snapshot information:

```
2020-08-24T17:05:52.4180220Z [DEBUG] Could not find metadata org.geowebcache:gwc-core:1.18-SNAPSHOT/maven-metadata.xml in local (/Users/runner/.m2/repository)
2020-08-24T17:05:52.4191380Z [DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.osgeo.org/repository/snapshot/
2020-08-24T17:05:52.4193840Z [DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.osgeo.org/repository/snapshot/
2020-08-24T17:05:52.4198670Z [INFO] Downloading from osgeo-snapshots: https://repo.osgeo.org/repository/snapshot/org/geowebcache/gwc-core/1.18-SNAPSHOT/maven-metadata.xml
2020-08-24T17:05:52.7558240Z [DEBUG] Writing tracking file /Users/runner/.m2/repository/org/geowebcache/gwc-core/1.18-SNAPSHOT/resolver-status.properties
2020-08-24T17:05:52.7967350Z [DEBUG] Could not find metadata org.geowebcache:gwc-core:1.18-SNAPSHOT/maven-metadata.xml in osgeo-snapshots (https://repo.osgeo.org/repository/snapshot/)
2020-08-24T17:05:52.7969620Z [DEBUG] Could not find metadata org.geowebcache:gwc-core:1.18-SNAPSHOT/maven-metadata.xml in local (/Users/runner/.m2/repository)
2020-08-24T17:05:52.7976010Z [DEBUG] Skipped remote request for org.geowebcache:gwc-core:1.18-SNAPSHOT/maven-metadata.xml, already updated during this session.
2020-08-24T17:05:52.7980460Z [DEBUG] Failure to find org.geowebcache:gwc-core:1.18-SNAPSHOT/maven-metadata.xml in https://repo.osgeo.org/repository/snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of osgeo-snapshots has elapsed or updates are forced
2020-08-24T17:05:52.7995840Z [DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.osgeo.org/repository/snapshot/
2020-08-24T17:05:52.7998730Z [DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.osgeo.org/repository/snapshot/
2020-08-24T17:05:52.8003970Z [INFO] Downloading from osgeo-snapshots: https://repo.osgeo.org/repository/snapshot/org/geowebcache/gwc-core/1.18-SNAPSHOT/gwc-core-1.18-SNAPSHOT.pom
2020-08-24T17:05:53.1401930Z [DEBUG] Writing tracking file /Users/runner/.m2/repository/org/geowebcache/gwc-core/1.18-SNAPSHOT/gwc-core-1.18-SNAPSHOT.pom.lastUpdated
2020-08-24T17:05:53.1824760Z [WARNING] The POM for org.geowebcache:gwc-core:jar:1.18-SNAPSHOT is missing, no dependency information available
2020-08-24T17:05:53.1891900Z [DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=609695, ConflictMarker.markTime=228032, ConflictMarker.nodeCount=97, ConflictIdSorter.graphTime=129915, ConflictIdSorter.topsortTime=31021, ConflictIdSorter.conflictIdCount=38, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=4527636, ConflictResolver.conflictItemCount=78, DefaultDependencyCollector.collectTime=50912305681, DefaultDependencyCollector.transformTime=5644023}
```
Says it cannot find this file:
https://repo.osgeo.org/repository/snapshot/org/geowebcache/gwc-core/1.18-SNAPSHOT/maven-metadata.xml

And indeed I tried from my browser, it's not there:
image

Going through the HTML index interface of Nexus, I get:

image

And yet looking at the logs of the [last GWC master build](https://build.geoserver.org/view/geowebcache/job/geowebcache-master/105/consoleText), I see:

```
Uploaded to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-diskquota/1.18-SNAPSHOT/maven-metadata.xml (603 B at 478 B/s)
Uploading to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-diskquota/maven-metadata.xml
Progress (2): 1.2 MB | 400 B
                            
Uploaded to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-core/1.18-SNAPSHOT/gwc-core-1.18-20200824.125737-5.jar (1.2 MB at 563 kB/s)
Uploading to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-core/1.18-SNAPSHOT/gwc-core-1.18-20200824.125737-5.pom
Progress (2): 400 B | 4.1/5.8 kB
Progress (2): 400 B | 5.8 kB    
                            
Uploaded to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-diskquota/maven-metadata.xml (400 B at 314 B/s)
Uploading to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-diskquota/1.18-SNAPSHOT/gwc-diskquota-1.18-20200824.125735-1-tests.jar
Progress (2): 5.8 kB | 2.0 kB
                             
Uploaded to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-core/1.18-SNAPSHOT/gwc-core-1.18-20200824.125737-5.pom (5.8 kB at 4.9 kB/s)
Downloading from nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-core/maven-metadata.xml
Progress (2): 2.0 kB | 395 B
                            
Downloaded from nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-core/maven-metadata.xml (395 B at 783 B/s)
Uploading to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-core/1.18-SNAPSHOT/maven-metadata.xml
Progress (2): 2.0 kB | 1.2 kB
                             
Uploaded to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-diskquota/1.18-SNAPSHOT/gwc-diskquota-1.18-20200824.125735-1-tests.jar (2.0 kB at 1.7 kB/s)
Uploading to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-diskquota/1.18-SNAPSHOT/maven-metadata.xml
Progress (2): 1.2 kB | 814 B
                            
Uploaded to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-core/1.18-SNAPSHOT/maven-metadata.xml (1.2 kB at 995 B/s)
Uploading to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-core/maven-metadata.xml
Progress (2): 814 B | 395 B
                           
Uploaded to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-diskquota/1.18-SNAPSHOT/maven-metadata.xml (814 B at 669 B/s)
Uploaded to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-core/maven-metadata.xml (395 B at 298 B/s)
Uploading to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-core/1.18-SNAPSHOT/gwc-core-1.18-20200824.125737-5-tests.jar
```

So the file has been uploaded, ``Uploaded to nexus: https://repo.osgeo.org/repository/geoserver-snapshots/org/geowebcache/gwc-core/maven-metadata.xml (395 B at 298 B/s)``, and yet it's no more there??

@jodygarnett it's as if something was cleaning up the files somehow....

**Comment by jodygarnett** [comment]
We experimented with two approaches:

* Checking policy: (not used as this resulted in artifacts that were not used frequently being removed)
image

* Delete task: keep at least one snapshot, felete all snapshots older than two days, provided we still keep the minimum number 1 specified.

image

**Comment by jodygarnett** [comment]
Checking recent logs:
```
2020-08-24 18:00:00,009+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.quartz.internal.task.QuartzTaskInfo - Task 'geoserver snapshot cleanup' [repository.maven.remove-snapshots] state change WAITING -> RUNNING
2020-08-24 18:00:00,012+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.tasks.RemoveSnapshotsTask - Task information:
2020-08-24 18:00:00,012+0000 INFO  [quartz-7-thread-20]  *SYSTEM org.sonatype.nexus.quartz.internal.task.QuartzTaskInfo - Task 'Storage facet cleanup' [repository.storage-facet-cleanup] state change RUNNING -> WAITING (OK)
2020-08-24 18:00:00,078+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.tasks.RemoveSnapshotsTask -  ID: ac811210-fdee-4a51-b03e-ae51e0b3afcc
2020-08-24 18:00:00,078+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.tasks.RemoveSnapshotsTask -  Type: repository.maven.remove-snapshots
2020-08-24 18:00:00,078+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.tasks.RemoveSnapshotsTask -  Name: geoserver snapshot cleanup
2020-08-24 18:00:00,078+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.tasks.RemoveSnapshotsTask -  Description: Remove Maven snapshots from geoserver-snapshots
2020-08-24 18:00:00,093+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.tasks.RemoveSnapshotsTask - Task log: /nexus-data/log/tasks/repository.maven.remove-snapshots-20200824180000012.log
2020-08-24 18:00:00,093+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.tasks.RemoveSnapshotsTask - Executing removal of snapshots on repository 'geoserver-snapshots'
2020-08-24 18:00:00,093+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.internal.orient.RemoveSnapshotsFacetImpl - Beginning snapshot removal on repository 'geoserver-snapshots' with configuration: RemoveSnapshotsConfig{minimumRetained=1, snapshotRetentionDays=2, removeIfReleased=false, gracePeriod=-1}
2020-08-24 18:00:00,093+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.internal.orient.RemoveSnapshotsFacetImpl - Begin processing snapshots in repository 'geoserver-snapshots'
2020-08-24 18:00:00,094+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.internal.orient.RemoveSnapshotsFacetImpl - Searching for GAVS with snapshots that qualify for deletion on repository 'geoserver-snapshots'
2020-08-24 18:00:00,145+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.internal.orient.RemoveSnapshotsFacetImpl - Found 626 snapshot GAVs to analyze
2020-08-24 18:00:01,648+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.internal.orient.RemoveSnapshotsFacetImpl - Elapsed time: 1.502 s, deleted 0 components from 0 distinct GAVs
2020-08-24 18:00:01,648+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.internal.orient.RemoveSnapshotsFacetImpl - Finished processing snapshots with more than 1 versions created before 2020-08-22T18:00:01.648Z
2020-08-24 18:00:01,648+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.internal.orient.RemoveSnapshotsFacetImpl - Updating metadata on repository 'geoserver-snapshots'
2020-08-24 18:00:01,648+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.internal.orient.RemoveSnapshotsFacetImpl - Completed snapshot removal on repository 'geoserver-snapshots'
2020-08-24 18:00:01,649+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.repository.maven.tasks.RemoveSnapshotsTask - Task complete
2020-08-24 18:00:01,649+0000 INFO  [quartz-7-thread-18]  *SYSTEM org.sonatype.nexus.quartz.internal.task.QuartzTaskInfo - Task 'geoserver snapshot cleanup' [repository.maven.remove-snapshots] state change RUNNING -> WAITING (OK)
```

**Comment by jodygarnett** [comment]
Great now it is failing on:

>  Failed to execute goal on project gs-main: Could not resolve dependencies for project org.geoserver:gs-main:jar:2.18-SNAPSHOT: Could not find artifact net.sf.json-lib:json-lib:jar:2.4.2-geoserver in osgeo-releases (https://repo.osgeo.org/repository/release/)

I can no longer find this in the repository.

But I do have it locally:

```
-rw-r--r--  1 jgarnett  staff  136800 29 May 16:23 json-lib-2.4.2-geoserver.jar
```

**Comment by jodygarnett** [comment]
Okay I am stuck on this one, anyone else got ideas?

**Comment by aaime** [comment]
json-lib is available in central: https://repo1.maven.org/maven2/net/sf/json-lib/json-lib/2.4/
So in theory, it should be picked from there. However, looking at the geoserver main pom, I see:

```
   <dependency> 
     <groupId>net.sf.json-lib</groupId> 
     <artifactId>json-lib</artifactId>
     <version>2.4.2-geoserver</version>
   </dependency>
   <dependency>
```

So we are depending on a customized version of it (yes, there was  discussion about it, to solve a bug). I think it's placed on the geosolutions repo.. yep:
http://maven.geo-solutions.it/net/sf/json-lib/json-lib/2.4.2-geoserver/

In this PR I tried removing it since you told us it was getting mirrored... but apparently, it's not?
I'm going to revert that change, the GeoSolutions repository is evidently required for the build to work.

**Comment by aaime** [comment]
Added back the GeoSolutions repo, this time it failed on a different artifact:

```
[ERROR] Failed to execute goal on project geoserver: Could not resolve dependencies for project org.geoserver:geoserver:pom:2.18-SNAPSHOT: Failed to collect dependencies at org.geotools:gt-main:jar:24-SNAPSHOT: Failed to read artifact descriptor for org.geotools:gt-main:jar:24-SNAPSHOT: Could not find artifact org.geotools:library:pom:24-SNAPSHOT in osgeo-snapshots (https://repo.osgeo.org/repository/snapshot/) -> [Help 1]
```

and indeed, ``maven-metadata.xml`` is gone here:

image

Location (byt the time you go there, it might be fixed):
https://repo.osgeo.org/service/rest/repository/browse/snapshot/org/geotools/library/24-SNAPSHOT/

**Comment by jodygarnett** [comment]
backed off snapshot cleanup tasks:
* occur less often
* keep at least 2 snapshots
* remove any snapshots older than 5 days

**Comment by jodygarnett** [comment]
Okay reading this: https://stackoverflow.com/questions/50266844/maven-metadata-xml-is-not-found-in-nexus

It appears there is a scheduled task to generate any `maven-metadata.xml` files if they are missing as a result of error.

* creating a task for geoserver-snapshots repository, running manually

**Comment by jodygarnett** [comment]
After running the cleanup https://repo.osgeo.org/service/rest/repository/browse/snapshot/org/geotools/library/24-SNAPSHOT/

Shows
```
Parent Directory
24-20200824.095738-1 
24-20200824.120519-2 
24-20200825.215825-1
maven-metadata.xml           Tue Aug 25 22:08:36 UTC 2020   590  
maven-metadata.xml.md5  Tue Aug 25 22:08:36 UTC 2020     32
maven-metadata.xml.sha1  Tue Aug 25 22:08:36 UTC 2020     40
```

So I think this is "working" and will allow us to resolve the problem if it appears in the future.

**Pull request closed without merging**
