### PR TITLE
Resolve geoserverBaseDir maven property using standard means

### PR DESCRIPTION
**Pull request by groldan**
Use the standard (since maven 3.3.1) `${maven.multiModuleProjectDirectory}` expression to resolve the `geoserverBaseDir` property, replacing the `org.commonjava.maven.plugins:directory-maven-plugin` plugin.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Review by bradh — APPROVED** [review]

**Comment by aaime** [comment]
Had a look around regarding version compatibility:
- The documentation does not seem to say which version is supported, 3.3.1 has been released in 2015
- The Jenkins build server is using a 3.6.3

So... looks good, nice to depend on one less plugin (I remember having issues with some tools because the directory plugin was not running soon enough).

**Comment by aaime** [comment]
The backport to `2.23.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 969edb1035... Resolve geoserverBaseDir maven property using standard means
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging src/pom.xml
CONFLICT (content): Merge conflict in src/pom.xml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-2.23.x 2.23.x
# Navigate to the new working tree
cd .worktrees/backport-2.23.x
# Create a new branch
git switch --create backport-7165-to-2.23.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 969edb1035ce912587eafcd5be76df0fabc6e8d8
# Push it to GitHub
git push --set-upstream origin backport-7165-to-2.23.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-2.23.x
```
Then, create a pull request where the `base` branch is `2.23.x` and the `compare`/`head` branch is `backport-7165-to-2.23.x`.

**Comment by aaime** [comment]
The backport to `2.24.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 969edb1035... Resolve geoserverBaseDir maven property using standard means
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging src/pom.xml
CONFLICT (content): Merge conflict in src/pom.xml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-2.24.x 2.24.x
# Navigate to the new working tree
cd .worktrees/backport-2.24.x
# Create a new branch
git switch --create backport-7165-to-2.24.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 969edb1035ce912587eafcd5be76df0fabc6e8d8
# Push it to GitHub
git push --set-upstream origin backport-7165-to-2.24.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-2.24.x
```
Then, create a pull request where the `base` branch is `2.24.x` and the `compare`/`head` branch is `backport-7165-to-2.24.x`.

**Comment by aaime** [comment]
And... reverting right away too... Sigh!
Semantically the variable is not the same thing, it provides the root of the build from where it got started, not from the actual root of the multimodule tree.

This is turn breaks the QA build, when it's run from a single module. Example from wps-core:

```
[INFO] --- maven-pmd-plugin:3.14.0:pmd (pmd) @ gs-wps-core ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:23 min
[INFO] Finished at: 2023-10-07T11:32:25+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.14.0:pmd (pmd) on project gs-wps-core: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.14.0:pmd failed: org.apache.maven.reporting.MavenReportException: Could not find resource '/home/aaime/devel/git-gs/src/extension/wps/wps-core/../build/qa/pmd-ruleset.xml'. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

```

**Comment by aaime** [comment]
thinking out loud, the QA build can likely work off configurations stored in their own module, and accessed via classpath. Although, I guess such module would have to be outside of the normal build, to avoid a circularity when using the QA profile? Just thinking out loud, mind, can be easily wrong.

**Comment by groldan** [comment]
holy s. I was so sure it'd always resolve to the root pom's directory. Sorry about that.

**Pull request merged**
