### PR TITLE
Remove unsupported GeoMesa community module

### PR DESCRIPTION
**Pull request by elahrvivaz**
The GeoMesa community module has not been updated in years. GeoMesa integration is fully described in the separate GeoMesa [documentation](https://www.geomesa.org/documentation/stable/user/geoserver.html).
  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by elahrvivaz** [comment]
Would there be any place in the documentation to reference related projects that aren't community modules? I.e. a place that would be appropriate to link to GeoMesa? Thanks,

**Comment by aaime** [comment]
We actually don't have a place for that... maybe we should create one. Thinking out loud, a section for "other modules" in our guide, @jodygarnett what do you think? 

We could stick the GeoStyler external plugin there too (right now they have [updated the old community page to point to it](https://docs.geoserver.org/latest/en/user/community/geostyler/index.html), but I believe a dedicated  section would be better).

**Comment by jodygarnett** [comment]
I don’t know; I am frustrated by the lack of participation. The community project approach was one of the initiatives we used to be welcoming to new contributors; it has a mixed track record with some modules graduating quickly; and others in a holding pattern (used but not attracting investment enough to be completed).

I think the PSC has to negotiate a bit more strongly (we only have 2 sponsors presently).

But let me try and be positive; the user documentation may not be the best spot; but the website “Downloads” page may be appropriate, and extra tab linking to compatible stuff. Some thought would be needed so these could clearly indicate compatibility.

**Comment by aaime** [comment]
@jodygarnett I think the community area is working fine, we get lots of action, it's normal that some stuff graduates, other do not, and some just die or leave. I believe the community section has more modules than we have in supported: it's a game of numbers, if only 10% of them manage to become supported it's worth it IMHO.

The download page is an idea, but when a module is controlled outside, it's not easy to find out which module is compatible with which version of GeoServer... I'd have it somewhere in a more general section, don't know, "Friends of GeoServer". We do clearly state that we don't have a say in what happens over there, we don't test them, and we cannot provide support, but users are free to follow the link and see if they find something useful.

**Comment by jodygarnett** [comment]
What about on the download page having:

* Production: active stable and maintenance 
* Development: remove this it was only useful for milestones and RCs, nightly builds are available from “Production” already
* Archive: generated 
* External: let GeoMesa and others be added here

Optional: Make a page for GeoMesa with metadata indicating what versions are supported. Use that to add a “geomesa” link to releases of GeoServer that they are compatible with. Pros: encourage and promote up to date external plugins, no effort to depreciate us maintained external modules. Cons: would provide a better experience over community modules

**Comment by aaime** [comment]
@jodygarnett I would go for the download links change, but I'd also keep Development there, in my circles reaching out to the development series is common for a subset of partners (research institutes mainly). Pheraps the "main" bit should be articulated a bit more, with indication that it's not meant for production, but great to try the latest innovations.

And then yes, I would add an "external" for GeoMesa and GeoStyler, with also a note that anyone maintaining a module in an external repository can push a PR to add theirs, but also that the GeoServer community is not involved in their development, and any question should go directly to the external repository.

**Comment by aaime** [comment]
Merging the removal in the meantime, it's a clean PR and the geomesa plugin was not part of the community nightly build anyways.

**Comment by elahrvivaz** [comment]
Thanks guys - is there any follow up you'd like to see from me/GeoMesa regarding the other changes you've been discussing here?

**Comment by jodygarnett** [comment]
I guess I would like your opinion @elahrvivaz - for the GeoMesa project, and your employer, what is a good fit?

**Pull request merged**
