### PR TITLE
OGC API styling improvements

### PR DESCRIPTION
**Pull request by MichelGabriel**
This PR has style changes/improvements for OGC API:
- introduced Bootstrap CSS
- uniform look
- removed unused CSS
- added map placeholder
- added grid layout
- added/restyled breadcrumbs
- improved responsiveness
- styling for `Styles`, `Tiles` and `DGGS`

**Screenshot of the new landing page**

gs-ogcapi-landing

**Screenshot of the collections**

gs-ogcapi-collections
ons

**Screenshot of the collection**

gs-ogcapi-collection

**Screenshot of the feature page**

gs-ogcapi-feature

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [x] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by aaime** [comment]
@MichelGabriel quite the nice improvement. I've found one case where things are not working as nice as the old UI, it's the HTML view when having several attributes. Here is the ``topp:states`` layer, which has a lot of them:

image

Only a few are visible, I see no way to scroll (besides starting a selection and dragging, which is not very usable):

image

Actually after looking at this I've found there is a scrollbar at the bottom, but it's too far away to be easily noticed:

image

Is there a quick fix for this? Don't know, maybe removing the preview placehoder for example, and allow the table to use the whole page?

**Comment by aaime** [comment]
Oh BTW, the QA build failure is unrelated, you can rebase to the current master to get rid of that one.

**Comment by MichelGabriel** [comment]
> Is there a quick fix for this? Don't know, maybe removing the preview placehoder for example, and allow the table to use the whole page?

I don't know about a quick fix, but I will fix it.

**Comment by MichelGabriel** [comment]
The table is now full width, and some further improvements were made to the responsiveness of the `collections` pages.

**Less columns on smaller pages:**

gs-ogcapi-collections-small

gs-ogcapi-collections-medium

**Comment by aaime** [comment]
Ah yes, love how the collection page scales down. Checked table, also good. Merging.

**Pull request merged**
