### PR TITLE
API change for JDBC Resource Store [GSIP-136]

### PR DESCRIPTION
**Pull request by NielsCharlier**
See GSIP-136. This PR will still be updated according to proposal changes/approval

### CODE REVIEW

**Comment by jodygarnett** [comment]
Please email geoserver-devel to review/approve the proposal :)

**Comment by NielsCharlier** [comment]
No, just your latest changes to the proposal

**Comment by NielsCharlier** [comment]
this is ready now.

**Comment by bencaradocdavies** [comment]
@NielsCharlier that looks all good. I also ran a full local build, communityRelease compile, and built the jdbcconfig and jdbcstore modules.

I note that upgrade to Java 7 WatchService is desirable but, as discussed, out of scope.

**Pull request merged**
