### PR TITLE
[GEOS-9611] Upgrade from Apache Common Collections v3 to v4

### PR DESCRIPTION
**Pull request by aaime**
Follows up with https://github.com/geotools/geotools/pull/2796

The changes involve only supported modules for the moment. The old and new libraries can coexist, but have to check if the war still contains the old one, otherwise the community modules packaging instructions would have to be updated.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [x] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [x] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by soc** [comment]
`MultiValueMap` → `MultiValuedMap` :-)

**Comment by aaime** [comment]
Checked, gs-main still depends to commons-collections 3.x via json-lib, so the jar stays in the release package. Which means, the community modules do not need to be fixed right now.

**Comment by soc** [comment]
@aaime I did a migration of `net.sf.json-lib` to `org.json` a while ago in an unrelated project, maybe that's an option here, too?

**Comment by aaime** [comment]
Afraid not, it's not GPL compatible (just found out): https://www.json.org/license.html and https://github.com/stleary/JSON-java/blob/master/LICENSE

In particular, due to this restriction "The Software shall be used for Good, not Evil."
Well meaning for sure, but impractical to apply.

Checked out dependencies, GWC REST module actually uses it, it should be removed.
I've opened a ticket about it: https://github.com/GeoWebCache/geowebcache/issues/850

**Pull request merged**
