### PR TITLE
Release documentation improvements

### PR DESCRIPTION
**Pull request by bencaradocdavies**
@jodygarnett  @aaime @jdeolive  quick sanity check: added branching instructions and GitHub Pages reference to release guide

### CODE REVIEW

**Comment by bencaradocdavies** [comment]
I made a few improvements to the GitHub pages README. I am not sure if it is clear enough. But it is the information I needed to make the last release:
https://github.com/geoserver/geoserver.github.io

**Comment by aaime** [comment]
For some reason I though the release scripts were going to create the branch? Of course I might be wrong, I think RCs were always handled by jdeolive (and I might be wrong here too).

**Comment by bencaradocdavies** [comment]
@aaime, as far as I know, the release scripts are run by Jenkins to perform a release from a branch, but do not create the branch itself. The scripts make a small local-only release branch (eg rel_2.7-RC1), update versions on this branch from SNAPSHOT to the release version, and tag. The Jenkins publish phase pushes the tag but not the release branch. The process I described was how I made the 2.7.x branch and 2.7-RC1 release, and everything seemed to work. If I have misunderstood, now would be a great time to be corrected.

Release process and documentation is there to relieve @jdeolive of sole responsibility fir dirty jobs such as the creation of new branches. @jodygarnett has been active in recruiting new release engineers for this purpose. :-)

**Comment by jgarnett** [comment]
Can I get off this list please? These emails are coming to me in error.

Thanks.

**Comment by bencaradocdavies** [comment]
Sorry @jgarnett, my bad, I tagged the wrong user. I have fixed the other pull request where I did this. You should be able to unsubscribe by pressing the Unsubscribe button on the right hand side.

Kind regards,
Ben.

**Pull request merged**
