### PR TITLE
[Community] security oauth2 release collects the wrong spring-security-oauth2 version of the JARs

### PR DESCRIPTION
**Pull request by afabiani**
Despite the version is correctly defined into the `openid-connect` module, due to those old ones the community release collector fetches the wrong ones.
  

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
Can we have the version defined once and for all in the main pom file?

**Comment by afabiani** [comment]
> Can we have the version defined once and for all in the main pom file? E.g., dependency management. And then remove the version from all the module specific pom files.

@aaime sure, even better... shall we need a JIRA for that?

**Review by mprins — APPROVED** [review]
it's unfortunate that we cannot use `spring.security.version` as that seems to have a different release cycle

**Comment by afabiani** [comment]
@aaime @mprins I have been updated the PR by pushing up the dependency management

**Comment by aaime** [comment]
The backport to `2.21.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply c452460328...  - Pushing the "spring-security-oauth2" dependency to the main pom.xml
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging src/community/security/oauth2-geonode/pom.xml
Auto-merging src/community/security/oauth2-github/pom.xml
Auto-merging src/community/security/oauth2-google/pom.xml
[backport-6694-to-2.21.x 4bdf2fb0ca] [Community] security oauth2 release collects the wrong spring-security-oauth2 version of the JARs
 Author: afabiani <alessio.fabiani@geosolutionsgroup.com>
 Date: Tue Mar 21 14:34:01 2023 +0100
 3 files changed, 3 insertions(+), 3 deletions(-)
Auto-merging src/community/security/oauth2-geonode/pom.xml
Auto-merging src/community/security/oauth2-github/pom.xml
Auto-merging src/community/security/oauth2-google/pom.xml
Auto-merging src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
Auto-merging src/community/security/oauth2/oauth2-core/pom.xml
Auto-merging src/pom.xml
CONFLICT (content): Merge conflict in src/pom.xml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-2.21.x 2.21.x
# Navigate to the new working tree
cd .worktrees/backport-2.21.x
# Create a new branch
git switch --create backport-6694-to-2.21.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 1b511c6689a039258d0e197dc98f9030d0cc5588,c452460328a34e2987c668db20e0110048e4909a
# Push it to GitHub
git push --set-upstream origin backport-6694-to-2.21.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-2.21.x
```
Then, create a pull request where the `base` branch is `2.21.x` and the `compare`/`head` branch is `backport-6694-to-2.21.x`.

**Comment by aaime** [comment]
The backport to `2.22.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply c452460328...  - Pushing the "spring-security-oauth2" dependency to the main pom.xml
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging src/community/security/oauth2-geonode/pom.xml
Auto-merging src/community/security/oauth2-github/pom.xml
Auto-merging src/community/security/oauth2-google/pom.xml
[backport-6694-to-2.22.x f8ac35679e] [Community] security oauth2 release collects the wrong spring-security-oauth2 version of the JARs
 Author: afabiani <alessio.fabiani@geosolutionsgroup.com>
 Date: Tue Mar 21 14:34:01 2023 +0100
 3 files changed, 3 insertions(+), 3 deletions(-)
Auto-merging src/community/security/oauth2-geonode/pom.xml
Auto-merging src/community/security/oauth2-github/pom.xml
Auto-merging src/community/security/oauth2-google/pom.xml
Auto-merging src/community/security/oauth2-openid-connect/oauth2-openid-connect-core/pom.xml
Auto-merging src/community/security/oauth2/oauth2-core/pom.xml
Auto-merging src/pom.xml
CONFLICT (content): Merge conflict in src/pom.xml

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-2.22.x 2.22.x
# Navigate to the new working tree
cd .worktrees/backport-2.22.x
# Create a new branch
git switch --create backport-6694-to-2.22.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 1b511c6689a039258d0e197dc98f9030d0cc5588,c452460328a34e2987c668db20e0110048e4909a
# Push it to GitHub
git push --set-upstream origin backport-6694-to-2.22.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-2.22.x
```
Then, create a pull request where the `base` branch is `2.22.x` and the `compare`/`head` branch is `backport-6694-to-2.22.x`.

**Comment by afabiani** [comment]
backports done

**Pull request merged**
