### PR TITLE
[GEOS-9397] Cached layers page may take minutes to show up (when backing stores are not responsive)

### PR DESCRIPTION
**Pull request by aaime**
Could not find a way to write a test for it, the wicket Image class does not allow inspection of its image resource...

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [x] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by groldan** [comment]
The "New Cached Layer" page gets totally suck when there are lots of unconfigured layers. I'll get you an easy fix.

**Comment by groldan** [comment]
Hi Andrea, take a look at this branch: https://github.com/groldan/geoserver/tree/aaime/delayed_icon
It provides a 5x-6x performance improvement for the "New Cached Layer" page, pretty consistently under-second responses with 50K layers and ~2/2.3 seconds with 100k.

The only one really slow interaction is sorting by type for the first time, as it has to get all layers' FeatureTypes. Wonder if there might be a way to avoid that, or even disable sorting by geometry type? Or as a compromise, having only gwc, layergroup, raster, and vector types.

**Comment by groldan** [comment]
BTW, just realized that `LayerPage` doesn't sort as well, but it's fast. It relies on `PublishedInfo.getType(): PublishedType`, which doesn't distinguish between "vector geometry types", meaning it will only fetch the icons for the 25 items in the showing page as opposed to all items.

**Comment by groldan** [comment]
ok, made it so there's no FeatureType fetching during loading of tile layers, see 1be2f19ef86c49a309655639410723be1d9b3458

With a data directory with 50K tile layers and 50K unconfigured layers, both the cached layers page and the new cached layer page are responsive. 
Sorting by type for the first time goes from unbearable to ~2s.

Here's the data directory: [100K_50K_tile_layers.tgz](https://drive.google.com/file/d/1UtnejqYzxibHPlR5FTVEa8UV_V1fxbbC/view?usp=sharing)

BTW, works best with GeoWebCache/geowebcache/pull/797, since one the FeatureType loading for all layers bottleneck is removed, `GeoServerTileLayerInfo.clone()` takes up 50% of the time, which that PR fixes.

**Comment by aaime** [comment]
@groldan seems good, can you make a PR against my branch? Makes it easier to review and integrate.

**Comment by groldan** [comment]
@aaime aaime/geoserver/pull/10

**Comment by aaime** [comment]
@groldan PR integrated, proceeding to fix the leftover comments.

**Comment by aaime** [comment]
Ok, updated the caching mechanism, rebased the branch (it was failing due to changes in GWC that were not there) and force pushed (wanted to just merge, but got into trouble doing so and had to start over... sorry!)

**Comment by aaime** [comment]
@groldan you requested changes in PR review, could you have a look? The PR is accumulating conflicts in the meantime.

**Pull request closed without merging**
