### PR TITLE
GSIP-143 add status page for system properties and environment

### PR DESCRIPTION
**Pull request by DBlasby**
Added status page for System.getenv and System.getProperties.

Also, noticed that RenderingEngineStatusTest.java didn't have (c) header and had incorrect formating - fixed.

### CODE REVIEW

**Comment by tbarsballe** [comment]
Formatting-only changes should be their own commit, for easier code review and segregetion between formatting changes and functionality.

**Comment by DBlasby** [comment]
Moved out formatting changes

**Comment by tbarsballe** [comment]
Please squash your commits; having multiple cpmmits kind of defeats the purpose of keeping formatting-only changes seperate.

**Comment by tbarsballe** [comment]
Looks good, thanks!

I'll merge after the Travis Build passes.

**Pull request merged**
