### PR TITLE
Update imagemosiac tutorial

### PR DESCRIPTION
**Pull request by tbarsballe**
Update the imagemosaic tutorial with new content to match actual behavior.
Some content adapted from http://geoserver.geo-solutions.it/multidim/en/imagemosaic/index.html

Added description of JDBC indexing / datastore.properties
Added documentation on indexer.properties

Update GeoServer ImageMosaic Layer Configuration parameters with new parameters.

Fix formatting.

### CODE REVIEW

**Comment by tbarsballe** [comment]
Thanks for the review @bradh. I will fix the various typos you found shortly.

**Comment by dvntucker** [comment]
+1 @tbarsballe, nice to have more documentation on these features.

**Comment by simboss** [comment]
You can find a bit more docs about datastore config in [this](http://demo.geo-solutions.it/share/github/geobatch/download/latest/doc/actions/actionImageMosaic.html) tutorial.

Check also the JNDI section.

**Comment by tbarsballe** [comment]
Update:

* Fixed various typos.
* Added a minor update to the JNDI section, providing a link to the JNDI tutorial. Mostly leaving JNDI configuration to the JNDI tutorial, as imagemosaic treats JNDI the same as any other store (at least on the surface).
* Added minor update to the Filter (cql_filter) section, plus a link to the CQL/ECQL tutorial page.

Will merge later today after the Travis CI build completes, if there are no further comments.

**Comment by tbarsballe** [comment]
Backported to 2.8.x and 2.7.x.

**Pull request merged**
