### PR TITLE
GEOS-7887: use GML3 format from WFS Spring context to avoid memory leak

### PR DESCRIPTION
**Pull request by jandm**
Deployed and tested locally, and fixes the bug. 

Questions:
- is it ok to reference beans in the WFS context like i did ?
- do we need to do the same for other formats ?

PS: i can't import the eclipse formatter in intellij, space formatting looks incorrect

### CODE REVIEW

**Comment by aaime** [comment]
Hi, had a quick look and it seems ok, good job. 

Mind the contribution guide, reformatting the code is not welcomed and will prevent the pull request from being merged: 
https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md
and in particular:
https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md#pull-request-guidelines

The other requirement being tests... hmm... this one might be tricky. I've tried to write one for you, to be put in GetFeatureInfoIntegrationTest:

````
    @Test
    public void testSchemaLeak() throws Exception {
        String layer = getLayerId(MockData.FORESTS);
        String request = "wms?version=1.3.0&bbox=-0.002,-0.002,0.002,0.002&styles=&format=jpeg&info_format=" + GML3FeatureInfoOutputFormat.FORMAT + "&request=GetFeatureInfo&layers="
                + layer + "&query_layers=" + layer + "&width=20&height=20&i=10&j=10";
        // prime system, make sure everything is wired
        getAsDOM(request);
        
        // count how many imports in the OGC filter schema
        XSDSchema schema = OGC.getInstance().getSchema();
        int expectedImportCounts = schema.getReferencingDirectives().size();
        
        // now check how many there are after anothe request, should not go up
        getAsDOM(request);
        int actualImportCounts = schema.getReferencingDirectives().size();
        assertEquals(expectedImportCounts, actualImportCounts);
    }
````

**Comment by aaime** [comment]
Hi @jandm wondering, do you have time to amend the pull request, or should someone else try to take it over?

**Comment by jandm** [comment]
I'll look at it right away , will let you know if i get stuck.

**Comment by jandm** [comment]
I'm getting an unrelated test failure ?:
Tests run: 14, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 8.15 sec <<< FAILURE!
testAsyncExecutionLimit(org.geoserver.wps.InputLimitsTest)  Time elapsed: 2798 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Expecting to find matches for Xpath //ows:ExceptionText[contains(., 'maxExecutionTime 2 seconds, maxTotalTime 3 seconds')]
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at org.custommonkey.xmlunit.XMLAssert.assertXpathExists(XMLAssert.java:901)
	at org.geoserver.wps.InputLimitsTest.testAsyncExecutionLimit(InputLimitsTest.java:570)

**Comment by aaime** [comment]
Yeah, that one pops up every now and then, it's random

**Comment by jandm** [comment]
Please let me know if anything else is needed.

**Comment by aaime** [comment]
Hi, I'll try to pick this one up tomorrow during the bug fix sprint to:
* Clear the residual whitespace changes (lots of them)
* Squash in a single commit
* Backport to 2.10.x and 2.9.x

**Comment by jandm** [comment]
Great, thanks !

**Comment by aaime** [comment]
Manually merged to squash the commits. I did not remove the residual whitespace changes in the end since I'm backporting to all mainteined branches, but next time, try to avoid them.

**Pull request closed without merging**
