### PR TITLE
[GEOS-11285] GWC REST Content-Encoding gzip returns broken response

### PR DESCRIPTION
**Pull request by petersmythe**
[GEOS-11285](https://osgeo-org.atlassian.net/browse/GEOS-11285) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

Omit the Content-Length header in GZIPFilter

Related issue: https://osgeo-org.atlassian.net/browse/GEOS-10779

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by petersmythe** [comment]
Unit test testGZipRemovesContentLength was already in place

**Comment by aaime** [comment]
A test is needed. The test should fail before the change, and be working after.

Also, the change looks like a workaround, while the request wrapper is already trying to prevent the header from being set, in the first place. Did you figure out how that happened?

**Comment by petersmythe** [comment]
> Also, the change looks like a workaround, while the request wrapper is already trying to prevent the header from being set, in the first place. Did you figure out how that happened?

No, it was beyond my understanding.  It took many hours just to get this far.

> A test is needed. The test should fail before the change, and be working after.

I hear you.  So the filter test testGZipRemovesContentLength already checks the Content-Length is not set.  If it's not happening in the filter, what is the next layer that could be doing this i.e. what is a suitable test to set up?

**Comment by petersmythe** [comment]
Tests `testGZipRemovesContentLength` and `testNotGZippedMaintainsContentLength` have been updated to also use `setContentLengthLong`.  I can confirm that the test fails before the patch and passes after the patch.

**Review by prushforth — COMMENTED** [review]
I still get the same issue Content-Length is set to the uncompressed size of the resource, while the gzipped size is smaller, leaving the connection open for the full keep-alive time:

image
image

Edit: building the main module, maybe I missed that

**Comment by prushforth** [comment]
Acutally, I had not built the main module, so once I corrected that it works!  Wow, fantastic sleuthing and fixing.

**Comment by aaime** [comment]
Needs one more build on the command line, to fix the formatting (it happens automatically whenever one runs ``mvn ... install ... ``, but it's also possible to invoke spotless manually, the checklist has a link to instructions):

```
Error: 8,642 [ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.22.1:check (default) on project gs-main: The following files had format violations:
Error: 8,642 [ERROR]     src/test/java/org/geoserver/filters/GZipFilterTest.java
Error: 8,642 [ERROR]         @@ -73,7 +73,7 @@
Error: 8,642 [ERROR]          ········MockFilterConfig·config·=·new·MockFilterConfig(context);
Error: 8,642 [ERROR]          ········config.addInitParameter("compressed-types",·"text/plain");
Error: 8,642 [ERROR]          ········filter.init(config);
Error: 8,642 [ERROR]         -········
Error: 8,642 [ERROR]         +
Error: 8,642 [ERROR]          ········MockFilterChain·chain·=
Error: 8,642 [ERROR]          ················new·MockFilterChain()·{
Error: 8,642 [ERROR]          ····················@Override
Error: 8,642 [ERROR]         @@ -101,7 +101,7 @@
Error: 8,642 [ERROR]          
Error: 8,642 [ERROR]          ········//·run·the·filter
Error: 8,642 [ERROR]          ········GZIPFilter·filter·=·new·GZIPFilter();
Error: 8,642 [ERROR]         -········
Error: 8,642 [ERROR]         +
Error: 8,642 [ERROR]          ········MockServletContext·context·=·new·MockServletContext();
Error: 8,642 [ERROR]          ········MockFilterConfig·config·=·new·MockFilterConfig(context);
Error: 8,642 [ERROR]          ········config.addInitParameter("compressed-types",·"text/plain");
Error: 8,642 [ERROR] Run 'mvn spotless:apply' to fix these violations.
Error: 8,642 [ERROR] -> [Help 1]
```

**Comment by aaime** [comment]
> Tests `testGZipRemovesContentLength` and `testNotGZippedMaintainsContentLength` have been updated to also use `setContentLengthLong`. I can confirm that the test fails before the patch and passes after the patch.

Are both the int and long versions of the set content length methods covered by tests?

**Review by aaime — APPROVED** [review]
LGTM

**Comment by petersmythe** [comment]
Thanks for your guidance @aaime !

**Pull request merged**
