### PR TITLE
Synchronize translations with Transifex for web security package

### PR DESCRIPTION
**Pull request by AlexGacon**
# Checklist

- [X] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [X] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by AlexGacon** [comment]
The failed tests don't seem to be related with the translation changes : any clue ?

**Comment by bradh** [comment]
> The failed tests don't seem to be related with the translation changes : any clue ?

I've restarted the JDK 17 job. Will see if that helps.

**Comment by AlexGacon** [comment]
There is a real problem with the JDK 17 job no ? It is not the first time it failed but succeed after restart.

**Comment by bradh** [comment]
> There is a real problem with the JDK 17 job no ? It is not the first time it failed but succeed after restart.

I think it is an artifact of the CI system. If you'd like to debug, feel free.

**Comment by aaime** [comment]
I believe @mprins had a look at it and pushed a tentative fix against the OOM.

**Comment by mprins** [comment]
the failure was:
```
21:18:59,524 [INFO] 
21:18:59,524 [INFO] Results:
21:18:59,524 [INFO] 
Error: 9,524 [ERROR] Failures: 
Error: 9,524 [ERROR]   LocalResolveTest.testResolveTimeOut:119->AbstractAppSchemaTestSupport.assertXpathEvaluatesTo:334 expected:<[urn:x-test:GeologicUnit:gu.25699]> but was:<[]>
21:18:59,524 [INFO] 
Error: 9,524 [ERROR] Tests run: 233, Failures: 1, Errors: 0, Skipped: 23
```

but seems resolved now

**Pull request merged**
