### PR TITLE
[GEOS-8751] install/deploy community gs-nsg-profiles for -PcommunityRelease

### PR DESCRIPTION
**Pull request by sikeoka**
https://osgeo-org.atlassian.net/browse/GEOS-8751

This pull request can be backported to 2.13.x

### CODE REVIEW

**Comment by nmco** [comment]
Hi @sikeoka thank you for this contribution ! I create a PR proposing a slightly different approach build on top of what you did:
1. the handling of which profile should be activated is delegated to the NSG profiles module
2. a maven command executed inside NSG profiles module directory will hit all the profiles

If you agree with my approach  we can close this PR and merge these two:
- https://github.com/geoserver/geoserver/pull/2919
- https://github.com/geoserver/geoserver/pull/2920

**Comment by sikeoka** [comment]
I tried to make gs-nsg-profiles consistent with how gs-security works.  I don't care too much about how it's done as long as everything gets installed correctly but wouldn't having two different ways to handle multi-module community projects be confusing for future developers?  I'll leave it up to you unless someone else wants to comment.

**Comment by nmco** [comment]
Yes I know, security community module is doing it that way, actually recent modules have all their own way of handling this ... but if you have a look at older modules, like jms and script for example, they are all using the way I propose.

I agree that we should make consistent the way community plugins with multi-modules are handled. I will take that into account when reviewing new community modules contribution, maybe adding this to the documentation too ?

**Comment by sikeoka** [comment]
That sounds good to me.

**Comment by nmco** [comment]
Cool, merged my PRs closing this one, thank you for the discussion.

**Pull request closed without merging**
