### PR TITLE
Updated link to Christian's thesis

### PR DESCRIPTION
**Pull request by mtCarto**
Link to rancor.boundlessgeo.com was broken

### CODE REVIEW

**Comment by aaime** [comment]
Thanks, merging it. Wondering if a more "stable" location should be found for that pdf file?

**Comment by aaime** [comment]
@mcrmcr any opinions on this one?

**Comment by mcrmcr** [comment]
What about putting the pdf in the "doc" directory.

Cheers
Christian

On Wed, Oct 7, 2015 at 10:01 AM, Andrea Aime <notifications@github.com>
wrote:

> Merged #1257 <https://github.com/geoserver/geoserver/pull/1257>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoserver/geoserver/pull/1257#event-428833263>.
>



-- 
DI Christian Mueller MSc (GIS), MSc (IT-Security)
OSS Open Source Solutions GmbH

**Comment by aaime** [comment]
We are very adamant that people should add very small (few kb) sample data sets to keep the checkout size controlled, this PDF is 1MB. Not an option imho.

**Comment by mcrmcr** [comment]
Hi Andrea.

Sorry for the late reply.

I have a Google Business Account. I could store the doc on Google Drive and
create a public share. What is your opinion ?

Cheers
Christian

On Wed, Oct 7, 2015 at 6:12 PM, Andrea Aime <notifications@github.com>
wrote:

> We are very adamant that people should add very small (few kb) sample data
> sets to keep the checkout size controlled, this PDF is 1MB. Not an option
> imho.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoserver/geoserver/pull/1257#issuecomment-146247868>.
>



-- 
DI Christian Mueller MSc (GIS), MSc (IT-Security)
OSS Open Source Solutions GmbH

**Pull request merged**
