### PR TITLE
[GEOS-9119] Add missing parameter to gwcBlobStore bean configuration

### PR DESCRIPTION
**Pull request by tbarsballe**
See https://osgeo-org.atlassian.net/browse/GEOS-9119

### CODE REVIEW

**Comment by aaime** [comment]
Works for me but.. how does GeoServer even start without the parameter in question? I only see one constructor there....

**Comment by tbarsballe** [comment]
I'm not sure myself. My best guess is GeoServer is pulling in the bean from the [GWC version | https://github.com/GeoWebCache/geowebcache/blob/master/geowebcache/web/src/main/webapp/WEB-INF/geowebcache-core-context.xml#L94-L99]of that file somehow. Probably worth investigating, although debugging through Spring context instantiation is always a pain.

**Comment by tbarsballe** [comment]
Okay, I actually debugged into it, and it turns out Spring is using the GeoServer context file and just auto-wiring the missing parameter via spring magic. I imagine this is a bit dependant on spring version and other config, which also explains why it doesn't work on all configurations.

**Comment by aaime** [comment]
Bizzarre :-) 
Anyways, still best to be clear in the app-context.

**Pull request merged**
