### PR TITLE
[GEOS-10336]-INSPIRE failure: version not propagated in GetCapabilities LegendURL

### PR DESCRIPTION
**Pull request by yashwanthanands**
[GEOS-10336](https://osgeo-org.atlassian.net/browse/GEOS-10336)

WMS Version propagation issue in the Legend URL has been fixed.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
@yashwanthanands never remove the PR template. Instead, check everything that applies, and make sure you followed every requirement (e.g., I don't see a new test, but at least one is required).

**Comment by yashwanthanands** [comment]
thanks for the review @aaime , your feedback have been applied.

**Review by mprins — APPROVED** [review]

**Comment by mprins** [comment]
Does this require a CLA?  the actual code change is rather small IMO, if not this should be squash-merged

**Comment by aaime** [comment]
@yashwanthanands is working for GeoSolutions, so covered by the company's CLA.

**Pull request merged**
