### PR TITLE
[Backport 2.22.x] [GEOS-10871] Force use of AntRun plugin 3.1.0

### PR DESCRIPTION
**Pull request by aaime**
[GEOS-10871](https://osgeo-org.atlassian.net/browse/GEOS-10871)

Backport #6635
 **Authored by:** @jodygarnett

### CODE REVIEW

**Comment by jodygarnett** [comment]
Got a pretty solid error on windows:

* ``java.lang.ClassNotFoundException: org.geoserver.util.EntityResolverProvider`` 33 matches
* ``java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext`` 1000 matches 

This is the kind of "something went wrong" build failure that indicates the test harness is not working:

```
2023-02-27T15:18:27.3244863Z Feb 27, 2023 3:18:27 PM org.geoserver.ows.Dispatcher <init>
2023-02-27T15:18:27.3245410Z WARNING: Unable to load EntityResolverProvider. Entity resolution will be enabled: java.lang.ClassNotFoundException: org.geoserver.util.EntityResolverProvider
2023-02-27T15:18:27.3245948Z Feb 27, 2023 3:18:27 PM org.geoserver.ows.Dispatcher exception
2023-02-27T15:18:27.3246258Z SEVERE: 
2023-02-27T15:18:27.3246621Z org.geoserver.platform.ServiceException: Whoops, something gone wrong!
```

Yep problems setting up workspace:
```
2023-02-27T15:20:28.6011577Z Feb 27, 2023 3:20:28 PM org.geoserver.platform.GeoServerExtensions extensionNames
2023-02-27T15:20:28.6011663Z WARNING: bean lookup error
2023-02-27T15:20:28.6012040Z java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
2023-02-27T15:20:28.6012415Z 	at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:168)
2023-02-27T15:20:28.6012745Z 	at org.springframework.context.support.AbstractApplicationContext.getBeanNamesForType(AbstractApplicationContext.java:1231)
2023-02-27T15:20:28.6012969Z 	at org.geoserver.platform.GeoServerExtensions.extensionNames(GeoServerExtensions.java:234)
2023-02-27T15:20:28.6013184Z 	at org.geoserver.platform.GeoServerExtensions.extensions(GeoServerExtensions.java:137)
2023-02-27T15:20:28.6013397Z 	at org.geoserver.platform.GeoServerExtensions.extensions(GeoServerExtensions.java:292)
2023-02-27T15:20:28.6013591Z 	at org.geoserver.catalog.impl.CatalogImpl.getValidators(CatalogImpl.java:144)
2023-02-27T15:20:28.6013782Z 	at org.geoserver.catalog.impl.CatalogImpl.postValidate(CatalogImpl.java:2094)
2023-02-27T15:20:28.6013962Z 	at org.geoserver.catalog.impl.CatalogImpl.validate(CatalogImpl.java:1487)
2023-02-27T15:20:28.6014125Z 	at org.geoserver.catalog.impl.CatalogImpl.add(CatalogImpl.java:1441)
2023-02-27T15:20:28.6014336Z 	at org.geoserver.config.GeoServerImplTest.createWorkspace(GeoServerImplTest.java:333)
2023-02-27T15:20:28.6014483Z 	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
2023-02-27T15:20:28.6014671Z 	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
2023-02-27T15:20:28.6014830Z 	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
2023-02-27T15:20:28.6015011Z 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
2023-02-27T15:20:28.6015213Z 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
2023-02-27T15:20:28.6015386Z 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
2023-02-27T15:20:28.6015555Z 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2023-02-27T15:20:28.6015736Z 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
2023-02-27T15:20:28.6015945Z 	at org.geoserver.config.GeoServerImplTest.addWorkspaces(GeoServerImplTest.java:325)
2023-02-27T15:20:28.6016217Z 	at org.geoserver.config.GeoServerImplTest.testWorkspaceSettingsThreadSafety(GeoServerImplTest.java:299)
```

**Comment by jodygarnett** [comment]
I am adding a revert of https://github.com/geoserver/geoserver/pull/6637 to this PR as it appears not all tests were passed when that was merged

**Comment by jodygarnett** [comment]
Marking this as a draft as I wish to share the record of GEOS-6313 revert working, but do not wish this merged until GEOS-61313 is resolved.

**Comment by aaime** [comment]
@jodygarnett we have had those random build failures for a bit, not necessarily related to this one. 
We have had a ton of network related failures lately, failures to transfer artifacts from repos... I'm speculating maybe some manage to get past error checking, but then we get corrupt jars in the repo and this results in classloading issues.
But... just a guess. I don't know where to find time to actually look into this.

**Comment by jodygarnett** [comment]
Reseting this as test to see if this is a transitory windows failure or due to recent lifecycle checks

**Comment by jodygarnett** [comment]
You are correct @aaime it passes today - how frustrating.

**Comment by dieterstueken** [comment]
That's interesting:

My PR was an attempt to resolve those `BeanFactory not initialized`  errors.
I analyzed the stacktrace in detail, but it seems not being related to my changes.
While I changed the life-cycle of `GeoServerLoaderProxy`  itself, this one discloses additional life-cycle problems with `GeoServerExtensions`.

However,  `GeoServerExtensions` is some very strange kind of a static singleton which raises a lot of questions.

https://refactoring.guru/smells/large-class

**Comment by sikeoka** [comment]
The BeanFactory not initialized stack traces was fixed on main about two and a half months ago but somehow didn't get backported even though it had the backport labels.

**Comment by jodygarnett** [comment]
We should find and backport your improvement. 

GeoServerExtensions had very strange static behaviour to facilitate some test cases. I think I tried to isolate the strange into a helper class but could not remove it.

**Comment by dieterstueken** [comment]
sorry I mixed this up. This one is not my own PR I mentioned (6637, merged yesterday).
But my comment remains: a very weird singleton class.
Not my first case to cut down those software tumors. I keep thinking about ...

**Pull request merged**
