### PR TITLE
[GEOS-11088] 30% of startup time spent in XstreamPersister's CRSConverter

### PR DESCRIPTION
**Pull request by groldan**
[GEOS-11088](https://osgeo-org.atlassian.net/browse/GEOS-11088)

Significant overhead added by `CRSConverter` while starting up off a datadir with a large number of layers, parsing the same small number of CRS WKT over and over.

Add a short-lived cache to `CRSConverter` to limit the number of calls to `CRS.parseWKT()`. Guava's cache also handles concurrency out of the box.

The cache contains up to 10 entries and values are SoftReferences.

  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
In the PSC meeting, we were wondering about pushing cachiNg down in CRS.parseWKT(), using a GeoTools soft cache instead (which can be cleared when CRS.reset is called) .Rationale: it would benefit every usage of WKT, rather than just the GeoServer XStream usage, and fits with the rest of the GeoTools CRS handling (the buffered authority factory is caching CRS lookups too, but only by code)

**Comment by aaime** [comment]
There isn't, but you got official PSC feedback above. 
If you want to merge this PR as is nonetheless, I suggest you escalate discussion on the geoserver-devel list.

**Comment by groldan** [comment]
I see. I didn't take your initial comment "we were wondering about pushing caching down in CRS.parseWKT()" as a recommendation for me to do it. I'll see, this is not something I really need myself, I can apply the patch to geoserver-cloud, and it was just a nice contribution given I'm on vacations.
If I have time and interest I will make a GT pr, otherwise it's up to you, the PSC.
Cheers,

**Comment by jodygarnett** [comment]
It was me with the idea Gabe, indeed we are shocked at how well your loader is doing to place such stress on the system :)

**Comment by aaime** [comment]
Quick PR with GeoTools based replacement, following the existing patterns in CRS class:
[Jotted ](https://github.com/geotools/geotools/pull/4423)

@groldan would that achieve the same performance as this one?

**Comment by groldan** [comment]
I'll give it a shot. It won't have the same concurrency handling as the guava cache, but at the same time it might be a bit of an edge case (concurrent requests hitting a miss will all parse the wkt).
Besides that, performance wise it should be the same.

**Comment by groldan** [comment]
Closing as superseeded by https://github.com/geotools/geotools/pull/4423

**Pull request closed without merging**
