### PR TITLE
Add POST example with keyword search

### PR DESCRIPTION
**Pull request by paulwittle**
This proposal adds and example of how you might query CSW using an HTTP POST request and also demonstrates how to search the keywords and increase the number of results returned.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by travis-ci after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates

Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.

### CODE REVIEW

**Comment by paulwittle** [comment]
I've just realised that I've missed a whole discussion here. My example actually uses Dublin Core which may mean it is still relevant to the core module rather than the downgraded ISO module. That said, I'm not 100% what happened to the tutorial as I thought the examples (or at least some of them) could be relevant to Dublin Core as well as ISO. 

I also notice that this pull request has failed the checks so I'm not sure exactly where I should be pushing my proposed change now.

**Comment by aaime** [comment]
Yeah, the ISO support was downgraded due to lack of a maintainer.
I believe @NielsCharlier moved the ISO documentation somewhere else, but it's still available in the docs tree, likely in the community section.. yeah, here:
https://docs.geoserver.org/latest/en/user/community/csw-iso/index.html
Were you referring to this tutorial?
https://docs.geoserver.org/latest/en/user/community/csw-iso/tutorial.html

**Comment by paulwittle** [comment]
Yeah, I think that is right; on closer inspection there is still a link to that page from the supported part of the plugin. This pull request is for the tutorial file which I assume is correct. I think the test failures might be linked to the Java 11 issue you've been discussing so potentially this commit is all correct despite it failing the tests?

**Comment by aaime** [comment]
Sounds about right, merging.

**Pull request merged**
