### PR TITLE
Follow up documentation changes for [GEOT-5759] (removal of -gt- prefixes for vendor options in CSS)

### PR DESCRIPTION
**Pull request by aaime**

### CODE REVIEW

**Comment by jodygarnett** [comment]
I will need to update the styling workshop (which also uses the gt prefixes).

**Comment by aaime** [comment]
@jodygarnett it's been a while since your comment, I am not familiar with the CSS workshop but I've tried to fix it anyways, could you have a look and make any further fixes you deem necessary?

**Comment by aaime** [comment]
Ah hem, @jodygarnett ? :-)

**Comment by aaime** [comment]
Sorry @jodygarnett , got tired of waiting. Can you please avoid commenting on pull requests when you have no intention or time to follow up? I believe there are other pull requests blocked waiting for you to follow up.

Merging now

**Pull request merged**
