### PR TITLE
GEOS-7369: Handling placemarks encoded with ground overlay for data in projected crs.

### PR DESCRIPTION
**Pull request by jdeolive**
Rather than grabbing the raw feature source use the current context feature
collection, which already has been set up to deal with reprojection, etc...

### CODE REVIEW

**Comment by jdeolive** [comment]
Fwiw I plan to backport this bug fix back to the 2.8.x branch.

**Comment by simboss** [comment]
If I do a review will you give me a 100$ for this? :P

**Comment by jdeolive** [comment]
@simboss Haha.. you drive a hard bargain but deal! :P

**Comment by simboss** [comment]
I am just kidding of course!

(Am I? :) )

**Comment by jdeolive** [comment]
Anyone have any feedback on this one? Are we still pushing in bug fixes for 2.9?

**Comment by jdeolive** [comment]
No movement on this one so unless I hear anything back in the next couple of days I plan to merge in this bug fix. It's a pretty small self contained change.

**Comment by aaime** [comment]
Yep, good fix.
Ah hem... hem... the copyright headers vote is still not passed (and it's geotools only for the moment), before merging and backporting could you fix them to be "2014 - 2016"? :-D

**Comment by jdeolive** [comment]
Thanks Andrea. Re the copyright headers I did try to update them correctly but I was unclear on whether I need a range or not. Thanks a lot for clarifying! I'll fix that.

**Pull request merged**
