### PR TITLE
[GEOS-11122] Loading font from FontCache when specified in legend options.

### PR DESCRIPTION
**Pull request by jdeolive**
[GEOS-11122](https://osgeo-org.atlassian.net/browse/GEOS-11122) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

This change addresses the issue of trying to use the font name of a font that has been added from the geoserver data directory. The idea is to check the FontCache first, before falling back to existing behaviour.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).
- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
Whoa @jdeolive welcome back, nice to see you dig into the code!

Checking the build results, there are some issues in the new test:

```
2023-09-12T22:18:48.0473824Z 22:18:48,045 [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.008 s <<< FAILURE! - in org.geoserver.wms.legendgraphic.LegendUtilsTest
2023-09-12T22:18:48.0477129Z 22:18:48,047 [ERROR] testGetLabelFromCache(org.geoserver.wms.legendgraphic.LegendUtilsTest)  Time elapsed: 0.007 s  <<< FAILURE!
2023-09-12T22:18:48.0477995Z org.junit.ComparisonFailure: expected:<[Dialog]> but was:<[Bitstream Vera Sans]>
2023-09-12T22:18:48.0479179Z 	at org.geoserver.wms.legendgraphic.LegendUtilsTest.testGetLabelFromCache(LegendUtilsTest.java:30)
2023-09-12T22:18:48.0481082Z
```

**Comment by jdeolive** [comment]
Thanks @aaime ! Hope all is well in your world. I think i know why that test is failing, will work on that today. Thanks for checking it out!

**Comment by jdeolive** [comment]
@aaime Thanks Andrea! There was actually a formatting issue that I missed as well, so just re-pushed that. No rush on merging this from my end, happy to wait for the GWC stuff to get sorted first.

**Comment by aaime** [comment]
With the RC out things should have settled down. This is a fix, so it can get in anywas. Can you rebase?

BTW, gotta love the anarchist mustache! :laughing:

**Comment by aaime** [comment]
The backport to `2.22.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 3e3ca1ebcb... [GEOS-11122] Loading font from FontCache when specified in legend options
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendUtils.java
CONFLICT (content): Merge conflict in src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendUtils.java

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-2.22.x 2.22.x
# Navigate to the new working tree
cd .worktrees/backport-2.22.x
# Create a new branch
git switch --create backport-7115-to-2.22.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 3e3ca1ebcbe4d5df5d5e6f300a6e11530fa59023
# Push it to GitHub
git push --set-upstream origin backport-7115-to-2.22.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-2.22.x
```
Then, create a pull request where the `base` branch is `2.22.x` and the `compare`/`head` branch is `backport-7115-to-2.22.x`.

**Comment by aaime** [comment]
The backport to `2.23.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 3e3ca1ebcb... [GEOS-11122] Loading font from FontCache when specified in legend options
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendUtils.java
CONFLICT (content): Merge conflict in src/wms/src/main/java/org/geoserver/wms/legendgraphic/LegendUtils.java

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-2.23.x 2.23.x
# Navigate to the new working tree
cd .worktrees/backport-2.23.x
# Create a new branch
git switch --create backport-7115-to-2.23.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 3e3ca1ebcbe4d5df5d5e6f300a6e11530fa59023
# Push it to GitHub
git push --set-upstream origin backport-7115-to-2.23.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-2.23.x
```
Then, create a pull request where the `base` branch is `2.23.x` and the `compare`/`head` branch is `backport-7115-to-2.23.x`.

**Pull request merged**
