### PR TITLE
PR - Fix for (GEOS-7805) CSW Service does not work anymore due to EntityResolver bean circular reference

### PR DESCRIPTION
**Pull request by afabiani**

### CODE REVIEW

**Comment by aaime** [comment]
Can you elaborate on how/why the pull request works? The readers do depend explicitly on the EntityResolverProvider, which in turn depends on GeoServer... so it seems the change only makes a transitive dependency explicit. What am I missing?

**Comment by afabiani** [comment]
At least in Tomcat container, since geoServer is an alias, if the loader tries to instantiate a bean depending on that, even transitively, before gs-main jar is loaded, we get a"BeanInCreation" exception. At least this is what I am experiencing on Tomcat7 containers.

**Comment by afabiani** [comment]
At least in Tomcat container, since geoServer is an alias, if the loader
tries to instantiate a bean depending on that, even transitively, before
gs-main jar is loaded, we get a"BeanInCreation" exception. At least this is
what I am experiencing on Tomcat7 containers.

**Comment by afabiani** [comment]
Closing this as replaced by

https://github.com/geoserver/geoserver/pull/1921

**Pull request closed without merging**
