### PR TITLE
Update time.rst

### PR DESCRIPTION
**Pull request by Fred-VLIZ**
Typo

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Review by bradh — APPROVED** [review]
LGTM.

**Comment by aaime** [comment]
@ianturton however... now 2.21.x is stable, and 2.20.x is maintenance...

**Comment by petersmythe** [comment]
Is there a way that we can guide all users to the latest documentation rather than the stable documentation?  I just think that there's a difference between code and docs, while some users might dictate using a stable code base, generally latest documentation is better than stable.

**Comment by mprins** [comment]
I can:
- add https://geoserver.org/ into my Google Search Console  sites
- add the verification file required for that 
- add some key files to the index
- when I have time add some template to generate a sitemap file
this wil give a little control over what shows up in search results first

**Pull request merged**
