### PR TITLE
GEOS-7933: Adding contentType to HttpErrorCodeException.

### PR DESCRIPTION
**Pull request by jdeolive**

### CODE REVIEW

**Comment by ianturton** [comment]
Looks ok to me,

**Comment by aaime** [comment]
Agreed

**Comment by jdeolive** [comment]
Great, thanks guys. I was hoping to backport this one to 2.10.x as well? Any concerns with that? Should I wait for a bit?

**Comment by aaime** [comment]
It's a again a small change, and the 2.10.x release is next month, so I'd rather merge now than wait a month and then merge a day before the release...

**Comment by jdeolive** [comment]
Cool, sounds good, thanks Andrea. Backport coming shortly.

**Pull request merged**
