### PR TITLE
[GEOS-11312] Inconsistent Memory Units in Legend Image Creation

### PR DESCRIPTION
**Pull request by vuvkar**
[GEOS-11312](https://osgeo-org.atlassian.net/browse/GEOS-11312) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=geoserver&utm_campaign=badge_info)

Tally was doing memory calculations in the byte level, but it was not considered datatype capabilities. 

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [x] Bug fixes and small new features are presented as a single commit.
- [x] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
As you can see from the checklist, tests are mandatory. Please add one that would fail without the changes, and works as expected with the data type change.

**Comment by vuvkar** [comment]
@aaime a question about the last check - 
``` Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).```
Do I need to create a separate issue in JIRA, or create a new branch, and submit all the changes with one commit? 
Sorry, this is my first contribution to GeoServer 😅

**Comment by aaime** [comment]
@vuvkar don't worry about that one, when it comes the time to merge we can use "squash merge" to reduce the list of commits down to one.

**Comment by aaime** [comment]
@vuvkar the ticket was closed by mistake. PRs are reviewed on volunteer time, please be patient, we cannot guarantee a specific deadline.

**Review by mprins — CHANGES_REQUESTED** [review]
Please fix the styling by running 
mvn spotless:apply
or 
mvn install
before commit

https://github.com/geoserver/geoserver/actions/runs/8146100128/job/22449170452?pr=7443#step:6:6255

**Comment by aaime** [comment]
QA fixed, changes look good, merging.

**Pull request merged**
