### PR TITLE
Fix for GEOS-9384

### PR DESCRIPTION
**Pull request by ronaldhoek**
Fix link to 'Building Windows Installer' instruction from user manual.

## Checklist
- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

### CODE REVIEW

**Comment by aaime** [comment]
Odd, there is a conflict...

**Comment by ronaldhoek** [comment]
> Odd, there is a conflict...

Looks like @ianturton pushed a fix yesterday:
https://github.com/geoserver/geoserver/commit/46d0025594e80a2c1d24528588dd061924483cef#diff-a8c8b7124766023cc0287b72e6eac396

**Comment by ronaldhoek** [comment]
Resolved conflict by
- merging the master into the pull branch
- modified the url to use a relative path

**Comment by aaime** [comment]
Build failure is unrelated... @ianturton are you ok to merge?

**Pull request merged**
