### PR TITLE
[GEOS-7740] Make ResourceNotification serializable

### PR DESCRIPTION
**Pull request by tbarsballe**
See https://osgeo-org.atlassian.net/browse/GEOS-7740

### CODE REVIEW

**Comment by jodygarnett** [comment]
These are transitory objects used for notification - why do they need to be serializable?

**Comment by tbarsballe** [comment]
See details about the problematic behavior in the linked ticket.

**Comment by jodygarnett** [comment]
Niels has answered my question on the mailing list.

**Comment by tbarsballe** [comment]
Trivial bugfix; backported to 2.9.x

**Pull request merged**
