### PR TITLE
[GEOS-11045] Implement proposal "OGC API - Features - Part n: Query by IDs"

### PR DESCRIPTION
**Pull request by sebastianfrey**
[GEOS-11045](https://osgeo-org.atlassian.net/browse/GEOS-11045)

This PR implements the OGC API- Features Proposal `Query by IDs`. It allows multiple features to be queried by ID at once.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [x] New unit tests have been added covering the changes.
- [x] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [x] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [x] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by sebastianfrey** [comment]
I am not sure why some build are failing and some not. On my local machine everything compiles fine without errors.

**Comment by bradh** [comment]
The failing CI is a problem with other PRs. I don't think its related to this change. I've restarted some.

**Comment by sebastianfrey** [comment]
@bradh Ok, thanks for letting me now. Makes sense.

**Comment by aaime** [comment]
Could you rebase the PR on top of the latest main?

**Comment by sebastianfrey** [comment]
I have no access to a full Git right now, so I synced the branch through GitHub's web UI. This created an additional merge commit, if a full rebase is required, you will have to wait.

**Comment by aaime** [comment]
Squash-merged it down to a single commit :smile:

**Pull request merged**
