### PR TITLE
Geos 10424 fix backuprestore lib packaging

### PR DESCRIPTION
**Pull request by fostash**
[GEOS-10424](https://osgeo-org.atlassian.net/browse/GEOS-10424)

Fix maven install definition adding jdom jar for backup restore plugin 
  

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [ ] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [ ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ ] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
So you produced the release zips and tested it can start after the fix?

**Comment by fostash** [comment]
Yes, the server startup correctly after the fix

**Comment by bradh** [comment]
Do you get "existing file" warnings when doing the unzip?

**Comment by fostash** [comment]
Yes I get "existing file" when copying file into the lib dir of geoserver for already present jars
I opened the PR agains 2.20.x because the jira ticket is raised for the 2.20.3, in the main branch it is already fixed

**Comment by aaime** [comment]
That is true... 

image

However, it means GEOS-10432 was just not backported. If so, actions:
* Close GEOS-10424 as a duplicate of GEOS-10432 (I see it came before, but the other one is the one that got a commit)
* Close this PR, a backport [GEOS-10432](https://github.com/geoserver/geoserver/commit/a980689acca5df18c1afd7e6a19b69a0c765e17e) instead, keeping the two files aligned (the current PR puts the jdom jar in a different line).

**Comment by fostash** [comment]
closed. opened https://github.com/geoserver/geoserver/pull/5821 for backport https://github.com/geoserver/geoserver/commit/a980689acca5df18c1afd7e6a19b69a0c765e17e

**Pull request closed without merging**
