### PR TITLE
translate introduction in user manual to zhCN

### PR DESCRIPTION
**Pull request by sharkAndshark**
affects doc only
<Include a few sentences describing the overall goals for this Pull Request. Please do not remove the checklist below, pull requests missing it will be ignored.>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not applicable.**

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for community modules):
- [ ] There is a ticket in Jira describing the issue/improvement/feature (a notable exemptions is, changes not visible to end users)
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[GEOS-XYZW] Title of the Jira ticket" (export to XML in Jira generates the message in this exact form)
- [ ] The pull request contains changes related to a single objective. If multiple focuses cannot be avoided, each one is in its own commit and has a separate ticket describing it.
- [ ] New unit tests have been added covering the changes
- [ ] This PR passes all existing unit tests (test results will be reported by Continuous Integration after opening this PR)
- [ ] This PR passes the [QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html) (QA checks results will be reported by Continuous Integration after opening this PR)
- [ ] Commits changing the UI, existing user workflows, or adding new functionality, need to include documentation updates (screenshots, text)
- [ ] Commits changing the REST API, or any configuration object, should check if the REST API docs (Swagger YAML files and classic documentation) need to be updated.

### CODE REVIEW

**Comment by aaime** [comment]
@sharkAndshark thanks for sharing this translation!
@jodygarnett do we need to do anything for this translation to be visible to end users?

**Comment by aaime** [comment]
@tbarsballe do you know if  we need to do anything for this translation to be visible to end users?

**Comment by tbarsballe** [comment]
I'm not certain. I think it might "just work" if we merge it. The docs.geoserver.org page urls include /en/ so I think other localizations will get handled the same way.

**Comment by jodygarnett** [comment]
@sharkAndshark we are merging to see if it shows up automatically on docs.geoserver.org, if not we will sort out how to get it to set up. And then you can work on the documentation more over time?

**Comment by sharkAndshark** [comment]
> @sharkAndshark we are merging to see if it shows up automatically on docs.geoserver.org, if not we will sort out how to get it to set up. And then you can work on the documentation more over time?

sure.

**Comment by tbarsballe** [comment]
I've added a build script for the translated docs: https://github.com/geoserver/geoserver/pull/4823

However, it looks like they fail to build - it appears some pages linked from the main page are missing - those links will need to be removed, or the requisite pages will need to be added.
It's also possible that some of the links were translated differently than the page name (in particular, 简介/index.rst seems to not be linked from anywhere), in which case the link should be updated to match the page name.

More details on these build failures can be seen on the linked pull request, or you can pull down the branch and run `mvn clean install` in the docs/zhCN directory (requires `mvn`, `ant`, and `sphinx-build`)

**Comment by sharkAndshark** [comment]
> I've added a build script for the translated docs: #4823
> 
> However, it looks like they fail to build - it appears some pages linked from the main page are missing - those links will need to be removed, or the requisite pages will need to be added.
> It's also possible that some of the links were translated differently than the page name (in particular, 简介/index.rst seems to not be linked from anywhere), in which case the link should be updated to match the page name.
> 
> More details on these build failures can be seen on the linked pull request, or you can pull down the branch and run `mvn clean install` in the docs/zhCN directory (requires `mvn`, `ant`, and `sphinx-build`)

I'm trying to fix it

**Comment by sharkAndshark** [comment]
> I've added a build script for the translated docs: #4823
> 
> However, it looks like they fail to build - it appears some pages linked from the main page are missing - those links will need to be removed, or the requisite pages will need to be added.
> It's also possible that some of the links were translated differently than the page name (in particular, 简介/index.rst seems to not be linked from anywhere), in which case the link should be updated to match the page name.
> 
> More details on these build failures can be seen on the linked pull request, or you can pull down the branch and run `mvn clean install` in the docs/zhCN directory (requires `mvn`, `ant`, and `sphinx-build`)

I try to fix it in https://github.com/geoserver/geoserver/pull/4832

**Pull request merged**
