### PR TITLE
[GEOS-10778] Retire GeoStyler community module

### PR DESCRIPTION
**Pull request by aaime**
[GEOS-10778](https://osgeo-org.atlassian.net/browse/GEOS-10778)

See ticket for details. 

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/geoserver/geoserver/blob/main/CONTRIBUTING.md).
- [x] I have sent a [Contribution Licence Agreement](https://docs.geoserver.org/latest/en/developer/policies/committing.html) (not required for small changes, e.g., fixing typos in documentation).
- [x] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [x] All the build checks are green ([see automated QA checks](https://docs.geoserver.org/latest/en/developer/qa-guide/index.html)).

For core and extension modules:

- [ ] New unit tests have been added covering the changes.
- [ ] [Documentation](https://github.com/geoserver/geoserver/tree/main/doc/en/user/source) has been updated (if change is visible to end users).
- [ ] The [REST API docs](https://github.com/geoserver/geoserver/tree/main/doc/en/api/1.0.0) have been updated (when changing configuration objects or the REST controllers).
- [ ] There is an issue in the [GeoServer Jira](https://osgeo-org.atlassian.net/browse/GEOS/summary) (except for changes that do not affect administrators or end users in any way).
- [ ] Commit message(s) must be in the form ``[GEOS-XYZWV] Title of the Jira ticket``.
- [ ] Bug fixes and small new features are presented as a single commit.
- [ ] Each commit has a single objective (if there are multiple commits, each has a separate JIRA ticket describing its goal).

### CODE REVIEW

**Comment by aaime** [comment]
I inquired about the module removal a few months ago, but PRs never came, so I made one:
https://mobile.twitter.com/geowolf/status/1536638848259735554

@marcjansen can anyone from Terrestris review?

**Comment by marcjansen** [comment]
@aaime thanks for the reminder.

@buehner, @hwbllmnn, @dkoch or @weskamm please take a look and if possible link to the new repo / builds.

TIA

**Review by hwbllmnn — APPROVED** [review]

**Comment by hwbllmnn** [comment]
@aaime Do you have a suggestion where to put a link to the new repo? I'm not sure if this is currently auto-generated or not.

**Comment by aaime** [comment]
@hwbllmnn we don't have a place for externally maintained plugins yet...  but I guess you could resurrect the documentation page I've deleted in this PR, and provide links to the external repository instead?
Maybe with an explanation on how to install, I've looked for the usual zip file other extensions provide, but could not find one. Also, some indication about version compatibility would be useful (e.g., right now it might work with a variety of GeoServer versions, but the day we upgrade Wicket it's likely that some code will have to be modified).

I would suggest you open another PR, grab this commit, and add the documentation for the external plugin as you see fit.

**Comment by jodygarnett** [comment]
I am not sure how I feel about linking to externally managed plugins? I guess we could treat them at the same level as community modules? I feel better about the community modules as they are in a common area for folks to contribute / collaborate on with an inside track for being added to the core geoserver application.

I guess the key thing I would like to know as a user is if the external plugin works with *this exact* version of GeoServer. If we find links like geogig that work with old unsupported versions of GeoServer it would not do much good.

**Review by jodygarnett — APPROVED** [review]
Andrea your change to the user manual and community modules looks good.

**Comment by aaime** [comment]
Thanks for checking it out @jodygarnett . I'll leave the PR open till next Monday, and will merge if no other action is taken. Terrestris can always follow up with another PR to reinstate some docs pointing at the new repo.

**Comment by hwbllmnn** [comment]
Alright, I've opened an alternative PR #6431 with the changes suggested by @aaime , feel free if you choose this one.

**Comment by aaime** [comment]
Thanks @hwbllmnn

**Comment by aaime** [comment]
> I am not sure how I feel about linking to externally managed plugins?

Yeah, I have seen externally managed plugins before, but none of them survived in the long run (with the exception of the ElasticSearch one, which was folded back in GeoTools when NGA stopped developing it). But it's everyone's prerogative to choose their own path, if the GeoStyler developers prefer to maintain it in their own repo, more power to them.
Indeed it got more updates now it's there, than the entire time it was sitting unmaintained in the community section of the plugins (so, that's a definitive plus).

Figuring out which version of GeoServer works with the plugin will be indeed more of a challenge, but they can manage it with clear communication and release notes (e.g. "this plugin has been tested with version xyz of GeoServer).

**Pull request closed without merging**
