### PR TITLE
Add Travis CI coverage of communityRelease profile

### PR DESCRIPTION
**Pull request by bencaradocdavies**
See: https://sourceforge.net/p/geoserver/mailman/message/35248797/

### CODE REVIEW

**Comment by aaime** [comment]
Failed, @smithkm was reporting a similar problem a few days ago:

````
[ERROR] Failed to execute goal on project gs-script-py: Could not resolve dependencies for project org.geoserver.script:gs-script-py:jar:2.10-SNAPSHOT: Could not find artifact org.geoscript:geoscript-py:jar:1.4-SNAPSHOT in boundless (https://repo.boundlessgeo.com/main/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :gs-script-py
````

**Comment by smithkm** [comment]
Yeah I ended up "fixing" it by building a snapshot of geoscript-py locally.

**Comment by bencaradocdavies** [comment]
The last geoscript-py build failed because of a boundless repo outage, and new builds failed because no explicit Maven version was set. I fixed it and it seems to have passed. I did a ```git commit --amend``` and a ```git push --force``` on the source branch for this PR to trigger another build.

**Comment by bencaradocdavies** [comment]
Success! @aaime I do not think this has too much effect on build time. The main purpose is to detect compile failures in the communityRelease profile that are otherwise overlooked until after merge when ares Jenkins runs.

**Comment by bencaradocdavies** [comment]
I also backported this change to 2.9.x and 2.8.x.

**Pull request merged**
