### PR TITLE
Initial importer docs

### PR DESCRIPTION
**Pull request by jodygarnett**
Gathered up REST API docs from importer extension and added a page of user docs.

### CODE REVIEW

**Comment by jodygarnett** [comment]
Feedback indicates the rest api docs here are wrong. May need to cut this back to a placeholder page.

**Comment by bmmpxf** [comment]
The existing reference materials on REST are stored in the source as hidden (non-built) files. We can revisit REST at another time.

**Comment by aaime** [comment]
Jody, we already had user docs, here: http://docs.geoserver.org/stable/en/user/community/importer/index.html

**Comment by aaime** [comment]
Oh ok, I see you moved them. I'm going to write some REST API docs (slim reference, some examples)

**Comment by bmmpxf** [comment]
@aaime There are two files in the importer doc source directory: ``restrst`` and ``restmd``, which are two versions of an attempted API doc of the Importer, written at different times. None of us were entirely sure in the moment which was most recent or correct (if either), so you may want to start there.

**Comment by aaime** [comment]
Yes,  that is what I'm doing,  trying a bit the rest API as I go to check
if the representations are correct
Il 19/feb/2015 19:05 "bmmpxf" <notifications@github.com> ha scritto:
>
> @aaime There are two files in the importer doc source directory: restrst
and restmd, which are two versions of an attempted API doc of the Importer,
written at different times. None of us were entirely sure in the moment
which was most recent or correct (if either), so you may want to start
there.

**Pull request merged**
