### PR TITLE
Improve doc for WebAdmin Data Layer page

### PR DESCRIPTION
**Pull request by dr-jts**
Improve doc for WebAdmin Data Layer page (headings, formatting, minor text changes)

### CODE REVIEW

**Comment by aaime** [comment]
@bmmpxf do you have any time to look at this one?

**Comment by dr-jts** [comment]
Actually I realize I should have made these changes in a feature branch.  So I"m going to close this PR, fix things up, and issue a new one.

**Comment by jodygarnett** [comment]
Did you manage to submit a new pull request for this @dr-jts?

**Comment by dr-jts** [comment]
Yes. And Andrea merged it.

https://github.com/geoserver/geoserver/pull/1025

**Pull request closed without merging**
